(()=>{'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const steps=['Board','Airframe','Sensors','ESC','Motor idle','Rotation','Receiver','Arm / failsafe','Finish'];
 const names=['Roll','Pitch','Throttle','Yaw','ARM switch','Mode switch'];
 const style=document.createElement('style');style.textContent=`.fc-setup{border:1px solid #37758d;border-radius:12px;padding:16px;background:#102331;color:#dceefa}.fc-setup h3{margin:12px 0;font-size:19px}.fc-setup p{line-height:1.6}.fc-setup .fs-steps{display:flex;gap:6px;flex-wrap:wrap}.fc-setup .fs-steps span{padding:5px 8px;background:#243b4a;border-radius:6px;font-size:11px}.fc-setup .fs-steps .current{background:#087eac;color:white}.fc-setup .fs-steps .done{color:#79efba}.fc-setup .fs-body{min-height:180px}.fc-setup .fs-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.fc-setup .fs-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.fc-setup label{display:block;margin:8px 0;color:#c3dce9;font-size:13px}.fc-setup input[type=checkbox]{display:inline-block;width:22px;vertical-align:middle;margin-right:8px}.fc-setup progress{width:100%;height:16px;accent-color:#44d2ff}.fc-setup table{width:100%;font-size:12px}.fc-setup .fs-scroll{overflow:auto}.fc-setup td{min-width:70px}.fc-setup pre{white-space:pre-wrap;overflow-wrap:anywhere}.fc-setup .fs-status{padding:10px;background:#071a27;border-radius:7px;color:#9edfff;white-space:pre-wrap}.fc-setup .fs-stop{background:#792d35;border-color:#f27781}.fc-setup small{color:#afccd9}.fc-setup select,.fc-setup input{max-width:100%}`;document.head.append(style);
 function mount(root,a,{advanced=()=>{}}={}){
  root.classList.add('fc-setup');let step=0,active=false,session='',id='',epoch=0,busy=false,polling=false,lastPing=0,failures=0,status=null;
  let complete=Array(9).fill(false),gyro=false,level=false,escLowDone=false,escStarted=false,pulse=1050,motor=0,starts=Array(4).fill(null),tested=0,rotation=0,rotationTested=0,testPulse=Array(4).fill(null),source='WEB',armMode='YAW_RIGHT',sweep=false,centres=null,endpoints=null,receiverSaved=false,lossState=0,lossWatching=false,jobWait=null;
  root.innerHTML='<div class="fs-steps"></div><h3 class="fs-title"></h3><div class="fs-body"></div><p class="fs-status" role="status">Connect your kit, remove propellers, then detect the board.</p><div class="fs-actions"><button data-fs="back">Back</button><button data-fs="next">Next</button><button data-fs="stop" class="fs-stop">STOP setup / outputs</button></div>';
  const $=s=>root.querySelector(s),body=$('.fs-body'),note=v=>{$('.fs-status').textContent=v};
  const k=()=>a.kit(),same=()=>k()?.deviceId===id;
  const raw=(type,fields={})=>a.command({type,...fields});
  async function cmd(type,fields={}){if(!active||!same()||!a.owned())throw Error('Setup lost its kit / control session. Start again.');const e=epoch;const r=await raw(type,{...fields,session});if(e!==epoch||!active||!same())throw Error('Setup stopped.');if(r.deviceId&&r.deviceId!==id)throw Error('Different Device ID in setup response.');return r;}
  function buttons(){root.querySelector('[data-fs=back]').disabled=busy||!active||step===0||Number(status?.benchMode||0)!==0;root.querySelector('[data-fs=next]').disabled=busy||!active||!complete[step]||step===8||Number(status?.benchMode||0)!==0;}
  function handle(name,fn){const b=body.querySelector(`[data-fs="${name}"]`);if(!b)return;b.onclick=async()=>{if(busy)return;busy=true;buttons();try{await fn()}catch(e){note(e.message)}finally{busy=false;buttons()}};}
  async function stop(message='Setup stopped. Motors disarmed.'){const old=session,oldId=id;session='';active=false;sweep=false;lossWatching=false;epoch++;if(jobWait){jobWait.reject(Error('Setup stopped.'));jobWait=null}if(old&&k()?.deviceId===oldId)try{await raw('setup_end',{session:old})}catch{}if(old)try{await a.afterSetup?.()}catch{}note(message);buttons();}
  async function begin(){
   if(!body.querySelector('[data-fs=props]').checked)throw Error('Remove every propeller and confirm before setup.');
   await a.ensureConnection?.();const kit=k();if(!kit||kit.armed||Number(kit.benchMode||0))throw Error('Connect the correct kit, disarm and stop bench tests.');
   id=kit.deviceId;const found=await raw('setup_status');if(found.deviceId!==id||!found.supported)throw Error('Guided flight setup requires V18.3.64 A2 Aerion F1. A1 is bridge-only.');
   await a.prepareSetup?.();if(!a.owned())await a.ensureControl();if(!a.owned()||k()?.deviceId!==id)throw Error('Could not take configuration control for this kit.');
   complete=Array(9).fill(false);gyro=level=escLowDone=escStarted=receiverSaved=false;starts=Array(4).fill(null);tested=rotation=0;centres=endpoints=null;lossState=0;source=found.input==='PPM'?'PPM':'WEB';armMode=found.receiver?.armMode||'YAW_RIGHT';
   session='SETUP-'+(crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2));const token=session,e=++epoch;active=true;
   try{const r=await raw('setup_begin',{session:token,confirm:'PROPS_REMOVED'});if(e!==epoch||!active||!same()){if(k()?.deviceId===id)await raw('setup_end',{session:token});return}status=r;complete[0]=true;lastPing=performance.now();failures=0;note(`Detected ${r.boardId} · ${id} · firmware ${r.firmware}. Arming is inhibited during setup.`);render();}catch(error){if(e===epoch){active=false;buttons()}throw error;}
  }
  async function waitFor(predicate,timeout=15000){if(jobWait)throw Error('Another setup job is pending.');return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{if(jobWait){jobWait=null;reject(Error('Operation timed out. Check the controller status and retry.'));}},timeout);jobWait={predicate,resolve:r=>{clearTimeout(timer);resolve(r)},reject:e=>{clearTimeout(timer);reject(e)}};});}
  async function motorTest(mask,value=pulse){const r=await cmd('setup_motor',{mask,pulse:value,durationMs:800,confirm:'PROPS_REMOVED'});status=r;await waitFor(s=>s.benchMode===0,4500);tested|=mask;for(let i=0;i<4;i++)if(mask&(1<<i))testPulse[i]=value;note(`800 ms motor test finished at ${value} µs. Confirm the physical response.`);}
  function rxFields(){const maps=[...body.querySelectorAll('[data-rx-map]')].map(x=>Number(x.value));if(new Set(maps).size!==6)throw Error('Choose six distinct PPM channels.');if(!endpoints||!centres)throw Error('Sweep all sticks / switches and capture centres first.');const f={armMode};maps.forEach((ch,i)=>{f['map'+i]=ch;f['min'+i]=endpoints.min[ch-1];f['max'+i]=endpoints.max[ch-1];f['centre'+i]=centres[ch-1];if(f['max'+i]-f['min'+i]<400)throw Error(names[i]+' needs at least 400 µs travel.');if(i<4)f['reverse'+i]=Number(body.querySelector(`[data-rx-reverse="${i}"]`).checked)});return f;}
  async function saveReceiver(){const f=rxFields();await cmd('input_set',{source:'PPM'});await cmd('receiver_setup_set',f);const r=await cmd('receiver_setup_get');for(let i=0;i<6;i++)if(r.receiver.map[i]!==f['map'+i]||r.receiver.minimum[i]!==f['min'+i]||r.receiver.centre[i]!==f['centre'+i]||r.receiver.maximum[i]!==f['max'+i]||i<4&&!!r.receiver.reverse[i]!==!!f['reverse'+i])throw Error('Receiver readback differs; retry calibration.');if(r.receiver.armMode!==armMode)throw Error('Arm mode readback differs.');status.receiver=r.receiver;receiverSaved=true;complete[6]=true;note('PPM mapping, endpoints, centres, reversal and ARM mode saved and read back.');}
  function render(){
   $('.fs-title').textContent=`${step+1}. ${steps[step]}`;$('.fs-steps').innerHTML=steps.map((v,i)=>`<span class="${i===step?'current':complete[i]?'done':''}">${i+1} ${v}</span>`).join('');
   if(step===0){body.innerHTML=`<p>Detect the connected flight controller and permanent Device ID.</p><label><input data-fs="props" type="checkbox">All propellers are removed</label><button data-fs="detect">Detect board / start setup</button><pre>${status?esc(status.boardId+' · '+status.deviceId+' · '+status.firmware+' · IMU '+(k()?.sensors?.imu?.model||k()?.imuModel||'not reported')):'No board detected'}</pre>`;handle('detect',begin);}
   if(step===1){body.innerHTML='<p>Choose a supported vehicle and motor geometry.</p><div class="fs-grid"><label>Vehicle<select><option>Quadcopter</option><option disabled>Hexacopter — unsupported</option><option disabled>Fixed wing — unsupported</option></select></label><label>Frame<select data-fs="airframe"><option value="QUAD_X">Quad X</option><option value="QUAD_H">Quad H</option></select></label></div><p><small>Both layouts use the existing front-left / front-right / rear-right / rear-left mixer. Verify physical motor positions in the rotation step.</small></p><button data-fs="saveFrame">Save airframe</button>';body.querySelector('[data-fs=airframe]').value=status?.airframe||'QUAD_X';handle('saveFrame',async()=>{status=await cmd('airframe_set',{airframe:body.querySelector('[data-fs=airframe]').value});complete[1]=true;note('Airframe saved: '+status.airframe)});}
   if(step===2){body.innerHTML=`<p>Keep the frame level and still. Progress comes from actual FC samples.</p><progress max="100" value="0"></progress><p data-fs="progress">Gyro ${gyro?'✓':'pending'} · accelerometer ${level?'✓':'pending'}</p><div class="fs-actions"><button data-fs="gyro">Calibrate gyro</button><button data-fs="level">Calibrate accelerometer / level</button></div>`;for(const kind of ['gyro','level'])handle(kind,async()=>{status=await cmd('setup_calibrate',{kind});const done=await waitFor(s=>s.job===2||s.job===3,12000);if(done.job!==2)throw Error('Calibration failed / cancelled. Hold the frame level and still, check the IMU, then retry.');if(kind==='gyro')gyro=true;else level=true;complete[2]=gyro&&level;note(kind+' calibration completed.');render()});}
   if(step===3){body.innerHTML=`<p>PWM ESC calibration: follow your ESC manufacturer's power and beep sequence. Disconnect motor battery before HIGH, then connect it when instructed. Props must be removed.</p><p data-fs="escStatus">Outputs idle</p><div class="fs-actions"><button data-fs="high">Start HIGH 2000 µs (12 s maximum)</button><button data-fs="low">Send LOW 1000 µs (3 s)</button></div><label><input data-fs="tones" type="checkbox">LOW finished and manufacturer success tones confirmed</label><label><input data-fs="skipEsc" type="checkbox">These ESCs are already calibrated; skip this step</label><button data-fs="confirmEsc">Confirm ESC status</button>`;handle('high',async()=>{status=await cmd('setup_esc',{stage:'HIGH',confirm:'PROPS_REMOVED'});escStarted=true;escLowDone=false;complete[3]=false;note('HIGH active. Connect ESC battery per manufacturer instructions, then press LOW.');});handle('low',async()=>{if(!escStarted)throw Error('Start HIGH first.');status=await cmd('setup_esc',{stage:'LOW',confirm:'PROPS_REMOVED'});await waitFor(s=>s.benchMode===0,6000);escLowDone=true;note('LOW completed. Confirm the actual ESC tones.');});handle('confirmEsc',async()=>{if(status.benchMode)throw Error('Wait for outputs to stop.');if(!body.querySelector('[data-fs=skipEsc]').checked&&!(escLowDone&&body.querySelector('[data-fs=tones]').checked))throw Error('Complete HIGH → LOW and confirm tones, or explicitly select already calibrated.');complete[3]=true;note('ESC status confirmed by pilot.');});}
   if(step===4){body.innerHTML=`<p>Find each motor's reliable starting pulse. No RPM sensor is installed; mark only a pulse you physically observed starting the motor. Each test stops after 800 ms.</p><label>Motor<select data-fs="motor">${Array.from({length:4},(_,i)=>`<option value="${i}">M${i+1}</option>`).join('')}</select></label><div class="fs-actions"><button data-fs="minus">−5 µs</button><b data-fs="pulse">${pulse} µs</b><button data-fs="plus">+5 µs</button><button data-fs="testMinimum">Test selected motor</button><button data-fs="markStart">Mark observed start</button></div><pre>${starts.map((v,i)=>'M'+(i+1)+': '+(v||'pending')).join(' · ')}</pre><button data-fs="saveIdle">Save idle = highest start + 20 µs</button>`;body.querySelector('[data-fs=motor]').value=motor;body.querySelector('[data-fs=motor]').onchange=e=>{motor=Number(e.target.value)};for(const [n,delta] of [['minus',-5],['plus',5]])handle(n,async()=>{pulse=Math.max(1000,Math.min(1300,pulse+delta));body.querySelector('[data-fs=pulse]').textContent=pulse+' µs';tested&=~(1<<motor)});handle('testMinimum',()=>motorTest(1<<motor));handle('markStart',async()=>{if(testPulse[motor]!==pulse)throw Error('Run this motor at the selected pulse first.');starts[motor]=pulse;render()});handle('saveIdle',async()=>{if(starts.some(v=>v===null))throw Error('Observe all four motor starting points first.');const idle=Math.max(1050,Math.max(...starts)+20);if(idle>1250)throw Error('Required idle exceeds supported 1250 µs. Check motor / ESC setup.');await cmd('flight_settings_set',{idleUs:idle});const r=await cmd('snapshot_get');if(r.flightSettings?.idleUs!==idle)throw Error('Idle readback differs.');complete[4]=true;note('Motor idle saved and read back: '+idle+' µs.');});}
   if(step===5){body.innerHTML=`<p>Top view: M1 front-left CW, M2 front-right CCW, M3 rear-right CW, M4 rear-left CCW. Check real wiring and spin direction.</p>${['Front-left · CW','Front-right · CCW','Rear-right · CW','Rear-left · CCW'].map((v,i)=>`<label><input data-motor="${i}" type="checkbox" ${rotation&(1<<i)?'checked':''}>M${i+1}: ${v}</label>`).join('')}<label>Run<select data-fs="runMask">${Array.from({length:4},(_,i)=>`<option value="${1<<i}">M${i+1} only</option>`).join('')}<option value="15">All motors</option></select></label><button data-fs="rotationTest">Run 800 ms at saved idle</button><p><small>Fix wiring / ESC direction physically. Motor connector routing is shown below and can be changed in Hardware I/O after ending setup.</small></p><pre data-fs="routing">Reading motor routing…</pre>`;raw('pinmap_get').then(r=>{const node=body.querySelector('[data-fs=routing]');if(node)node.textContent=(r.expansion?.motors||r.motors||[]).map(x=>`M${x.motor}: ${x.connector}`).join(' · ')}).catch(()=>{});handle('rotationTest',async()=>{const r=await cmd('snapshot_get');const mask=Number(body.querySelector('[data-fs=runMask]').value);await motorTest(mask,r.flightSettings.idleUs);rotationTested|=mask});body.querySelectorAll('[data-motor]').forEach(x=>x.onchange=()=>{const bit=1<<Number(x.dataset.motor);if(x.checked&&!(rotationTested&bit)){x.checked=false;note('Run this motor before confirming its position / direction.');return}rotation=x.checked?rotation|bit:rotation&~bit;complete[5]=rotation===15;buttons()});}
   if(step===6){body.innerHTML=`<label>RC input<select data-fs="source"><option value="WEB">App / Web</option><option value="PPM">Physical PPM receiver</option></select></label><button data-fs="saveInput">Save input</button><div data-fs="ppm" ${source==='PPM'?'':'hidden'}><p>Sweep every stick and both switches to their limits, then release directional sticks to centre, throttle to minimum and ARM low. Map six distinct channels.</p><div class="fs-actions"><button data-fs="sweep">Start endpoint sweep</button><button data-fs="centres">Stop sweep / capture centres</button></div><div class="fs-scroll"><table><thead><tr><th>Function</th><th>Channel</th><th>Reverse</th><th>Min / centre / max</th><th>Raw → normalised</th></tr></thead><tbody>${names.map((n,i)=>`<tr><td>${n}</td><td><select data-rx-map="${i}">${Array.from({length:10},(_,j)=>`<option value="${j+1}" ${j===(status?.receiver?.map?.[i]??i+1)-1?'selected':''}>CH${j+1}</option>`).join('')}</select></td><td>${i<4?`<input data-rx-reverse="${i}" type="checkbox" ${status?.receiver?.reverse?.[i]?'checked':''}>`:'—'}</td><td data-rx-values="${i}">—</td><td data-rx-live="${i}">—</td></tr>`).join('')}</tbody></table></div><button data-fs="saveReceiver">Save / verify endpoints</button></div>`;body.querySelector('[data-fs=source]').value=source;body.querySelector('[data-fs=source]').onchange=e=>{source=e.target.value;receiverSaved=false;complete[6]=false;body.querySelector('[data-fs=ppm]').hidden=source!=='PPM';buttons()};handle('saveInput',async()=>{status=await cmd('input_set',{source});complete[6]=source==='WEB'||receiverSaved;note('RC source saved: '+source)});handle('sweep',async()=>{if(!status.ppmFresh)throw Error('No fresh PPM frames. Check receiver, pin and signal edge.');endpoints={min:Array(10).fill(2250),max:Array(10).fill(750)};centres=null;sweep=true;complete[6]=false;note('Move all sticks and switches through full travel.');});handle('centres',async()=>{if(!sweep||!status.ppmFresh)throw Error('Start a sweep with fresh PPM first.');sweep=false;centres=[...status.raw];note('Centres captured. Save endpoints after checking mapping / reverse.');});handle('saveReceiver',saveReceiver);}
   if(step===7){body.innerHTML=source==='PPM'?`<label>PPM arm method<select data-fs="armMode"><option value="YAW_RIGHT">Yaw right ARM / left DISARM</option><option value="YAW_LEFT">Yaw left ARM / right DISARM</option><option value="CH5_SWITCH">Mapped ARM switch</option></select></label><p>Yaw gestures require low throttle, centred pitch / roll and a 1 second hold. Arming stays inhibited throughout setup.</p><button data-fs="saveArm">Save arm method</button><p>Configure receiver RF-loss mode to stop PPM pulses. A receiver that keeps sending held values cannot tell the FC that RF was lost.</p><button data-fs="watchLoss">Start loss / restore check</button><p data-fs="loss">Switch transmitter OFF, wait for stale frames, then ON.</p><button data-fs="confirmLoss">Confirm observed loss and restore</button>`:`<p>App / Web uses manual ARM (CH5). A brief RC gap retains throttle / ARM and centres directional axes; prolonged loss disarms. Reconnection returns to minimum throttle and requires a new manual ARM.</p><p>RC timeout from this controller: ${esc(k()?.rcTimeoutMs||1000)} ms. This is a displayed policy, not a physical flight test.</p><label><input data-fs="webPolicy" type="checkbox">I have reviewed the connection-loss and manual re-arm policy</label><button data-fs="confirmWeb">Confirm policy</button>`;if(source==='PPM'){body.querySelector('[data-fs=armMode]').value=armMode;handle('saveArm',async()=>{if(!receiverSaved)throw Error('Calibrate receiver first.');armMode=body.querySelector('[data-fs=armMode]').value;const r=status.receiver,f={armMode};for(let i=0;i<6;i++){f['map'+i]=r.map[i];f['min'+i]=r.minimum[i];f['max'+i]=r.maximum[i];f['centre'+i]=r.centre[i];if(i<4)f['reverse'+i]=Number(r.reverse[i])}await cmd('receiver_setup_set',f);const read=await cmd('receiver_setup_get');if(read.receiver.armMode!==armMode)throw Error('Arm mode readback differs.');status.receiver=read.receiver;complete[7]=false;lossState=0;lossWatching=false;note('Arm method saved. Complete receiver loss / restore check.');});handle('watchLoss',async()=>{lossState=status.ppmFresh?1:0;lossWatching=true;complete[7]=false;note('Transmitter ON must be observed first. Then switch OFF until frames become stale, then ON.');});handle('confirmLoss',async()=>{if(lossState!==3)throw Error('Observe fresh → stale → fresh PPM frames first.');if(body.querySelector('[data-fs=armMode]').value!==status.receiver.armMode)throw Error('Save the selected arm mode first.');complete[7]=true;lossWatching=false;note('PPM loss and restore observed with motors disarmed.');});}else handle('confirmWeb',async()=>{if(!body.querySelector('[data-fs=webPolicy]').checked)throw Error('Review and acknowledge the policy first.');complete[7]=true;note('Connection-loss policy acknowledged.');});}
   if(step===8){body.innerHTML=`<p>Configuration completed for <b>${esc(id)}</b>. Finish leaves the motors disarmed. Re-enable flight control and ARM manually after all physical checks.</p><pre>${esc(JSON.stringify({board:status.boardId,airframe:status.airframe,input:source,motorStartUs:starts,armMode:source==='PPM'?armMode:'MANUAL_CH5',physicalFlightTested:false},null,2))}</pre><div class="fs-actions"><button data-fs="finish">Finish / save setup record</button><button data-fs="pid">Finish and open advanced PID</button></div>`;async function finish(){const record={version:'18.3.64',deviceId:id,completedAt:new Date().toISOString(),airframe:status.airframe,input:source,motorStartUs:starts,armMode:source==='PPM'?armMode:'MANUAL_CH5',physicalFlightTested:false};await stop('Setup finished. Motors disarmed; ARM manually after physical checks.');try{localStorage.setItem('aerion-fc-setup-'+id,JSON.stringify(record))}catch{}}handle('finish',finish);handle('pid',async()=>{await finish();advanced()});}
   buttons();
  }
  async function poll(){if(!active||polling)return;if(document.hidden||!same()||!a.owned()||!root.isConnected||root.closest('dialog')&&!root.closest('dialog').open){await stop('Setup stopped because the kit, page or control ownership changed.');return}polling=true;const e=epoch;try{const now=performance.now(),ping=now-lastPing>1000;if(ping)lastPing=now;const d=await cmd(ping?'setup_ping':'setup_status');if(e!==epoch)return;status=d;failures=0;if(!d.active||d.session!==session||d.armed){await stop('Setup session expired or changed. Motors disarmed. Start again.');return}const progress=body.querySelector('progress');if(progress)progress.value=d.total?Math.min(100,d.samples/d.total*100):0;const p=body.querySelector('[data-fs=progress]');if(p)p.textContent=`${d.samples} / ${d.total} samples · ${d.job===1?'running':d.job===2?'complete':d.job===3?'failed':'idle'} · gyro ${gyro?'✓':'pending'} · level ${level?'✓':'pending'}`;const eNode=body.querySelector('[data-fs=escStatus]');if(eNode)eNode.textContent=d.benchMode===4?(d.pulse===2000?'HIGH 2000 µs active — send LOW after tones':'LOW 1000 µs — wait for completion'):'Outputs idle';if(sweep&&d.ppmFresh)d.raw.forEach((v,i)=>{endpoints.min[i]=Math.min(endpoints.min[i],v);endpoints.max[i]=Math.max(endpoints.max[i],v)});body.querySelectorAll('[data-rx-map]').forEach(x=>{const i=Number(x.dataset.rxMap),ch=Number(x.value)-1;body.querySelector(`[data-rx-values="${i}"]`).textContent=endpoints?`${endpoints.min[ch]} / ${centres?.[ch]??'—'} / ${endpoints.max[ch]}`:'—';body.querySelector(`[data-rx-live="${i}"]`).textContent=`${d.raw[ch]} → ${d.channels[i]}`});if(lossWatching){if(lossState===0&&d.ppmFresh)lossState=1;else if(lossState===1&&!d.ppmFresh)lossState=2;else if(lossState===2&&d.ppmFresh)lossState=3;const n=body.querySelector('[data-fs=loss]');if(n)n.textContent=['Waiting for transmitter ON','Fresh PPM observed. Switch transmitter OFF.','Stale PPM observed. Switch transmitter ON.','Loss and restore observed. Confirm to continue.'][lossState]}if(jobWait&&jobWait.predicate(d)){const w=jobWait;jobWait=null;w.resolve(d)}}catch(e){if(active&&++failures>=3)await stop('Setup connection lost. FC stops outputs on lease expiry. Reconnect and start again.')}finally{polling=false;buttons()}}
  root.querySelector('[data-fs=next]').onclick=()=>{if(active&&!busy&&complete[step]){step++;render()}};root.querySelector('[data-fs=back]').onclick=()=>{if(active&&!busy&&step>0){sweep=false;step--;render()}};root.querySelector('[data-fs=stop]').onclick=()=>stop();
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stop('Setup paused / stopped because the app became hidden.')});addEventListener('pagehide',()=>stop());root.closest('dialog')?.addEventListener('close',()=>stop());root.closest('dialog')?.addEventListener('cancel',()=>stop());setInterval(poll,300);render();
  return {stop,update:()=>{if(active&&(!same()||!a.owned()))stop('Setup ownership changed.');buttons()},get active(){return active}};
 }
 window.AerionFcSetup={mount};
})();
