/* ZEBJUS Hardware I/O Studio: same verified Device ID and control lock as Python. */
(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const pins=[['Off',-1],['D7 / GPIO17',17],['D8 / GPIO19',19],['D9 / GPIO20',20],['D10 / GPIO18',18]];
const fallback=[1,2,3,0],positions=['FRONT RIGHT • CW','FRONT LEFT • CCW','REAR LEFT • CW','REAR RIGHT • CCW'];
let current=null,lastDevice='',lastStatusRead=0,matrix=Array(8).fill(0),busy=false;
function school(){return window.zebjusSchool}
function format(o){return typeof o==='string'?o:JSON.stringify(o,null,2)}
function output(id,message,error=false){const e=$('#'+id);if(e){e.textContent=format(message);e.classList.toggle('error',error);e.scrollTop=e.scrollHeight}}
function num(v){const x=Number(String(v??'').trim());if(!Number.isInteger(x))throw Error('Use a decimal or 0x hexadecimal integer.');return x}
function mapping(){return Array.isArray(current?.motors)&&current.motors.length===4?current.motors.map((m,i)=>{const n=Number(String(m.connector||'').replace('D',''));return n>=0&&n<=3?n:fallback[i]}):[...fallback]}
function mapRows(id,scope){const box=$('#'+id);if(!box)return;box.innerHTML=positions.map((name,i)=>`<label>M${i+1} • ${name}<select data-io-slot="${i}" data-map-scope="${scope}">${[0,1,2,3].map(n=>`<option value="${n}">D${n} • GPIO ${[0,1,2,21][n]}</option>`).join('')}</select></label>`).join('')}
function chosen(scope){return $$(`[data-map-scope="${scope}"]`).map(el=>Number(el.value))}
function setMap(scope,values){$$(`[data-map-scope="${scope}"]`).forEach((el,i)=>el.value=String(values[i]))}
function setExpansion(exp){if(!exp)return;current=exp;window.zebjusExpansion=exp;const slots=mapping();setMap('io',slots);setMap('wire',slots);slots.forEach((v,i)=>{const e=$(`[data-io-motor="${i+1}"]`);if(e)e.textContent=`D${v}`});$('#ioPpmEdge').value=exp.ppmEdge||'RISING';$$('[data-io-reverse]').forEach(el=>el.checked=!!exp.ppmReverse?.[Number(el.dataset.ioReverse)]);$('#ioServoPin').value=String(exp.servoPin??-1);$('#ioGpsPin').value=String(exp.gpsRxPin??-1);$('#ioMatrixAddress').value=String(exp.matrixAddress??112);window.dispatchEvent(new Event('zebjus-expansion-change'))}
async function refresh(force=false){const api=school(),d=api?.getSelectedDevice?.();if(!api?.isKitActive?.()){const e=$('#ioConnection');if(e){e.textContent='CONNECT KIT';e.className='status'};if(lastDevice)setExpansion({motors:fallback.map(n=>({connector:`D${n}`})),ppmEdge:'RISING',ppmReverse:[false,false,false,false],servoPin:-1,gpsRxPin:-1,matrixAddress:112});lastDevice='';return}const id=d?.deviceId||'';if(force||id!==lastDevice||Date.now()-lastStatusRead>5000){try{const status=await api.client.refresh();lastDevice=id;lastStatusRead=Date.now();setExpansion(status.expansion);output('wireMotorMapResult',`${status.boardId} • ${id}\n${mapping().map((n,i)=>`M${i+1} → D${n}`).join(' • ')}`)}catch(e){output('wireMotorMapResult',e.message,true)}}const e=$('#ioConnection');if(e){e.textContent=`${d?.boardId||'KIT'} • ${d?.name||id}`;e.className='status good'}const badge=$('#ioFlightStatus');if(badge){badge.textContent=d?.armed?'ARMED • EDITS BLOCKED':'DISARMED • I/O READY';badge.className='status '+(d?.armed?'warn':'good')}const a2=d?.boardId==='ZFC-A2';['ioSaveMotors','wireSaveMotorMap','ioServoConfig','ioServoSend','ioServoCenter','ioGpsConfig','ioGpioWrite','ioGpioRelease'].forEach(x=>{const b=$('#'+x);if(b)b.disabled=!a2||!!d?.armed});$$('#ioMotorTests button').forEach(b=>b.disabled=!a2||!!d?.armed)}
async function command(type,data={},dest='ioAuxResult'){if(busy)throw Error('Wait for the previous hardware command.');if(!school()?.isKitActive?.())throw Error('Connect the exact ZEBJUS kit in Kit Connect first.');busy=true;try{const reply=await school().commandDevice({type,...data});if(reply?.expansion)setExpansion(reply.expansion);output(dest,reply);return reply}catch(e){output(dest,e.message,true);throw e}finally{busy=false}}
function action(id,fn,dest='ioAuxResult'){$('#'+id)?.addEventListener('click',()=>Promise.resolve().then(fn).catch(e=>output(dest,e.message,true)))}
async function saveMotor(scope){const v=chosen(scope),dest=scope==='wire'?'wireMotorMapResult':'ioPpmResult';if(new Set(v).size!==4)throw Error('M1–M4 must use four different D0–D3 motor connectors.');if(!confirm('Save motor routing and reboot the real FC? Remove propellers and verify M1–M4 with individual tests after reconnecting.'))return;await command('motor_map_set',Object.fromEntries(v.map((n,i)=>[`m${i+1}slot`,n])),dest)}
function init(){if(!$('#tab-io'))return;mapRows('ioMotorMapRows','io');mapRows('wireMotorMapRows','wire');
 $$('.io-aux-options').forEach(sel=>sel.innerHTML=pins.map(([label,v])=>`<option value="${v}">${label}</option>`).join(''));$('#ioGpioPin').innerHTML=pins.filter(x=>x[1]>=0).map(([label,v])=>`<option value="${v}">${label}</option>`).join('');setExpansion({motors:fallback.map(n=>({connector:`D${n}`})),ppmEdge:'RISING',ppmReverse:[false,false,false,false],servoPin:-1,gpsRxPin:-1,matrixAddress:112});
 const grid=$('#ioMatrixGrid');for(let i=0;i<64;i++){const b=document.createElement('button');b.type='button';b.title=`Row ${Math.floor(i/8)+1}, column ${i%8+1}`;b.setAttribute('aria-pressed','false');b.onclick=()=>{const row=Math.floor(i/8),bit=1<<(i%8);matrix[row]^=bit;b.classList.toggle('on',!!(matrix[row]&bit));b.setAttribute('aria-pressed',b.classList.contains('on')?'true':'false')};grid.appendChild(b)}
 const tests=$('#ioMotorTests');[1,2,3,4].forEach(i=>{const b=document.createElement('button');b.className='btn ghost small';b.textContent=`Test M${i}`;b.onclick=()=>{if(!confirm(`M${i}: Confirm ALL propellers are removed and the frame is secured for a 0.5-second low-pulse test.`))return;command('motor_test',{motor:i,pulse:1150,durationMs:500,confirm:'PROPS_REMOVED'},'ioPpmResult').catch(()=>{})};tests.appendChild(b)});
 action('ioReadMotors',()=>refresh(true),'ioPpmResult');action('wireReadMotorMap',()=>refresh(true),'wireMotorMapResult');action('ioSaveMotors',()=>saveMotor('io'),'ioPpmResult');action('wireSaveMotorMap',()=>saveMotor('wire'),'wireMotorMapResult');action('wireOpenIo',()=>$('.tab[data-tab="io"]')?.click());action('ioMotorStop',()=>command('motor_stop',{},'ioPpmResult'),'ioPpmResult');
 action('ioSavePpm',()=>command('ppm_config',{edge:$('#ioPpmEdge').value,...Object.fromEntries($$('[data-io-reverse]').map(el=>[`reverse${el.dataset.ioReverse}`,el.checked?1:0]))},'ioPpmResult'),'ioPpmResult');action('ioReadPpm',()=>command('receiver_read',{},'ioPpmResult'),'ioPpmResult');
 action('ioScan',async()=>{if(!school()?.isKitActive?.())throw Error('Connect a real kit first.');const r=await school().i2cScan(),box=$('#ioDevices');box.replaceChildren();for(const d of r.devices||[]){const b=document.createElement('button');b.textContent=`${d.addressHex} • ${d.hint||'I²C device'}`;b.onclick=()=>{$('#ioI2cAddress').value=d.addressHex;$('#ioMatrixAddress').value=String(d.address)};box.appendChild(b)}if(!r.devices?.length)box.textContent='No I²C ACK. Check 3.3 V power, common ground, SDA/SCL, pullups and addresses.';output('ioI2cResult',`${r.count} device(s) • ${r.durationMs} ms • ${r.errorCount||0} bus errors`)} ,'ioI2cResult');
 action('ioI2cRead',()=>command('i2c_read',{address:num($('#ioI2cAddress').value),reg:num($('#ioI2cReg').value),length:num($('#ioI2cLength').value)},'ioI2cResult'),'ioI2cResult');action('ioI2cWrite',()=>command('i2c_write',{address:num($('#ioI2cAddress').value),reg:num($('#ioI2cReg').value),bytes:$('#ioI2cBytes').value.trim()},'ioI2cResult'),'ioI2cResult');
 action('ioServoConfig',()=>command('servo_config',{pin:Number($('#ioServoPin').value)},'ioAuxResult'));action('ioServoCenter',()=>command('servo_write',{pulseUs:1500},'ioAuxResult'));$('#ioServoPulse').oninput=e=>$('#ioServoPulseOut').textContent=`${e.target.value} µs`;action('ioServoSend',()=>command('servo_write',{pulseUs:Number($('#ioServoPulse').value)},'ioAuxResult'));
 action('ioGpioRead',()=>command('gpio_read',{pin:Number($('#ioGpioPin').value)},'ioAuxResult'));action('ioGpioWrite',()=>command('gpio_write',{pin:Number($('#ioGpioPin').value),value:Number($('#ioGpioValue').value)},'ioAuxResult'));action('ioGpioRelease',()=>command('gpio_release',{pin:Number($('#ioGpioPin').value)},'ioAuxResult'));
 action('ioGpsConfig',()=>command('gps_config',{pin:Number($('#ioGpsPin').value)},'ioGpsResult'),'ioGpsResult');action('ioGpsRead',()=>command('gps_read',{},'ioGpsResult'),'ioGpsResult');
 action('ioMatrixSend',async()=>{const address=Number($('#ioMatrixAddress').value);if(Number(current?.matrixAddress)!==address)await command('matrix_config',{address},'ioMatrixResult');await command('matrix_write',{rows:matrix.join(',')},'ioMatrixResult')},'ioMatrixResult');action('ioMatrixClear',async()=>{matrix.fill(0);$$('#ioMatrixGrid button').forEach(b=>{b.classList.remove('on');b.setAttribute('aria-pressed','false')});await command('matrix_write',{rows:matrix.join(',')},'ioMatrixResult')},'ioMatrixResult');
 window.addEventListener('zebjus-device-command-result',e=>{if(e.detail?.ok&&e.detail.response?.expansion){setExpansion(e.detail.response.expansion);lastStatusRead=Date.now()}});$$('.tab[data-tab]').forEach(t=>t.addEventListener('click',()=>{if(t.dataset.tab==='io'||t.dataset.tab==='wiring')refresh(false)}));setInterval(()=>{if($('#tab-io')?.classList.contains('active')||$('#tab-wiring')?.classList.contains('active'))refresh(false)},2500);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
