(()=>{'use strict';
function confirmInLab(message){return window.AerionDialogs?.confirm(message)??Promise.resolve(confirm(message))}

 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const axes=['rateRoll','ratePitch','rateYaw','angleRateRoll','angleRatePitch','angleRateYaw','angleRoll','anglePitch'];
 const fields=[['maxTilt','Angle limit (°)',5,50],['maxRate','Rate limit (°/s)',20,300],['gyroHz','Gyro filter (Hz)',10,100],['dtermHz','D-term filter (Hz)',5,80],['idleUs','Motor idle (µs)',1050,1250],['maxMotorUs','Motor maximum (µs)',1700,2000],['maxThrottle','Throttle maximum (µs)',1300,1900],['cells','Battery cells',1,6],['batteryFactor','Voltage calibration multiplier',.5,1.5],['lowCell','Low battery (V/cell)',3,4],['criticalCell','Critical battery (V/cell)',2.8,3.9]];
 const style=document.createElement('style');style.textContent=`.kit-console{color:inherit;font:14px/1.5 system-ui;user-select:text}.kit-console h3{font-size:17px;margin:22px 0 12px}.kit-console .kc-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.kit-console button{border:1px solid #405063;border-radius:8px;background:#152330;color:#dcecf5;min-height:42px;padding:8px 13px;font:inherit;cursor:pointer}.kit-console button:disabled{opacity:.4;cursor:default}.kit-console .kc-tab.active{background:#078ab7;color:white}.kit-console .kc-page[hidden]{display:none}.kit-console .kc-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:12px}.kit-console label{font-size:12px;color:#9fbdcb;display:block}.kit-console input,.kit-console select{display:block;width:100%;margin-top:5px;padding:9px;border:1px solid #405063;border-radius:7px;background:#0b151f;color:#e9f6fd;font:inherit;min-height:38px}.kit-console input[type=checkbox]{width:24px}.kit-console table{width:100%;border-collapse:collapse}.kit-console th,.kit-console td{padding:6px;text-align:left;font-size:12px}.kit-console .kc-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.kit-console .kc-message{white-space:pre-wrap;border:1px solid #344b5d;background:#081722;border-radius:8px;padding:10px;margin:12px 0;color:#9cdbf7;max-height:160px;overflow:auto}.kit-console .kc-note{font-size:12px;color:#9db2bf}.kit-console canvas{display:block;width:100%;height:150px;border:1px solid #263e51;border-radius:8px;margin:8px 0;background:#08111b}.kit-console .kc-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:8px}.kit-console .kc-stats span{padding:8px;background:#101e2b;border-radius:8px;font-size:12px}.kit-console .kc-stats b{display:block;color:#9be1ff}.kit-console .kc-pid input{min-width:55px;padding:6px}.kit-console input:disabled,.kit-console select:disabled{opacity:.55}@media(max-width:520px){.kit-console{font-size:12px}.kit-console .kc-grid{grid-template-columns:1fr 1fr}}`;document.head.append(style);
 function download(name,data,type='application/json'){if(window.AerionAndroid?.saveFile){window.AerionAndroid.saveFile(name,data,type);return}const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
 function mount(root,adapter,{wizard=true}={}){
  root.classList.add('kit-console');root.innerHTML=`<div class="kc-message" data-kc="message">Connect the correct kit to read settings. Changes need control and disarmed motors.</div><button data-kc="setupWizard" ${wizard?'':'hidden'}>FC Setup Wizard</button><div class="kc-tabs">${['Wi-Fi','Controls','PID','Calibration','Diagnostics','FC Setup'].map((x,i)=>`<button class="kc-tab ${i===0?'active':''}" data-kc-tab="${i}">${x}</button>`).join('')}</div>
<section class="kc-page" data-kc-page="0"><h3>Kit Wi-Fi</h3><p class="kc-note">Change this kit between AP and saved STA Wi-Fi. Disarm before switching. AP password: 12345678.</p><div class="kc-actions"><button data-kc="switchAp" data-write>Activate AP</button><button data-kc="scan">Scan nearby Wi-Fi</button><button data-kc="saved">Read saved Wi-Fi</button></div><div class="kc-grid"><label>Saved network<select data-kc="savedSsid"></select></label><label>Nearby network<select data-kc="nearby"></select></label><label>New Wi-Fi SSID<input data-kc="ssid" maxlength="32"></label><label>Router password<input data-kc="password" type="password" maxlength="63" autocomplete="off"></label></div><div class="kc-actions"><button data-kc="useSaved" data-write>Activate saved STA</button><button data-kc="saveWifi" data-write>Save &amp; test / restart</button></div></section>
<section class="kc-page" data-kc-page="1" hidden><h3>RC control source</h3><p class="kc-note">Fresh valid PPM is always primary for real flight. Handover needs a fresh standby, matching throttle/sticks, high ARM channel and attitude within 45°. A rejected request keeps the current source.</p><div class="kc-row"><select data-kc="rcSource"><option value="AUTO">Automatic · PPM first</option><option value="WEB">App standby · PPM first</option><option value="PPM">PPM only</option></select><button data-kc="handover">Apply RC source</button></div><h3>Joystick feel</h3><div class="kc-grid"><label>Floating centers<input data-kc="floating" type="checkbox"></label><label>Sensitivity (0.2–1)<input data-kc="sensitivity" type="number" min=".2" max="1" step=".05"></label><label>Center deadband (0–0.2)<input data-kc="deadband" type="number" min="0" max=".2" step=".01"></label><label>Expo (0–0.8)<input data-kc="expo" type="number" min="0" max=".8" step=".05"></label><label>Throttle change (µs/s)<input data-kc="throttleSpeed" type="number" min="100" max="600" step="25"></label></div><button data-kc="saveFeel">Save joystick feel</button><h3>Controller limits, filters and battery</h3><div class="kc-grid">${fields.map(([k,t,min,max])=>`<label>${t}<input data-setting="${k}" type="number" min="${min}" max="${max}" step="${k==='batteryFactor'?'.001':k.endsWith('Cell')?'.05':'1'}" data-write></label>`).join('')}<label>IMU mounting<select data-setting="orientation" data-write>${Array.from({length:8},(_,i)=>`<option value="${i}">${i>=4?'Upside-down':'Upright'} · yaw ${(i%4)*90}°</option>`).join('')}</select></label><label>Battery monitor<select data-setting="batteryKind" data-write><option value="0">Not installed</option><option value="1">INA219 bus voltage</option><option value="2">INA226 bus voltage</option></select></label><label>I²C monitor address<select data-setting="batteryAddress" data-write>${Array.from({length:16},(_,i)=>`<option value="${64+i}">0x${(64+i).toString(16).toUpperCase()}</option>`).join('')}</select></label><label>In-flight Rate ↔ Angle<input data-setting="modeSwitch" type="checkbox" data-write></label><label>Matched PPM fallback<input data-setting="handover" type="checkbox" data-write></label></div><p class="kc-note">Battery values require a correctly wired and rated monitor. Critical voltage blocks a new ARM; during flight it alerts the pilot. PPM handover requires a fresh standby receiver, CH5 high, throttle within 100 µs and other axes within 150 µs.</p><div class="kc-actions"><button data-kc="read">Read current settings</button><button data-kc="saveSettings" data-write>Save controller settings</button></div></section>
<section class="kc-page" data-kc-page="2" hidden><h3>Rate / Angle PID</h3><table class="kc-pid"><thead><tr><th>Loop</th><th>P</th><th>I</th><th>D</th></tr></thead><tbody>${axes.map(k=>`<tr><td>${k}</td>${['P','I','D'].map(v=>`<td><input type="number" min="0" step=".001" data-pid="${k}${v}" data-write></td>`).join('')}</tr>`).join('')}</tbody></table><div class="kc-actions"><button data-kc="readPid">Read PID</button><button data-kc="savePid" data-write>Save PID to kit</button></div></section>
<section class="kc-page" data-kc-page="3" hidden><h3>Level calibration</h3><div class="kc-grid">${['accelOffsetX','accelOffsetY','accelOffsetZ','levelTrimRoll','levelTrimPitch'].map(k=>`<label>${k}<input data-cal="${k}" type="number" step=".001" data-write></label>`).join('')}</div><div class="kc-actions"><button data-kc="readCal">Read calibration</button><button data-kc="saveCal" data-write>Save offsets / trim</button><button data-kc="captureLevel" data-write>Capture level</button><button data-kc="gyro" data-write>Calibrate gyro</button></div><h3>Six-face accelerometer calibration</h3><p class="kc-note">Remove propellers. For each capture, point the indicated sensor axis upward (+) or downward (−), and hold still. These are sensor axes before the mounting rotation.</p><div class="kc-actions">${['X+','X−','Y+','Y−','Z+','Z−'].map((v,i)=>`<button data-face="${i}" data-write>Capture ${v}</button>`).join('')}<button data-kc="sixSave" data-write>Save all six faces</button><button data-kc="sixReset" data-write>Restart captures</button></div><p data-kc="sixStatus" class="kc-note">No captures read yet.</p><h3>Backup / restore this kit</h3><div class="kc-actions"><button data-kc="backup">Download settings backup</button><button data-kc="restore" data-write>Restore backup</button><input data-kc="restoreFile" type="file" accept="application/json,.json" hidden></div></section>
<section class="kc-page" data-kc-page="4" hidden><h3>Live diagnostics</h3><div class="kc-stats" data-kc="stats"></div><p data-kc="sensors" class="kc-note">Waiting for sensor status…</p><label>Graph axis<select data-kc="axis"><option value="0">Roll</option><option value="1">Pitch</option><option value="2">Yaw rate</option></select></label><p class="kc-note">Target: cyan · measured: amber. Graphs use received telemetry samples.</p><canvas data-graph="angle" width="850" height="150"></canvas><canvas data-graph="rate" width="850" height="150"></canvas><canvas data-graph="motors" width="850" height="150"></canvas><div class="kc-actions"><button data-kc="record">Pause log</button><button data-kc="csv">Download flight CSV</button><button data-kc="clear">Clear log</button></div></section><section class="kc-page" data-kc-page="5" hidden><div data-kc="fcSetup"></div></section>`;
  const $=name=>root.querySelector(`[data-kc="${name}"]`),all=sel=>[...root.querySelectorAll(sel)];let busy=false,snapshot=null,identity='',samples=[],recording=true,lastTelemetry=null,activeTab=0;
  const setup=wizard?AerionFcSetup.mount($('fcSetup'),adapter,{advanced:()=>root.querySelector('[data-kc-tab="2"]').click()}):{update(){}};$('setupWizard').onclick=()=>root.querySelector('[data-kc-tab="5"]').click();
  const message=v=>{$('message').textContent=v};
  function update(){setup.update();const k=adapter.kit(),owned=adapter.owned(),blocked=busy||!k||!owned||!!k.armed||Number(k.benchMode||0)!==0;all('[data-write]').forEach(el=>el.disabled=blocked);$('handover').disabled=busy||!k||!owned||!k.capabilities?.inflightHandover;$('saveFeel').disabled=!!k?.armed||busy;if(k?.deviceId&&identity&&identity!==k.deviceId){samples=[];snapshot=null;identity=k.deviceId}const role=k?.controlRole==='MOBILE'&&!owned?'MOBILE CONTROL · VIEW ONLY':owned?'YOU CONTROL':'VIEW ONLY';root.dataset.ownership=role;if(!busy&&k)$('message').textContent=`${k.name||k.deviceName||'Kit'} · ${k.deviceId} · ${role} · ${k.armed?'ARMED':'DISARMED'}`;}
  function action(name,fn){$(name).onclick=async()=>{if(busy)return;busy=true;update();try{await fn()}catch(e){message(e.message||String(e))}finally{busy=false;all('[data-write]').forEach(el=>el.disabled=!adapter.owned()||!!adapter.kit()?.armed||Number(adapter.kit()?.benchMode||0)!==0)}}}
  const cmd=(type,fields={})=>adapter.command({type,...fields});
  const write=async(type,fields={})=>{const kit=adapter.kit();if(!kit||kit.armed||Number(kit.benchMode||0)!==0)throw Error('Disarm and stop motor tests before configuration.');if(!adapter.owned())await adapter.ensureControl();if(!adapter.owned())throw Error('This kit is view-only.');return cmd(type,fields)};
  function populate(d){snapshot=d;identity=d.deviceId;const f=d.flightSettings||{};all('[data-setting]').forEach(x=>x.type==='checkbox'?x.checked=!!f[x.dataset.setting]:x.value=String(f[x.dataset.setting]??''));for(const k of axes)for(const a of ['P','I','D'])root.querySelector(`[data-pid="${k}${a}"]`).value=d.pid?.[k]?.[a]??'';const c=d.calibration||{};for(const key of ['X','Y','Z'])root.querySelector(`[data-cal="accelOffset${key}"]`).value=c.accelOffset?.[key.toLowerCase()]??0;root.querySelector('[data-cal="levelTrimRoll"]').value=c.levelTrim?.roll??0;root.querySelector('[data-cal="levelTrimPitch"]').value=c.levelTrim?.pitch??0;$('sixStatus').textContent=`Captured: ${['X+','X−','Y+','Y−','Z+','Z−'].filter((_,i)=>d.sixFaceMask&(1<<i)).join(', ')||'none'} · saved six-face calibration: ${d.sixFaceValid?'yes':'no'}`;}
  async function read(){if(!adapter.kit())throw Error('Connect and verify your kit first.');const d=await cmd('snapshot_get');populate(d);message(`Read ${d.deviceId} · firmware ${d.firmware} · ${d.boardId}`);return d}
  async function saved(){const r=await adapter.request('/api/wifi/saved');$('savedSsid').replaceChildren(...(r.profiles||[]).map(x=>new Option(x.ssid+(x.preferred?' · preferred':''),x.ssid)));message((r.profiles||[]).length?'Choose a saved STA network.':'No saved Wi-Fi. Enter a new SSID and router password.');}
  action('handover',async()=>{const k=adapter.kit();if(!adapter.owned()||!k?.capabilities?.inflightHandover)throw Error('Control ownership and handover capability required.');const source=$('rcSource').value;if(adapter.handover)await adapter.handover(source);else await cmd('rc_source_set',{source});message('RC preference accepted. Verify the actual RC source in diagnostics.');});
  action('read',read);action('readPid',read);action('readCal',read);action('saved',saved);
  action('scan',async()=>{let r=await adapter.request('/api/wifi/scan');for(let i=0;r.scanning&&i<40;i++){await new Promise(resolve=>setTimeout(resolve,250));r=await adapter.request('/api/wifi/scan')}if(r.scanning)throw Error('Wi-Fi scan is still running. Try again.');$('nearby').replaceChildren(...(r.networks||[]).map(x=>new Option(`${x.ssid} · ${x.rssi} dBm`,x.ssid)));message('Choose a nearby Wi-Fi network.');});$('nearby').onchange=()=>{$('ssid').value=$('nearby').value};
  action('switchAp',async()=>{await write('network_mode_set',{mode:'AP'});message('Kit restarting in AP. Join its unique Wi-Fi; password 12345678.');adapter.networkChanged('AP');});
  action('useSaved',async()=>{if(!$('savedSsid').value)throw Error('Read and choose a saved Wi-Fi network first.');await writeCheck();await adapter.request('/api/wifi/use',{ssid:$('savedSsid').value});message('Kit restarting in STA. Join the same router Wi-Fi and reconnect its Device ID.');adapter.networkChanged('STA');});
  async function writeCheck(){const k=adapter.kit();if(!k||k.armed||Number(k.benchMode||0)!==0)throw Error('Disarm before changing Wi-Fi.');if(!adapter.owned())await adapter.ensureControl();if(!adapter.owned())throw Error('VIEW ONLY.');}
  action('saveWifi',async()=>{await writeCheck();const ssid=$('ssid').value.trim(),password=$('password').value;if(!ssid)throw Error('Enter a Wi-Fi SSID.');if(String(adapter.kit().mode).includes('AP')){await adapter.request('/api/setup/test',{ssid,password,name:adapter.kit().name||''});$('password').value='';for(let i=0;i<70;i++){await new Promise(r=>setTimeout(r,250));const d=await adapter.request('/api/setup/test/status');if(d.status==='failed')throw Error(d.message||'Wi-Fi test failed; AP retained.');if(d.status==='success'){message('Wi-Fi verified and saved. Join '+ssid+' after restart, then reconnect.');adapter.networkChanged('STA');return}}throw Error('Wi-Fi test still pending. Reconnect to check status.');}else{await adapter.request('/api/wifi/set',{ssid,password});$('password').value='';message('Wi-Fi saved; kit restarting. Unreachable Wi-Fi returns to AP.');adapter.networkChanged('STA')}});
  action('saveSettings',async()=>{const f=Object.fromEntries(all('[data-setting]').map(x=>[x.dataset.setting,x.type==='checkbox'?Number(x.checked):Number(x.value)]));await write('flight_settings_set',{schema:1,boardId:adapter.kit().boardId,...f});await read();message('Controller settings saved and read back.');});
  const pidValues=()=>Object.fromEntries(all('[data-pid]').map(x=>[x.dataset.pid,Number(x.value)]));const calValues=()=>Object.fromEntries(all('[data-cal]').map(x=>[x.dataset.cal,Number(x.value)]));
  action('savePid',async()=>{await write('pid_set',pidValues());await read();message('PID saved and read back.');});action('saveCal',async()=>{await write('calibration_set',calValues());await read();message('Calibration saved and read back.');});action('captureLevel',async()=>{await write('level_calibrate',{samples:100});await read();});action('gyro',async()=>{await write('calibrate_gyro');await read();});
  all('[data-face]').forEach(b=>b.onclick=async()=>{if(busy)return;busy=true;update();try{await write('sixface_capture',{face:b.dataset.face});await read()}catch(e){message(e.message)}finally{busy=false;update()}});action('sixSave',async()=>{if(!await confirmInLab('Place the controller level and stationary before saving all six faces. Continue?'))return;await write('sixface_commit');await read()});action('sixReset',async()=>{await write('sixface_reset');await read()});
  action('backup',async()=>{const d=await read();download(`Aerion_${d.deviceId}_settings.json`,JSON.stringify({backupSchema:1,exportedAt:new Date().toISOString(),...d},null,2))});action('restore',async()=>{$('restoreFile').click()});$('restoreFile').onchange=async()=>{const file=$('restoreFile').files[0];if(!file)return;try{await adapter.ensureConnection?.();if(file.size>32768)throw Error('Backup file is too large.');const d=JSON.parse(await file.text()),k=adapter.kit();if(d.backupSchema!==1||d.flightSettings?.schema!==1||d.deviceId!==k?.deviceId||d.boardId!==k?.boardId)throw Error('Backup must match this Device ID, controller profile and settings schema.');if(!await confirmInLab('Restore saved PID, calibration and controller settings to this disarmed kit?'))return;const f={...d.flightSettings,boardId:d.boardId,backupSchema:1};for(const a of axes)for(const v of ['P','I','D'])f[a+v]=d.pid?.[a]?.[v];Object.assign(f,{accelOffsetX:d.calibration?.accelOffset?.x,accelOffsetY:d.calibration?.accelOffset?.y,accelOffsetZ:d.calibration?.accelOffset?.z,levelTrimRoll:d.calibration?.levelTrim?.roll,levelTrimPitch:d.calibration?.levelTrim?.pitch,scaleX:d.accelScale?.[0],scaleY:d.accelScale?.[1],scaleZ:d.accelScale?.[2],sixFaceValid:d.sixFaceValid?1:0});if(Object.entries(f).some(([key,value])=>value===undefined||typeof value==='number'&&!Number.isFinite(value)))throw Error('Backup is incomplete or contains invalid numbers.');await write('settings_restore',f);await read();message('Backup restored and read back.');}catch(e){message(e.message)}finally{$('restoreFile').value=''}};
  all('[data-kc-tab]').forEach(b=>b.onclick=()=>{activeTab=Number(b.dataset.kcTab);if(activeTab!==5)setup.stop('Setup stopped because another settings tab was opened.');all('[data-kc-tab]').forEach(x=>x.classList.toggle('active',x===b));all('[data-kc-page]').forEach(x=>x.hidden=Number(x.dataset.kcPage)!==activeTab);if(activeTab!==4&&activeTab!==5&&!snapshot&&adapter.kit())read().catch(e=>message(e.message));update();if(activeTab===4)draw()});
  function feel(){const p=window.AerionSticks.settings();for(const k of Object.keys(p)){const el=$(k);if(el)el.type==='checkbox'?el.checked=!!p[k]:el.value=p[k]}}feel();action('saveFeel',async()=>{if(adapter.kit()?.armed)throw Error('Disarm before changing joystick settings.');const v={};for(const k of Object.keys(window.AerionSticks.defaults))v[k]=$(k).type==='checkbox'?$(k).checked:Number($(k).value);window.AerionSticks.save(v);message('Joystick feel saved for this device.');});
  function telemetry(t){const k=adapter.kit();if(!k||t.deviceId&&t.deviceId!==k.deviceId)return;update();lastTelemetry=t;if(identity&&identity!==k.deviceId)samples=[];identity=k.deviceId;if(recording){samples.push({...t,deviceId:k.deviceId,receivedAt:Date.now()});if(samples.length>3000)samples.shift()}
   const stats=[['Flight mode',t.flightMode||'--'],['Control',t.controlRole||'--'],['Loop',`${t.flightLoopHz??'--'} Hz`],['Period',`${t.loopPeriodUs??'--'} µs`],['Longest gap',`${t.maxLoopGapUs??'--'} µs`],['Overruns',t.loopOverruns??'--'],['RC input',`${t.webRcFrameHz??'--'} web / ${t.ppmFrameHz??'--'} PPM Hz`],['RC age',`${t.rcAgeMs??'--'} ms`],['Request delay',`${t.requestLatencyMs??'--'} ms`],['Battery',t.batteryValid?`${Number(t.battery).toFixed(2)} V${t.batteryCritical?' · CRITICAL':t.batteryLow?' · LOW':''}`:'Not available'],['Last disarm',t.lastDisarmReason||'--'],['Last event',t.lastEvent||'--']];$('stats').innerHTML=stats.map(([a,b])=>`<span>${a}<b>${esc(b)}</b></span>`).join('');$('sensors').textContent=Object.entries(t.sensors||{}).map(([name,v])=>`${name}: ${v.model||''} ${v.detected||v.configured||v.addressPresent?'present/configured':'not verified'}, ${v.fresh?'fresh':'no fresh data'}, ${v.usedInFlight?'used in flight':'not used in flight'}${name==='imu'?`, gyro ${v.gyroCalibrated?'calibrated':'not calibrated'}, six-face ${v.sixFaceCalibrated?'saved':'not saved'}`:''}`).join(' · ');if(activeTab===4)draw();}
  function graph(name,series){const c=root.querySelector(`[data-graph="${name}"]`),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const recent=samples.slice(-180);const values=series.flatMap(s=>recent.map(s.read)).filter(Number.isFinite);let min=Math.min(...values,0),max=Math.max(...values,1);if(name==='motors'){min=950;max=2050}if(max-min<10){min-=5;max+=5}ctx.strokeStyle='#203549';for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(0,i*h/4);ctx.lineTo(w,i*h/4);ctx.stroke()}ctx.font='11px system-ui';ctx.fillStyle='#afc9d9';ctx.fillText(`${name.toUpperCase()} · ${Math.round(min)} … ${Math.round(max)}`,10,15);series.forEach(s=>{ctx.strokeStyle=s.color;ctx.lineWidth=2;ctx.beginPath();let on=false;recent.forEach((t,i)=>{const v=s.read(t);if(!Number.isFinite(v)){on=false;return}const x=8+i*(w-16)/Math.max(1,recent.length-1),y=h-8-(v-min)/(max-min)*(h-30);if(on)ctx.lineTo(x,y);else ctx.moveTo(x,y);on=true});ctx.stroke()})}
  function draw(){const axis=Number($('axis').value),measured=['roll','pitch','yaw'][axis],gyro=['gyroX','gyroY','gyroZ'][axis];graph('angle',axis===2?[]:[{color:'#12c7ff',read:t=>t.targetAngle?.[axis]},{color:'#ffbe65',read:t=>t[measured]}]);graph('rate',[{color:'#12c7ff',read:t=>t.targetRate?.[axis]},{color:'#ffbe65',read:t=>t[gyro]}]);graph('motors',['#12c7ff','#ffbe65','#bd8bff','#6bf1ad'].map((color,i)=>({color,read:t=>t.motors?.[i]})))}$('axis').onchange=draw;
  action('record',async()=>{recording=!recording;$('record').textContent=recording?'Pause log':'Resume log'});action('clear',async()=>{samples=[];draw();message('Flight log cleared.');});action('csv',async()=>{if(!samples.length)throw Error('No received telemetry to export.');const columns=['receivedAt','deviceId','flightMode','rcSource','roll','pitch','yaw','gyroX','gyroY','gyroZ','battery','flightLoopHz','loopPeriodUs','maxLoopGapUs','loopOverruns','rcAgeMs','lastDisarmReason','lastEvent'];const extra=['targetAngle0','targetAngle1','targetRate0','targetRate1','targetRate2',...Array.from({length:4},(_,i)=>'motor'+(i+1)),...Array.from({length:10},(_,i)=>'CH'+(i+1))];const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const lines=[columns.concat(extra).join(',')];for(const t of samples)lines.push([...columns.map(k=>t[k]),...Array.from({length:2},(_,i)=>t.targetAngle?.[i]),...Array.from({length:3},(_,i)=>t.targetRate?.[i]),...Array.from({length:4},(_,i)=>t.motors?.[i]),...Array.from({length:10},(_,i)=>t.rc?.[i])].map(cell).join(','));download(`Aerion_${identity}_flight.csv`,lines.join('\n'),'text/csv')});
  if(!wizard)root.querySelector('[data-kc-tab="5"]').hidden=true;update();return {refresh:read,update,telemetry,show:name=>{const i=['Wi-Fi','Controls','PID','Calibration','Diagnostics','FC Setup'].indexOf(name);root.querySelector(`[data-kc-tab="${i}"]`)?.click()},get samples(){return samples}};
 }
 window.AerionConsole={mount};
})();
