/* Gauges show only received measurements. Missing altitude/velocity stay unavailable. */
(()=>{'use strict';const $=s=>document.querySelector(s);let packet=null,received=0,id='',flightMs=0,lastAt=0,lastArmed=false;
 const attitudeAvailable=(t,live)=>live&&t.flightReady===true&&t.flightCoreIntegrated!==false&&t.sensors?.imu?.fresh!==false&&t.imuHealth!=='NOT_FOUND'&&t.imuHealth!=='STALE';
 const fmt=(v,d=1)=>Number.isFinite(v)?v.toFixed(d):'—',number=v=>typeof v==='number'&&Number.isFinite(v)?v:null;
 function base(c){const x=c.getContext('2d');x.clearRect(0,0,320,320);x.save();x.translate(160,160);x.fillStyle='#0b1117';x.beginPath();x.arc(0,0,151,0,Math.PI*2);x.fill();x.strokeStyle='#5b6d7c';x.lineWidth=5;x.stroke();return x;}
 function ticks(x,max=360){x.strokeStyle='#c4d7e1';for(let i=0;i<max;i+=max/60){const a=i/max*Math.PI*2;const r=i%(max/12)<.001?126:134;x.lineWidth=r===126?2:1;x.beginPath();x.moveTo(Math.sin(a)*r,-Math.cos(a)*r);x.lineTo(Math.sin(a)*141,-Math.cos(a)*141);x.stroke();}}
 function unavailable(x,label){x.fillStyle='#718492';x.font='13px system-ui';x.textAlign='center';x.fillText('—',0,-5);x.font='11px system-ui';x.fillText(label,0,20);}
 function attitude(t,live){const x=base($('#attitudeGauge'));x.save();x.beginPath();x.arc(0,0,135,0,Math.PI*2);x.clip();if(live&&number(t.roll)!==null&&number(t.pitch)!==null){x.save();x.rotate(-t.roll*Math.PI/180);const pitch=Math.max(-90,Math.min(90,t.pitch))*2;x.fillStyle='#327cb5';x.fillRect(-310,-500+pitch,620,500);x.fillStyle='#815d35';x.fillRect(-310,pitch,620,500);x.strokeStyle='#e7f3f5';x.lineWidth=2;x.beginPath();x.moveTo(-300,pitch);x.lineTo(300,pitch);x.stroke();x.font='12px system-ui';x.fillStyle='#fff';x.textAlign='center';for(let d=-60;d<=60;d+=10){if(!d)continue;const y=pitch-d*2,w=d%20===0?48:25;x.beginPath();x.moveTo(-w,y);x.lineTo(w,y);x.stroke();if(d%20===0){x.fillText(String(Math.abs(d)),-w-20,y+4);x.fillText(String(Math.abs(d)),w+20,y+4)}}x.restore();}else{x.fillStyle='#263744';x.fillRect(-160,-160,320,320);unavailable(x,live?'NO ATTITUDE':'NO LIVE DATA')}x.restore();ticks(x);x.strokeStyle='#ffc970';x.lineWidth=5;x.beginPath();x.moveTo(-73,0);x.lineTo(-24,0);x.lineTo(-16,8);x.moveTo(73,0);x.lineTo(24,0);x.lineTo(16,8);x.stroke();x.fillStyle='#ffc970';x.beginPath();x.arc(0,0,4,0,7);x.fill();x.restore();}
 function heading(t,live){const x=base($('#headingGauge'));ticks(x);if(live&&number(t.yaw)!==null){x.save();x.rotate(-t.yaw*Math.PI/180);for(let i=0;i<360;i+=30){const a=i*Math.PI/180;x.save();x.translate(Math.sin(a)*112,-Math.cos(a)*112);x.rotate(a);x.fillStyle=i%90?'#c3d2db':'#ffcf72';x.font=i%90?'15px system-ui':'22px system-ui';x.textAlign='center';x.fillText(({0:'N',90:'E',180:'S',270:'W'})[i]||String(i/10),0,5);x.restore()}x.restore();x.strokeStyle='#ffc76a';x.lineWidth=3;x.beginPath();x.moveTo(0,-74);x.lineTo(-8,-12);x.lineTo(-65,14);x.lineTo(-65,25);x.lineTo(-8,8);x.lineTo(-8,62);x.lineTo(-30,77);x.lineTo(-30,83);x.lineTo(0,72);x.lineTo(30,83);x.lineTo(30,77);x.lineTo(8,62);x.lineTo(8,8);x.lineTo(65,25);x.lineTo(65,14);x.lineTo(8,-12);x.closePath();x.stroke();}else unavailable(x,'NO LIVE YAW');x.restore();}
 function dial(selector,value,label,min,max){const x=base($(selector));for(let i=0;i<=10;i++){const angle=(-135+i*27)*Math.PI/180;x.strokeStyle='#c0d3de';x.lineWidth=2;x.beginPath();x.moveTo(Math.sin(angle)*123,-Math.cos(angle)*123);x.lineTo(Math.sin(angle)*140,-Math.cos(angle)*140);x.stroke();x.fillStyle='#a9c4d5';x.textAlign='center';x.font='12px system-ui';x.fillText(fmt(min+(max-min)*i/10,0),Math.sin(angle)*105,-Math.cos(angle)*105+4)}if(value!==null){const a=(-135+Math.max(0,Math.min(1,(value-min)/(max-min)))*270)*Math.PI/180;x.strokeStyle='#f4ce87';x.lineWidth=5;x.beginPath();x.moveTo(-Math.sin(a)*12,Math.cos(a)*12);x.lineTo(Math.sin(a)*108,-Math.cos(a)*108);x.stroke();x.fillStyle='#d3e9f0';x.font='20px system-ui';x.textAlign='center';x.fillText(fmt(value)+' '+label,0,72)}else unavailable(x,'SENSOR UNAVAILABLE');x.fillStyle='#566976';x.beginPath();x.arc(0,0,9,0,7);x.fill();x.restore();}
 function setupChecks(d,t,live){const summary=$('#cockpitSetupSummary'),list=$('#cockpitSetupChecks');if(!summary||!list)return;const record=window.AerionFcSetup?.getReport(d?.deviceId),rows=[];
  if(!d?.deviceId){summary.textContent='Connect a kit to review its setup checks.';list.replaceChildren();return;}
  if(record?.deviceId===d.deviceId){for(const check of record.steps)rows.push({name:check.name,state:check.state,message:check.message||({done:'Verified in setup',skipped:'Skipped — complete this check before flight',pending:'Pending — not yet verified',error:'Setup / calibration failed'})[check.state]});if(record.firmware&&d.firmware&&record.firmware!==d.firmware)rows.push({name:'Firmware changed',state:'pending',message:'Review setup checks for the current controller firmware.'});}
  else rows.push({name:'Setup record',state:'pending',message:'Setup and calibration have not been verified for this kit in this browser.'});
  if(live&&t.flightCoreIntegrated===true&&t.flightReady!==true)rows.push({name:'IMU / flight controller',state:'error',message:'FlightCore is not ready. Check the IMU model, wiring and calibration.'});
  if(live&&(t.imuHealth==='NOT_FOUND'||t.imuHealth==='STALE'||t.sensors?.imu?.fresh===false))rows.push({name:'IMU data',state:'error',message:'No fresh IMU measurements received.'});
  if(live&&t.outputWatchdogTripped)rows.push({name:'Motor output watchdog',state:'error',message:'Motor outputs stopped after a loop timing fault.'});
  const pending=rows.filter(row=>row.state!=='done');summary.textContent=pending.length?pending.length+' pending / failed setup checks · '+d.deviceId:'Setup checks verified · '+d.deviceId;summary.className=pending.length?'bad':'good';
  list.replaceChildren(...rows.map(row=>{const li=document.createElement('li');li.className=row.state==='done'?'good':'bad';li.dataset.setupCheck=row.name;const title=document.createElement('b');title.textContent=row.name+' · '+row.state.toUpperCase();const detail=document.createElement('small');detail.textContent=row.message;li.append(title,detail);return li;}));
 }
 function draw(){if(!$('#attitudeGauge'))return;const s=window.zebjusSchool,d=s?.getSelectedDevice?.(),live=!!packet&&s?.isSelectedConnected()&&packet.deviceId===d?.deviceId&&Date.now()-received<2200,t=packet||{};setupChecks(d,t,live);const attitudeLive=attitudeAvailable(t,live);const link=$('#cockpitLink');link.textContent=live?'LIVE · '+(t.rcSource||'NONE'):received?'LINK STALE':'NO LINK';link.className='status '+(live?'good':'bad');$('#gaugeAttitude').textContent=attitudeLive?fmt(t.roll)+'° / '+fmt(t.pitch)+'°':live?'SENSOR NOT AVAILABLE':'WAITING';$('#gaugeHeading').textContent=attitudeLive&&number(t.yaw)!==null?fmt((t.yaw%360+360)%360)+'° · gyro estimate':'—';const alt=live&&t.altitudeValid===true?number(t.altitude):null,vsi=live&&t.verticalSpeedValid===true?number(t.verticalSpeed):null;$('#gaugeAltitude').textContent=alt===null?'SENSOR NOT AVAILABLE':fmt(alt)+' m';$('#gaugeVsi').textContent=vsi===null?'SENSOR NOT AVAILABLE':fmt(vsi)+' m/s';for(const [name,key] of [['telRoll','roll'],['telPitch','pitch'],['telYaw','yaw'],['telBatt','battery']])$('#'+name).textContent=(key==='battery'?live&&t.batteryValid:attitudeLive)&&number(t[key])!==null?fmt(t[key],2)+(key==='battery'?' V':'°'):'—';attitude(t,attitudeLive);heading(t,attitudeLive);dial('#altitudeGauge',alt,'m',0,20);dial('#vsiGauge',vsi,'m/s',-5,5);
  const health=[['ATTITUDE',attitudeLive&&number(t.roll)!==null],['STABILISATION',live&&t.flightReady],['INPUT',live&&number(t.rcAgeMs)!==null&&t.rcAgeMs<900],['OUTPUT',live&&Array.isArray(t.motors)],['TELEMETRY',live],['BATTERY',live&&t.batteryValid],['GPS',live&&t.sensors?.gps?.fresh],['BAROMETER',live&&t.sensors?.barometer?.fresh],['CPU LOOP',live&&t.flightLoopHz>200&&!t.outputWatchdogTripped],['CONFIG',live&&!!t.flightSettings],['ARM',live&&t.armed],['TRAINING',live&&t.trainingActive]];$('#cockpitHealth').replaceChildren(...health.map(([title,ok])=>{const e=document.createElement('span');e.textContent=title;e.className=ok?'good':live?'bad':'';return e}));const facts=[['Device ID',live?t.deviceId:'—'],['Flight time observed',Math.floor(flightMs/1000)+' s'],['Flight mode',live?t.flightMode:'—'],['RC source',live?t.rcSource:'—'],['State',live?t.trainingActive?'TRAINING · OUTPUTS BLOCKED':t.armed?'ARMED':'DISARMED':'—'],['FC loop',live?fmt(t.flightLoopHz,0)+' Hz':'—'],['RC age',live?fmt(t.rcAgeMs,0)+' ms':'—'],['Link latency',live?fmt(t.requestLatencyMs,0)+' ms':'—'],['Motor outputs',live&&Array.isArray(t.motors)?t.motors.join(' / ')+' µs':'—'],['Last event',live?t.lastEvent||t.lastDisarmReason||'—':'—']];$('#cockpitFacts').replaceChildren(...facts.map(([title,value])=>{const e=document.createElement('span');e.append(title);const b=document.createElement('b');b.textContent=value??'—';e.append(b);return e}));}
 function sensorStatus(){const s=window.zebjusSchool,d=s?.getSelectedDevice?.(),t=packet||{},live=!!packet&&s?.isSelectedConnected()&&t.deviceId===d?.deviceId&&Date.now()-received<2200,gyroLive=live&&(t.sensors?.imu?.fresh===true||t.imuHealth==='OK')&&(t.flightCoreIntegrated!==true||t.flightReady===true);for(const axis of ['X','Y','Z']){const node=$('#gyro'+axis);if(node)node.textContent=gyroLive&&number(t['gyro'+axis])!==null?fmt(t['gyro'+axis],3):'—';}const level=$('#levelState');if(level)level.textContent=attitudeAvailable(t,live)&&number(t.roll)!==null&&number(t.pitch)!==null?Math.abs(t.roll)<2&&Math.abs(t.pitch)<2?'LEVEL':'TILTED':'Waiting';}
 window.addEventListener('aerion-telemetry',e=>{const t=e.detail,now=Date.now();if(t.deviceId!==id){id=t.deviceId;flightMs=0;lastAt=0;lastArmed=false}if(lastArmed&&t.armed&&lastAt&&now-lastAt<2200)flightMs+=now-lastAt;packet=t;received=lastAt=now;lastArmed=!!t.armed;});setInterval(()=>{if($('#tab-telemetry')?.classList.contains('active'))draw();if($('#tab-io')?.classList.contains('active')&&!$('#calibrationTools')?.hidden)sensorStatus()},160);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',draw);else draw();
})();
