'use strict';
// Executes the bundled Android UI and JS bridge in a real browser.
// Native Android API calls and controller radio are simulated here.
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),assets=path.join(root,'app/src/main/assets'),ID='ZFC-001122334455';
let server,browser,reachable=false,owner='',armed=false,wifiOpened=0,wifiJoins=[],routerSelections=[],wrong=false,slow=0;
const frames=[],requests=[],cancelled=[],browserRequests=[],errors=[];
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(page,f){await page.waitForFunction(f,null,{timeout:10000})}
(async()=>{
 server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),rel=u.pathname.replace(/^\/assets\//,'');if(!['flight/index.html','android-transport.js','aerion-drone-mark.png'].includes(rel)){res.writeHead(404).end();return}res.writeHead(200,{'Content-Type':rel.endsWith('.png')?'image/png':rel.endsWith('.js')?'text/javascript':'text/html','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'none'; frame-src 'none'; object-src 'none'"});res.end(fs.readFileSync(path.join(assets,rel)))});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://localhost:${server.address().port}/assets/flight/index.html`;
 browser=await chromium.launch({headless:true,executablePath:process.env.ZEBJUS_CHROMIUM});const context=await browser.newContext({viewport:{width:1000,height:560},hasTouch:true});
 await require('../../tools/browser_pairing_double').install(context);await context.addInitScript(()=>{localStorage.setItem('zebjus-flight-destination',JSON.stringify('REAL'));window.__aerionToken='test-token';window.NativeAerion={request(key,id,address,method,form,timeout){window.__request(id,address,method,form,timeout).then(r=>window.AerionAndroid.deliver(id,r.code,r.body))},cancel(key,id){window.__cancel(id)},openWifi(){window.__wifi()},joinWifi(key,id){window.__join(id)},useRouterWifi(key,ssid,fromAp){window.__router(ssid,fromAp)}}});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>browserRequests.push(r.url()));
 await page.exposeFunction('__router',(ssid,fromAp)=>routerSelections.push({ssid,fromAp}));await page.exposeFunction('__wifi',()=>{wifiOpened++});await page.exposeFunction('__join',id=>wifiJoins.push(id));await page.exposeFunction('__cancel',id=>cancelled.push(id));
 const nativeRequest=async(id,address,method,form,timeout)=>{
  requests.push({id,address,method,form,timeout});if(!reachable)return{code:0,body:'Join the kit Wi-Fi.'};const u=new URL(address),d=Object.fromEntries(new URLSearchParams(form));let code=200,body={ok:true};
  if(d.expectedDeviceId&&d.expectedDeviceId!==(wrong?'ZFC-FFEEDDCCBBAA':ID))return{code:409,body:JSON.stringify({ok:false,message:'Wrong Device ID'})};
  if(u.pathname==='/api/status')body={ok:true,kit:'ZEBJUS_FLIGHTCORE',deviceId:wrong?'ZFC-FFEEDDCCBBAA':ID,name:'zebjus_drone_1',ip:'192.168.4.1',mode:'AP SETUP',securityRequired:true,controlRole:owner?'MOBILE':'',flightReady:true,flightMode:'ANGLE',armed,locked:!!owner,lockMine:owner===u.searchParams.get('clientId')};
  else if(u.pathname==='/api/telemetry'){if(slow)await pause(slow);body={ok:true,roll:1,pitch:2,webRcFrameHz:25,flightLoopHz:250};}
  else if(u.pathname==='/api/control/acquire'){owner=d.clientId;body={ok:true,deviceId:ID,lockMine:true,controlRole:'MOBILE',rcTimeoutMs:1000,lockTimeoutMs:10000}}
  else if(u.pathname==='/api/control/release'){if(owner===d.clientId){owner='';armed=false}}
  else if(u.pathname==='/api/control/ping'){if(owner!==d.clientId){code=423;body={ok:false,message:'Lock lost'}}}
  else if(u.pathname==='/api/command'){
   if(slow)await pause(slow);if(owner!==d.clientId){code=423;body={ok:false,message:'Take control again'}}else if(d.type==='flight_stop'){armed=false;body={ok:true,command:'flight_stop',deviceId:ID};}else if(d.type==='rc_frame'){const c=d.channels.split(',').map(Number);frames.push(c);armed=c[4]>1500;body={ok:true,armed,outputsBlocked:false,deviceId:ID};}else{code=400;body={ok:false,message:'Unexpected command '+d.type};}
  }else{code=404;body={ok:false,message:'Unknown route'}}
  return {code,body:JSON.stringify(body)};
 };await page.exposeFunction('__request',nativeRequest);await page.exposeFunction('__api',(address,form)=>nativeRequest('publisher',address,'POST',form,0));
 await page.goto(url);await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.getElementById('startupLogo').naturalWidth>0);assert(await page.locator('#brandSplash').isVisible());await pause(2400);assert(await page.locator('#brandSplash').isVisible(),'brand intro remains visible before five seconds');await pause(800);await page.screenshot({path:path.resolve(root,'../../native_startup_mobile.png')});assert.equal(frames.length,0,'startup animation does not transmit RC');assert.equal(requests.length,0,'startup delays HTTP and pairing until the five-second reveal completes');await page.waitForFunction(()=>document.getElementById('brandSplash').hidden);assert(await page.evaluate(()=>performance.now()>=4900),'intro stays up for five seconds');await page.setViewportSize({width:1000,height:560});await wait(page,()=>!document.getElementById('heroAction').disabled);assert(await page.locator('#arm').isDisabled());assert.equal(await page.locator('#heroTitle').textContent(),'Connect your drone');assert.equal(await page.locator('#fullscreen').isVisible(),false);
 assert.equal(await page.locator('#trainingWebAppId').count(),0);await page.setViewportSize({width:390,height:844});await pause(1200);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.click('#heroAction');assert(await page.locator('#androidRouterWifi').isVisible());await page.screenshot({path:path.resolve(root,'../../native_connection_choices.png')});await page.setViewportSize({width:1000,height:560});assert((await page.locator('#androidAppVersion').textContent()).includes('18.3.82-android.1'));const beforeRouter=requests.length;await page.click('#androidRouterWifi');assert.deepEqual(routerSelections,[{ssid:'',fromAp:false}]);assert(await page.locator('#arm').isDisabled());assert.equal(frames.length,0,'offline router choice never transmits RC');assert(requests.slice(beforeRouter).every(r=>!r.address.includes('/api/control/acquire')),'router selection alone never acquires control');await page.fill('#kitName','zebjus_drone_1');await page.click('#androidWifi');assert.deepEqual(wifiJoins,['zebjus_drone_1']);await page.click('#androidWifiSettings');assert.equal(wifiOpened,1);assert((await page.locator('#connectDialog .connect-grid').textContent()).includes('kit label'));assert.equal(await page.locator('#settingsDialog .links').isVisible(),false);reachable=true;await page.fill('#kitName','zebjus_drone_1');await page.click('#checkConnection');await wait(page,()=>document.getElementById('controlHint').textContent==='MOBILE SESSION');assert(await page.locator('#arm').isDisabled());assert.equal(frames.length,0,'connection reserves ownership without flight frames');await page.click('#heroAction');await wait(page,()=>document.getElementById('controlToggle').getAttribute('aria-checked')==='true');assert.equal(await page.locator('#connectionLabel').textContent(),'zebjus_drone_1');
 await page.click('#arm');await pause(100);assert(armed);await page.keyboard.down('ArrowRight');await pause(100);assert(frames.at(-1)[0]>1500);await page.keyboard.up('ArrowRight');
 // Native lifecycle event, not just browser visibility: native callbacks force stopped output.
 await page.evaluate(()=>window.AerionAndroid.pause());await pause(220);assert.equal(armed,false);assert.equal(owner,'');assert(await page.locator('#arm').isDisabled());await page.evaluate(()=>window.AerionAndroid.resume());await pause(250);assert(await page.locator('#hero').isVisible());assert.equal(owner,'');
 await page.click('#heroAction');await wait(page,()=>document.getElementById('controlToggle').getAttribute('aria-checked')==='true');await page.evaluate(()=>window.AerionAndroid.stopped());await pause(200);assert.equal(owner,'');assert(await page.locator('#arm').isDisabled());
 await wait(page,()=>document.getElementById('controlToggle').getAttribute('aria-checked')==='true');assert.equal(armed,false,'native timeout recovery never restores ARM');slow=500;await page.evaluate(async()=>{const ctl=new AbortController();const pending=fetch('http://192.168.4.1/api/telemetry',{signal:ctl.signal}).catch(()=>{});setTimeout(()=>ctl.abort(),30);await pending;});assert(cancelled.length>0,'AbortSignal must cancel native request');await pause(600);assert.equal(await page.locator('#controlToggle').getAttribute('aria-checked'),'true','slow HTTP must not destroy native control');slow=0;assert.equal(armed,false);await page.click('#kill');await pause(150);
 const preJoin=requests.length;await page.evaluate(()=>{window.AerionAndroid.resume();window.AerionAndroid.wifiReady()});await pause(350);assert(requests.slice(preJoin).some(r=>r.address.includes('/api/control/acquire')&&r.form.includes('clientRole=MOBILE')),'back-to-back native resume/Wi-Fi join reserves a mobile session');assert(requests.slice(preJoin).every(r=>!r.form.includes('type=rc_frame')),'Wi-Fi join must not start RC frames');await page.evaluate(()=>window.AerionAndroid.joinRouter());assert.equal(routerSelections.at(-1).fromAp,true,'router selection fences the actual departing AP');await page.evaluate(()=>window.AerionAndroid.pause());await pause(150);await page.evaluate(()=>window.AerionAndroid.resume());await pause(150);assert(await page.locator('#arm').isDisabled());
 const preLink=requests.length;await page.evaluate(id=>window.AerionAndroid.openKit(id,'http://192.168.4.1'),ID);await pause(350);assert(requests.slice(preLink).every(r=>!r.address.includes('/api/control/acquire')),'app link is read-only');assert(await page.locator('#arm').isDisabled());
 await page.evaluate(()=>window.AerionAndroid.openKit('ZFC-FFEEDDCCBBAA','http://192.168.4.1'));await pause(150);assert.equal(await page.locator('#expectedId').inputValue(),ID,'app link cannot change an existing kit identity');
 const before=requests.length;await page.reload();await pause(300);assert(await page.locator('#arm').isDisabled());assert(requests.slice(before).every(r=>!r.address.includes('/api/control/acquire')),'reload must not acquire');assert.notEqual(requests[0].id,requests.at(-1).id,'document request IDs cannot collide after reload');
 await page.emulateMedia({reducedMotion:'reduce'});wrong=true;await page.reload();await pause(500);assert.equal(await page.locator('#heroTitle').textContent(),'Connect your drone');assert(await page.locator('#arm').isDisabled());assert.equal(await page.locator('#brandSplash').evaluate(e=>getComputedStyle(e).animationName),'none','reduced motion uses a static intro');assert.equal(await page.locator('#brandSplash').evaluate(e=>e.hidden),false);await page.waitForFunction(()=>document.getElementById('brandSplash').hidden);
 wrong=false;await page.click('#heroAction');await page.fill('#kitName','zebjus_drone_001122334455');await page.click('#androidWifi');assert.equal(wifiJoins.at(-1),'','old generated name uses the current kit AP picker instead of the removed SSID');await page.evaluate(()=>window.AerionAndroid.wifiReady());await wait(page,()=>document.getElementById('controlHint').textContent==='MOBILE SESSION');assert.equal(await page.locator('#kitName').inputValue(),'zebjus_drone_1');assert.equal(await page.locator('#expectedId').inputValue(),ID,'SSID migration retains exact paired kit identity');assert(await page.locator('#arm').isDisabled());
 assert.equal(errors.length,0,errors.join('\n'));assert(browserRequests.every(u=>u.startsWith('http://localhost:')),'native flight UI leaked browser HTTP requests');assert(!browserRequests.some(u=>/python|vendor|service-worker/.test(u)));assert(requests.some(r=>r.address.includes('/api/command')&&r.method==='POST'&&r.form.includes('expectedDeviceId='+ID)));assert(requests.some(r=>r.form.includes('type=flight_stop')),'physical STOP reaches the controller through native transport');
 console.log('PASS: actual bundled UI / Android transport adapter / native in-app Wi-Fi selection / read-only app links / explicit Wi-Fi mobile reservation without RC / form-encoded RC / lifecycle stop / read-only resume and reload / timeout cancellation / unique reply IDs / wrong-kit rejection / zero external runtimes');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)server.close()});
