'use strict';
// Actual native bundled UI + actual web Lab share one mock kit's ownership/RC.
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn,execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),ID='ZFC-001122334455',neutral=[1500,1500,1000,1500,1000,1000,1000,1000,1500,1000],sleep=ms=>new Promise(r=>setTimeout(r,ms));let server,browser,phone,lab,selectionDelay=0,reachable=false,denyObserverStatus=false,staleLabRc=false,statusDelay=0,statusHeld=false,realReady=false,rcDelay=0,telemetryDelay=0,udp2=true;const capturedExports=[];let nativeGate,gateDir,gateSequence=0,gateOutput='';const gateReplies=new Map();
function gate(op,key='',base='',id='',client='',channels=''){return new Promise((resolve,reject)=>{const n=String(++gateSequence);gateReplies.set(n,{resolve,reject});nativeGate.stdin.write([n,op,key,base,id,client,channels].join('\t')+'\n')})}
const monitorBoot=Date.now()-1000;
const fc={requestId:0,requestTarget:'',owner:'',role:'',active:false,target:'NONE',run:0,session:'',rc:[...neutral],last:0,armed:false,calls:[],cancelled:new Set(),pings:0,grants:0,udpToken:'',udpFrames:0};
function training(){return{ok:true,deviceId:ID,supported:true,selectionSupported:true,simulationRcTransport:'UDP',...(udp2?{simulationRcProtocol:'ZRC2'}:{}),active:fc.active,outputsBlocked:fc.active,target:fc.target,controller:'APP',input:'APP',runId:fc.run,leaseMs:5000,requesting:!!fc.requestTarget,requestId:fc.requestId,requestWebAppId:'123456',requestedTarget:fc.requestTarget||'NONE'};}
function status(cid=''){return{ok:true,kit:'ZEBJUS_FLIGHTCORE',deviceId:ID,name:'zebjus_drone_1',boardId:realReady?'ZFC-A2':'ZFC-A1',boardName:realReady?'Aerion F1':'ESP32-C3',firmware:'18.3.78',securityRequired:true,outputsBlocked:fc.active,mode:'STA',ip:'192.168.4.1',armed:fc.armed,benchMode:0,locked:!!fc.owner,lockMine:!!cid&&cid===fc.owner,controlRole:fc.role,webRc:realReady,flightCoreIntegrated:realReady,flightReady:realReady,simulationReady:true,simulationRcTransport:'UDP',rcMonitorProtocol:'ZFC3_NDJSON',rcMonitorPort:4211,rcTimeoutMs:1000,trainingSelection:true,trainingActive:fc.active,trainingTarget:fc.target,trainingController:'APP',trainingRunId:fc.run,trainingInput:'APP',rcSource:fc.last?'WEB_AP':'NONE',rcAgeMs:fc.last?Date.now()-fc.last:999999,rc:fc.rc,expansion:{ppmArmMode:'CH5_SWITCH'},sensors:{imu:{fresh:true,usedInFlight:true}}};}
function finish(){fc.active=false;fc.target='NONE';fc.run++;fc.armed=false;fc.udpToken='';fc.last=0;fc.rc=[...neutral];}
async function api(key,address,method,form=''){
 if(!reachable)return{code:0,body:'Join kit Wi-Fi'};const u=new URL(address),f=Object.fromEntries(new URLSearchParams(form)),cid=f.clientId||u.searchParams.get('clientId')||'';fc.calls.push({path:u.pathname,...f,clientId:cid});let data={ok:true},code=200;
 if(f.expectedDeviceId&&f.expectedDeviceId!==ID)return{code:409,body:JSON.stringify({ok:false,message:'Wrong Device ID'})};
 if(key!=='lab'&&method==='POST')try{
  if(u.pathname==='/api/control/acquire')await gate('begin',key,u.origin,ID,cid);
  else if(u.pathname==='/api/control/ping'||u.pathname==='/api/command'&&!['training_status','training_ping','training_end'].includes(f.type))await gate('authorize',key,u.origin,ID,cid);
 }catch(error){return{code:0,body:error.message};}
 if(u.pathname==='/api/status'){data=status(cid);if(key!=='lab'&&statusDelay){const delay=statusDelay;statusDelay=0;statusHeld=true;await sleep(delay);statusHeld=false;}}
 else if(u.pathname==='/api/telemetry'){if(telemetryDelay)await sleep(telemetryDelay);data={...status(cid),...(staleLabRc&&cid!==fc.owner?{rcAgeMs:2000}:{}),viewOnly:cid!==fc.owner,type:'telemetry',roll:0,pitch:0,yaw:0};}
 else if(u.pathname==='/api/control/acquire'){if(fc.owner&&cid!==fc.owner&&f.clientRole!=='MOBILE'&&!f.takeover){code=423;data={ok:false,message:'App controls the kit'};}else{if(f.takeover)finish();fc.owner=cid;fc.role=f.clientRole||'WEB';fc.grants++;data={ok:true,deviceId:ID,controlRole:fc.role,trainingRunId:fc.run,lockMine:true,rcTimeoutMs:1000,lockTimeoutMs:15000,rcUdpPort:fc.active&&f.rcTransport==='HTTP'?0:4210,rcUdpToken:fc.udpToken=(fc.run+123).toString(16).padStart(16,'0'),rcProtocol:fc.active?'ZRC2':'ZRC1',simulationOutputsBlocked:fc.active,simulationRcTransport:'UDP'};}}
 else if(u.pathname==='/api/control/release'){if(cid===fc.owner){fc.owner=fc.role='';if(fc.active)finish();}}
 else if(u.pathname==='/api/control/ping'){if(cid!==fc.owner){code=423;data={ok:false,message:'Control lost'};}}
 else if(u.pathname==='/api/command'){
  if(f.type==='training_status'){if(denyObserverStatus&&cid!==fc.owner)return{code:0,body:'Observer status unavailable'};data=training();}
  else if(f.type==='training_request'){fc.requestTarget=f.target;fc.requestId++;data=training();}
  else if(f.type==='training_stop'){fc.requestTarget='';finish();data=training();}
  else if(f.type==='training_end'){fc.cancelled.add(f.session);if(fc.active&&f.session===fc.session)finish();data=training();}
  else if(f.type==='training_ping'){fc.pings++;if(!fc.active||fc.session!==f.session||fc.owner!==cid){code=409;data={ok:false,message:'Lease lost'};}else data=training();}
  else if(f.type==='training_select'){if(selectionDelay)await sleep(selectionDelay);if(fc.cancelled.has(f.session)){code=409;data={ok:false,message:'Cancelled'};}else if(cid!==fc.owner||fc.role!=='MOBILE'){code=423;data={ok:false,message:'Mobile grant required'};}else{finish();fc.requestTarget='';fc.session=f.session;fc.target=f.target==='REAL'?'NONE':f.target;fc.active=f.target!=='REAL';data=training();}}
  else if(f.type==='flight_stop'){if(cid!==fc.owner){code=423;data={ok:false,message:'Control lost'};}else{fc.armed=false;data={ok:true,command:'flight_stop',deviceId:ID};}}
  else if(f.type==='rc_frame'){if(key!=='lab'&&fc.udpToken&&cid===fc.owner){await gate('offer',key,u.origin,ID,cid,f.channels);return{code:200,body:JSON.stringify({ok:true,rcQueued:true,rcAckAgeMs:0,outputsBlocked:fc.active,virtualArmed:!!fc.last&&fc.rc[4]>1500})};}if(rcDelay)await sleep(rcDelay);if(f.simulationRunId&&(!fc.active||Number(f.simulationRunId)!==fc.run)){code=409;data={ok:false,message:'Expired simulator run'};}else if(cid!==fc.owner){code=423;data={ok:false,message:'Control lost'};}else{fc.rc=f.channels.split(',').map(Number);fc.last=Date.now();fc.armed=!fc.active&&fc.rc[4]>=1500;data={ok:true,armed:fc.armed};}}
  else{code=400;data={ok:false,message:'Unexpected command '+f.type};}
 }else if(u.pathname==='/api/wifi/saved')data={ok:true,profiles:[]};
 if(key!=='lab'&&code===200&&method==='POST'){
  if(u.pathname==='/api/control/acquire'){await gate('accept',key,'','','',fc.active?'SIM':'');if(fc.udpToken)await gate('udp',key,u.origin,ID,cid,fc.udpToken+','+(fc.active?fc.run:0));}
  else if(u.pathname==='/api/control/release')await gate('release',key,u.origin,ID,cid);
  else if(f.type==='rc_frame')await gate('rc',key,u.origin,ID,cid,f.channels);
  else if(u.pathname==='/api/control/ping')await gate('ping',key,u.origin,ID,cid);
 }
 if(u.pathname==='/api/telemetry'&&u.searchParams.get('stream')==='rc')data=Object.fromEntries(Object.entries(data).filter(([k])=>['ok','kit','deviceId','name','ip','mode','armed','flightReady','flightMode','locked','lockMine','viewOnly','controlRole','trainingSelection','trainingActive','trainingTarget','trainingController','trainingRunId','rcSource','receiverHealth','rcAgeMs','rc','roll','pitch','yaw','webRcFrameHz','ppmFrameHz','flightLoopHz','batteryValid','battery'].includes(k)));
 return{code,body:JSON.stringify(data)};
}
const controlOn=p=>p.waitForFunction(()=>document.getElementById('controlToggle').getAttribute('aria-checked')==='true');
// Each new native run must acknowledge neutral input before a manual ARM.
// This keeps the browser pilot from racing the real Java publisher's startup.
const nativeNeutral=(p,run)=>p.waitForFunction(run=>{const n=window.AerionAndroid.rcDiagnostics();return n.validatedControllerAck===true&&Number(n.trainingRunId)===run&&Number(n.ackAgeMs)<150&&Array.isArray(n.acceptedChannels)&&Number(n.acceptedChannels[2])<=1050&&Number(n.acceptedChannels[4])<=1500;},run);
(async()=>{
 gateDir=fs.mkdtempSync(path.join(os.tmpdir(),'aerion-native-gate-'));execFileSync('java',['com.sun.tools.javac.Main','-d',gateDir,...['LeaseGate','LocalPolicy','NativeRcStream','SecureTransport'].map(n=>path.join(root,'android-app/app/src/main/java/in/zebjus/aerion',n+'.java')),path.join(__dirname,'NativeGateHarness.java')]);nativeGate=spawn('java',['-cp',gateDir,'in.zebjus.aerion.NativeGateHarness']);nativeGate.stderr.on('data',b=>process.stderr.write(b));nativeGate.stdout.on('data',b=>{gateOutput+=b;let end;while((end=gateOutput.indexOf('\n'))>=0){const line=gateOutput.slice(0,end);gateOutput=gateOutput.slice(end+1);const [id,...message]=line.split('\t');if(id==='RC'){const [client,token,channels]=message;if(client===fc.owner&&fc.udpToken&&BigInt('0x'+token)===BigInt('0x'+fc.udpToken)){fc.rc=channels.split(',').map(Number);fc.last=Date.now();fc.udpFrames++;fc.armed=!fc.active&&fc.rc[4]>1500;}continue;}if(id==='STOP'){phone?.evaluate(client=>AerionAndroid.stopped(client),message[0]).catch(()=>{});continue;}const pending=gateReplies.get(id);gateReplies.delete(id);if(pending){if(message[0]==='JSON')pending.resolve(JSON.parse(message.slice(1).join('\t')));else if(message.join('\t')==='OK')pending.resolve();else pending.reject(Error(message.join('\t')));}}});
 server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/rc/live'){
 if(u.searchParams.get('deviceId')!==ID)return res.writeHead(404).end();res.writeHead(200,{'Content-Type':'application/x-ndjson','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});
 const timer=setInterval(()=>{const full=status();const {name,ip,mode,locked,lockMine,expansion,sensors,rcMonitorProtocol,rcMonitorPort,...packet}=full;res.write(JSON.stringify({...packet,type:'rc_live',controllerMs:Date.now()-monitorBoot,rcFrameCount:fc.udpFrames,rcAgeMs:staleLabRc?2000:full.rcAgeMs,outputsBlocked:fc.active,virtualArmed:fc.active&&!!fc.last&&fc.rc[4]>1500,observerTransport:'NDJSON1'})+'\n');},100);req.on('close',()=>clearInterval(timer));return;
 }const rel=decodeURIComponent(u.pathname).replace(/^\//,'');const file=path.join(root,rel.startsWith('assets/')?'android-app/app/src/main/'+rel:rel||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return res.writeHead(404).end();const ext=path.extname(file);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://localhost:${server.address().port}`;
 browser=await chromium.launch({headless:true,executablePath:process.env.ZEBJUS_CHROMIUM,args:['--enable-unsafe-swiftshader']});phone=await browser.newPage({viewport:{width:1000,height:560},hasTouch:true,serviceWorkers:'block'});const errors=[];phone.on('pageerror',e=>errors.push(e.message));await require('../../tools/browser_pairing_double').install(phone,{native:false});await phone.exposeFunction('__request',api);await phone.exposeFunction('__offer',async(base,id,client,csv)=>{await gate('offer','',base,id,client,csv);return gate('diagnostics');});await phone.exposeFunction('__export',(name,body,mime)=>capturedExports.push({name,body,mime}));await phone.exposeFunction('__pause',(base,id,client)=>gate('pause','',base,id,client));await phone.addInitScript(()=>{window.__aerionToken='test';window.__nativeStatus={};window.NativeAerion={offerInput(token,base,id,client,csv){window.__offer(base,id,client,csv).then(d=>window.__nativeStatus=d).catch(()=>{});return true;},rcDiagnostics(){return JSON.stringify(window.__nativeStatus)},request(k,id,a,m,f,t){window.__request(id,a,m,f,t).then(r=>{if(a.includes("/api/control/acquire"))window.__nativeStatus={};window.AerionAndroid.deliver(id,r.code,r.body)})},pauseStream(k,base,id,client){window.__pause(base,id,client)},cancel(){},openWifi(){},joinWifi(){},saveFile(k,name,body,mime){window.__export(name,body,mime)}}});await phone.goto(origin+'/assets/flight/index.html');await phone.click('#heroAction');await phone.fill('#kitName','zebjus_drone_1');await phone.fill('#kitAddress','192.168.4.1');reachable=true;await phone.click('#checkConnection');await phone.waitForFunction(()=>document.getElementById('controlHint').textContent==='MOBILE SESSION');assert.equal(await phone.locator('[data-destination]').count(),0);assert.equal(await phone.locator('#practiceProps').count(),0);
 lab=await browser.newPage({viewport:{width:1100,height:850},serviceWorkers:'block'});await require('../../tools/browser_pairing_double').install(lab);lab.on('pageerror',e=>errors.push(e.message));await lab.route('**/api/**',async route=>{const req=route.request();if(new URL(req.url()).pathname==='/api/rc/live')return route.continue({url:origin+'/api/rc/live?deviceId='+ID});if(req.method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'content-type'}});const r=await api('lab',req.url(),req.method(),req.postData()||'');return route.fulfill({status:r.code,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:r.body});});await lab.goto(origin+'/?tab=training');await lab.waitForFunction(()=>window.__zebjusAppLoaded&&window.AerionTraining&&window.zebjusSchool);const acquireBefore=fc.calls.filter(x=>x.path==='/api/control/acquire'&&x.clientRole!=='MOBILE').length;await lab.waitForFunction(()=>zebjusSchool.isSelectedConnected(),null,{timeout:60000});await lab.selectOption('#trainingQuality','software');assert.equal(await lab.locator('#webAppIdValue').textContent(),'zebjus_drone_1');

 // Start on the web: the C3 app has no simulator buttons or routing ID entry.
 assert.equal(await phone.locator('#trainingWebAppId').count(),0);assert.equal(await phone.locator('#expectedId').isVisible(),false);
 await lab.evaluate(()=>zebjusLabAPI.setActiveTab('sim'));await lab.waitForFunction(()=>document.getElementById('simInputSource').value==='APP'&&!document.getElementById('simRunBtn').disabled);
 await lab.click('#simRunBtn');await controlOn(phone);assert.equal(fc.target,'TRIPOD');assert(fc.active&&!fc.armed);assert(fc.calls.some(x=>x.type==='training_request'&&x.target==='TRIPOD'));assert(fc.calls.some(x=>x.type==='training_select'&&Number(x.requestId)>0));
 await lab.waitForFunction(()=>zebjusSchool.state.tripodLow);await nativeNeutral(phone,fc.run);await phone.click('#arm');await lab.waitForFunction(()=>zebjusLabAPI.getSimState().running);
 await phone.keyboard.down('w');await phone.waitForFunction(()=>parseInt(document.getElementById('throttleValue').textContent)>=35);await phone.keyboard.up('w');await phone.keyboard.down('ArrowRight');await phone.keyboard.down('ArrowUp');
 await lab.waitForFunction(()=>zebjusSchool.state.joy[0]>1800&&zebjusSchool.state.joy[1]>1800&&zebjusSchool.state.joy[2]>1300);await lab.waitForFunction(()=>Math.abs(zebjusLabAPI.getSimState().roll)>.5);await phone.keyboard.up('ArrowRight');await phone.keyboard.up('ArrowUp');assert(!fc.armed,'virtual ARM must never arm the physical kit');
 staleLabRc=true;await lab.waitForFunction(()=>!zebjusLabAPI.getSimState().running);staleLabRc=false;await phone.click('#arm');await lab.waitForFunction(()=>zebjusSchool.state.tripodLow);await phone.click('#arm');await lab.waitForFunction(()=>zebjusLabAPI.getSimState().running);
 await lab.click('#simRunBtn');await phone.waitForFunction(()=>document.getElementById('controlHint').textContent==='MOBILE SESSION');assert(!fc.active&&!fc.armed&&fc.rc[2]===1000&&fc.rc[4]===1000);
 // Flight training is started from the web with the same joystick.
 await lab.evaluate(()=>zebjusLabAPI.setActiveTab('training'));await lab.selectOption('#trainingInput','APP');await lab.click('#trainingStart');await controlOn(phone);await lab.waitForFunction(()=>AerionTraining.bridge?.confirmed&&AerionTraining.bridge?.lowSeen);assert.equal(fc.target,'FLIGHT');await nativeNeutral(phone,fc.run);await phone.click('#arm');await lab.waitForFunction(()=>AerionTraining.running&&AerionTraining.model.armed);assert(!fc.armed);
 await phone.keyboard.down('w');await phone.waitForFunction(()=>parseInt(document.getElementById('throttleValue').textContent)>=65);await phone.keyboard.up('w');await lab.waitForFunction(()=>AerionTraining.model.y>.2);assert(!fc.armed);
 await lab.click('#trainingDisable');await phone.waitForFunction(()=>document.getElementById('controlHint').textContent==='MOBILE SESSION');assert(!fc.active&&!fc.armed);
 assert.equal(fc.calls.filter(x=>x.path==='/api/control/acquire'&&x.clientRole!=='MOBILE').length,acquireBefore,'web Start must not steal the mobile control grant');
 await phone.setViewportSize({width:390,height:844});assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await phone.screenshot({path:path.resolve(root,'../v18_3_82_android.png')});await lab.screenshot({path:path.resolve(root,'../v18_3_82_web.png')});assert.deepEqual(errors,[]);
 console.log('PASS: actual native Java publisher + bundled Android/web UI: kit-name connection, no mobile simulator/ID inputs, web Start auto links Tripod and Flight, all RC values/attitude/takeoff reflect, physical motors stay disarmed, stale RC stops simulation, manual ARM recovery, web STOP and repeated start preserve safe mobile reservation, portrait layout.');
})().catch(async error=>{console.error(error);if(phone)console.error(await phone.evaluate(()=>({notice:document.getElementById('notice').textContent,control:document.getElementById('controlHint').textContent,armDisabled:document.getElementById('arm').disabled,native:AerionAndroid.rcDiagnostics()})).catch(()=>null));console.error({run:fc.run,active:fc.active,target:fc.target,frames:fc.udpFrames,lastFrameAge:fc.last?Date.now()-fc.last:null,channels:fc.rc});if(lab){console.error(await lab.evaluate(()=>({selected:zebjusSchool?.getSelectedDevice?.(),note:document.getElementById('topNetworkNoticeText')?.textContent,training:document.getElementById('trainingMessage')?.textContent,sim:zebjusLabAPI?.getSimState?.()})).catch(()=>null));await lab.screenshot({path:path.resolve(root,'../v18_3_82_failure.png')}).catch(()=>{})}process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.close();if(nativeGate)nativeGate.kill('SIGTERM');if(gateDir)fs.rmSync(gateDir,{recursive:true,force:true});});
