'use strict';
// Actual native bundled UI + actual web Lab share one mock kit's ownership/RC.
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),ID='ZFC-001122334455',neutral=[1500,1500,1000,1500,1000,1000,1000,1000,1500,1000],sleep=ms=>new Promise(r=>setTimeout(r,ms));let server,browser,phone,lab,selectionDelay=0,reachable=false;
const fc={owner:'',role:'',active:false,target:'NONE',run:0,session:'',rc:[...neutral],last:0,armed:false,calls:[],cancelled:new Set(),pings:0,grants:0};
function training(){return{ok:true,deviceId:ID,supported:true,selectionSupported:true,active:fc.active,outputsBlocked:fc.active,target:fc.target,controller:'APP',input:'APP',runId:fc.run,leaseMs:5000};}
function status(cid=''){return{ok:true,kit:'ZEBJUS_FLIGHTCORE',deviceId:ID,name:'zebjus_drone_1',boardId:'ZFC-A2',boardName:'Aerion F1',firmware:'18.3.66',mode:'AP / DIRECT',ip:'192.168.4.1',armed:fc.armed,benchMode:0,locked:!!fc.owner,lockMine:!!cid&&cid===fc.owner,controlRole:fc.role,webRc:true,flightCoreIntegrated:true,flightReady:true,rcTimeoutMs:1000,trainingSelection:true,trainingActive:fc.active,trainingTarget:fc.target,trainingController:'APP',trainingRunId:fc.run,trainingInput:'APP',rcSource:fc.last?'WEB_AP':'NONE',rcAgeMs:fc.last?Date.now()-fc.last:999999,rc:fc.rc,expansion:{ppmArmMode:'CH5_SWITCH'},sensors:{imu:{fresh:true,usedInFlight:true}}};}
function finish(){fc.active=false;fc.target='NONE';fc.run++;fc.armed=false;fc.rc=[...neutral];}
async function api(key,address,method,form=''){
 if(!reachable)return{code:0,body:'Join kit Wi-Fi'};const u=new URL(address),f=Object.fromEntries(new URLSearchParams(form)),cid=f.clientId||u.searchParams.get('clientId')||'';fc.calls.push({path:u.pathname,...f,clientId:cid});let data={ok:true},code=200;
 if(f.expectedDeviceId&&f.expectedDeviceId!==ID)return{code:409,body:JSON.stringify({ok:false,message:'Wrong Device ID'})};
 if(u.pathname==='/api/status')data=status(cid);
 else if(u.pathname==='/api/telemetry')data={...status(cid),viewOnly:cid!==fc.owner,type:'telemetry',roll:0,pitch:0,yaw:0};
 else if(u.pathname==='/api/control/acquire'){if(fc.owner&&cid!==fc.owner&&f.clientRole!=='MOBILE'){code=423;data={ok:false,message:'App controls the kit'};}else{fc.owner=cid;fc.role=f.clientRole||'WEB';fc.grants++;data={ok:true,lockMine:true,rcTimeoutMs:1000,lockTimeoutMs:15000};}}
 else if(u.pathname==='/api/control/release'){if(cid===fc.owner){fc.owner=fc.role='';if(fc.active)finish();}}
 else if(u.pathname==='/api/control/ping'){if(cid!==fc.owner){code=423;data={ok:false,message:'Control lost'};}}
 else if(u.pathname==='/api/command'){
  if(f.type==='training_status')data=training();
  else if(f.type==='training_end'){fc.cancelled.add(f.session);if(fc.active&&f.session===fc.session)finish();data=training();}
  else if(f.type==='training_ping'){fc.pings++;if(!fc.active||fc.session!==f.session||fc.owner!==cid){code=409;data={ok:false,message:'Lease lost'};}else data=training();}
  else if(f.type==='training_select'){if(selectionDelay)await sleep(selectionDelay);if(fc.cancelled.has(f.session)){code=409;data={ok:false,message:'Cancelled'};}else if(cid!==fc.owner||fc.role!=='MOBILE'){code=423;data={ok:false,message:'Mobile grant required'};}else if(f.target!=='REAL'&&f.confirm!=='PROPS_REMOVED'){code=412;data={ok:false,message:'Remove props'};}else{finish();fc.session=f.session;fc.target=f.target==='REAL'?'NONE':f.target;fc.active=f.target!=='REAL';data=training();}}
  else if(f.type==='rc_frame'){if(cid!==fc.owner){code=423;data={ok:false,message:'Control lost'};}else{fc.rc=f.channels.split(',').map(Number);fc.last=Date.now();fc.armed=!fc.active&&fc.rc[4]>=1500;data={ok:true,armed:fc.armed};}}
  else{code=400;data={ok:false,message:'Unexpected command '+f.type};}
 }else if(u.pathname==='/api/wifi/saved')data={ok:true,profiles:[]};
 return{code,body:JSON.stringify(data)};
}
const controlOn=p=>p.waitForFunction(()=>document.getElementById('controlToggle').getAttribute('aria-checked')==='true');
async function select(target,props=true){await phone.click('#practiceMode');await phone.check(`[name=practiceTarget][value=${target}]`);if(props&&target!=='REAL')await phone.check('#practiceProps');await phone.click('#applyPractice');if(props||target==='REAL')await phone.waitForFunction(()=>!document.getElementById('practiceDialog').open);}
(async()=>{
 server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),rel=decodeURIComponent(u.pathname).replace(/^\//,'');const file=path.join(root,rel.startsWith('assets/')?'android-app/app/src/main/'+rel:rel||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return res.writeHead(404).end();const ext=path.extname(file);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://localhost:${server.address().port}`;
 browser=await chromium.launch({headless:true,executablePath:process.env.ZEBJUS_CHROMIUM,args:['--enable-unsafe-swiftshader']});phone=await browser.newPage({viewport:{width:1000,height:560},hasTouch:true,serviceWorkers:'block'});const errors=[];phone.on('pageerror',e=>errors.push(e.message));await phone.exposeFunction('__request',api);await phone.addInitScript(()=>{window.__aerionToken='test';window.NativeAerion={request(k,id,a,m,f,t){window.__request(id,a,m,f,t).then(r=>window.AerionAndroid.deliver(id,r.code,r.body))},cancel(){},openWifi(){},joinWifi(){}}});await phone.goto(origin+'/assets/flight/index.html');await phone.click('#heroAction');await phone.fill('#expectedId',ID);reachable=true;await phone.click('#checkConnection');await phone.waitForFunction(()=>document.getElementById('controlHint').textContent==='MOBILE SESSION');assert(await phone.locator('#practiceMode').isVisible());
 const selections=()=>fc.calls.filter(x=>x.type==='training_select').length;await select('FLIGHT',false);assert.match(await phone.locator('#practiceMessage').innerText(),/Remove every propeller/);assert.equal(selections(),0);await phone.check('#practiceProps');await phone.click('#applyPractice');await phone.waitForFunction(()=>!document.getElementById('practiceDialog').open);assert.equal(fc.target,'FLIGHT');assert(fc.active&&!fc.armed);assert(await phone.locator('#arm').isDisabled());assert.equal(fc.grants,2,'mode change must refresh the invalidated native UDP grant');
 lab=await browser.newPage({viewport:{width:1100,height:850},serviceWorkers:'block'});lab.on('pageerror',e=>errors.push(e.message));await lab.route('**/api/**',async route=>{const req=route.request();if(req.method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'content-type'}});const r=await api('lab',req.url(),req.method(),req.postData()||'');return route.fulfill({status:r.code,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:r.body});});await lab.goto(origin);await lab.waitForFunction(()=>window.__zebjusAppLoaded&&window.AerionTraining&&window.zebjusSchool);await lab.click('[data-tab=firmware]');await lab.fill('#kitSearchInput','zebjus_drone_1');await lab.fill('#kitCachedIp','192.168.4.1');await lab.click('#kitSearchBtn');await lab.waitForFunction(()=>zebjusSchool.isSelectedConnected());const acquireBefore=fc.calls.filter(x=>x.path==='/api/control/acquire'&&x.clientRole!=='MOBILE').length;await lab.click('[data-tab=training]');await lab.selectOption('#trainingQuality','software');await lab.waitForFunction(()=>AerionTraining.bridge?.observer);assert(!(await lab.evaluate(()=>zebjusSchool.canControl())));assert.equal(fc.calls.filter(x=>x.path==='/api/control/acquire'&&x.clientRole!=='MOBILE').length,acquireBefore,'observer must not request app control');
 await phone.click('#controlToggle');await controlOn(phone);await lab.waitForFunction(()=>AerionTraining.bridge?.lowSeen);await phone.click('#arm');await lab.waitForFunction(()=>AerionTraining.running&&AerionTraining.model.armed);await phone.keyboard.down('w');await phone.waitForFunction(()=>document.getElementById('throttleValue').textContent.replace('%','')>=65);await phone.keyboard.up('w');await lab.waitForFunction(()=>AerionTraining.model.y>.25);assert(!fc.armed,'training ARM never arms physical outputs');assert(!(await lab.evaluate(()=>zebjusLabAPI.getSimState().running)),'Tripod must stay stopped during Flight Training');await sleep(1600);assert(fc.pings>0,'foreground app renews its private training lease');assert.equal(fc.calls.filter(x=>x.type==='training_ping'&&x.clientId!==fc.owner).length,0,'web observer must not renew app-private lease');
 await select('TRIPOD');assert.equal(fc.target,'TRIPOD');await lab.waitForFunction(()=>!AerionTraining.running&&!AerionTraining.model.armed);await phone.click('#controlToggle');await controlOn(phone);await lab.waitForFunction(()=>zebjusSchool.state.tripodLow);await phone.click('#arm');await lab.waitForFunction(()=>zebjusLabAPI.getSimState().running);await phone.keyboard.down('ArrowRight');await sleep(150);await phone.keyboard.up('ArrowRight');assert.equal(await lab.evaluate(()=>AerionTraining.model.armed),false);assert(!fc.armed);const staleTraining={session:fc.session,owner:fc.owner};await select('REAL');await lab.waitForFunction(()=>!zebjusLabAPI.getSimState().running);assert(!fc.active&&!fc.armed);assert(await phone.locator('#arm').isDisabled());assert.equal(fc.rc[2],1000);assert.equal(fc.rc[4],1000);await phone.click('#controlToggle');await controlOn(phone);await phone.click('#arm');await phone.waitForFunction(()=>document.getElementById('flightState').textContent==='ARMED');const realRun=fc.run;await api('late', 'http://192.168.4.1/api/command','POST',new URLSearchParams({type:'training_end',clientId:staleTraining.owner,session:staleTraining.session,expectedDeviceId:ID}).toString());assert(fc.armed&&fc.run===realRun,'expired cleanup must not interrupt the fresh Real grant');await phone.click('#arm');await sleep(150);assert(!fc.armed);
 // A late selection cannot revive a mode after STOP, nor begin RC on its own.
 await phone.click('#practiceMode');await phone.check('[name=practiceTarget][value=FLIGHT]');await phone.check('#practiceProps');selectionDelay=500;await phone.click('#applyPractice');await sleep(60);await phone.evaluate(()=>document.getElementById('kill').click());await sleep(1100);selectionDelay=0;assert(!fc.active&&!fc.owner&&!fc.armed);await phone.locator('#practiceDialog').evaluate(d=>d.close());await phone.click('#practiceMode');await phone.check('[name=practiceTarget][value=FLIGHT]');await phone.check('#practiceProps');await phone.click('#applyPractice');await phone.waitForFunction(()=>!document.getElementById('practiceDialog').open);await phone.click('#controlToggle');await controlOn(phone);await phone.evaluate(()=>AerionAndroid.pause());await sleep(400);assert(!fc.active&&!fc.owner);assert(await phone.locator('#arm').isDisabled());await phone.evaluate(()=>AerionAndroid.resume());await sleep(300);assert(!fc.active&&!fc.owner,'resume requires new selection and manual ARM');
 await phone.setViewportSize({width:390,height:844});assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await phone.screenshot({path:path.resolve(root,'../native_modes_mobile.png')});assert.deepEqual(errors,[]);console.log('PASS: actual native app home modes + web observer; props confirmation, no control takeover, explicit transmission/manual ARM, exclusive Flight/Tripod RC, private app lease, safe Real selection, late mode STOP, native background cleanup and portrait layout');
})().catch(async e=>{console.error(e);if(phone)console.error('APP',await phone.evaluate(()=>({message:document.getElementById('practiceMessage').textContent,hint:document.getElementById('controlHint').textContent})).catch(()=>null));if(lab)console.error('LAB',await lab.evaluate(()=>({message:document.getElementById('trainingMessage').textContent,bridge:AerionTraining.bridge,kit:zebjusSchool.getSelectedDevice(),tripod:zebjusLabAPI.getSimState()})).catch(()=>null));process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)server.close()});
