'use strict';
// Actual native bundled UI + actual web Lab share one mock kit's ownership/RC.
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn,execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),ID='ZFC-001122334455',neutral=[1500,1500,1000,1500,1000,1000,1000,1000,1500,1000],sleep=ms=>new Promise(r=>setTimeout(r,ms));let server,browser,phone,lab,selectionDelay=0,reachable=false,denyObserverStatus=false,staleLabRc=false,statusDelay=0,statusHeld=false,realReady=false,rcDelay=0,telemetryDelay=0,udp2=true;const capturedExports=[];let nativeGate,gateDir,gateSequence=0,gateOutput='';const gateReplies=new Map();
function gate(op,key='',base='',id='',client='',channels=''){return new Promise((resolve,reject)=>{const n=String(++gateSequence);gateReplies.set(n,{resolve,reject});nativeGate.stdin.write([n,op,key,base,id,client,channels].join('\t')+'\n')})}
const monitorBoot=Date.now()-1000;
const fc={owner:'',role:'',active:false,target:'NONE',run:0,session:'',rc:[...neutral],last:0,armed:false,calls:[],cancelled:new Set(),pings:0,grants:0,udpToken:'',udpFrames:0};
function training(){return{ok:true,deviceId:ID,supported:true,selectionSupported:true,simulationRcTransport:'UDP',...(udp2?{simulationRcProtocol:'ZRC2'}:{}),active:fc.active,outputsBlocked:fc.active,target:fc.target,controller:'APP',input:'APP',runId:fc.run,leaseMs:5000};}
function status(cid=''){return{ok:true,kit:'ZEBJUS_FLIGHTCORE',deviceId:ID,name:'zebjus_drone_1',boardId:realReady?'ZFC-A2':'ZFC-A1',boardName:realReady?'Aerion F1':'ESP32-C3',firmware:'18.3.78',securityRequired:true,outputsBlocked:fc.active,mode:'STA',ip:'192.168.4.1',armed:fc.armed,benchMode:0,locked:!!fc.owner,lockMine:!!cid&&cid===fc.owner,controlRole:fc.role,webRc:realReady,flightCoreIntegrated:realReady,flightReady:realReady,simulationReady:true,simulationRcTransport:'UDP',rcMonitorProtocol:'ZFC3_NDJSON',rcMonitorPort:4211,rcTimeoutMs:1000,trainingSelection:true,trainingActive:fc.active,trainingTarget:fc.target,trainingController:'APP',trainingRunId:fc.run,trainingInput:'APP',rcSource:fc.last?'WEB_AP':'NONE',rcAgeMs:fc.last?Date.now()-fc.last:999999,rc:fc.rc,expansion:{ppmArmMode:'CH5_SWITCH'},sensors:{imu:{fresh:true,usedInFlight:true}}};}
function finish(){fc.active=false;fc.target='NONE';fc.run++;fc.armed=false;fc.udpToken='';fc.rc=[...neutral];}
async function api(key,address,method,form=''){
 if(!reachable)return{code:0,body:'Join kit Wi-Fi'};const u=new URL(address),f=Object.fromEntries(new URLSearchParams(form)),cid=f.clientId||u.searchParams.get('clientId')||'';fc.calls.push({path:u.pathname,...f,clientId:cid});let data={ok:true},code=200;
 if(f.expectedDeviceId&&f.expectedDeviceId!==ID)return{code:409,body:JSON.stringify({ok:false,message:'Wrong Device ID'})};
 if(key!=='lab'&&method==='POST')try{
  if(u.pathname==='/api/control/acquire')await gate('begin',key,u.origin,ID,cid);
  else if(u.pathname==='/api/control/ping'||u.pathname==='/api/command'&&!['training_status','training_ping','training_end'].includes(f.type))await gate('authorize',key,u.origin,ID,cid);
 }catch(error){return{code:0,body:error.message};}
 if(u.pathname==='/api/status'){data=status(cid);if(key!=='lab'&&statusDelay){const delay=statusDelay;statusDelay=0;statusHeld=true;await sleep(delay);statusHeld=false;}}
 else if(u.pathname==='/api/telemetry'){if(telemetryDelay)await sleep(telemetryDelay);data={...status(cid),...(staleLabRc&&cid!==fc.owner?{rcAgeMs:2000}:{}),viewOnly:cid!==fc.owner,type:'telemetry',roll:0,pitch:0,yaw:0};}
 else if(u.pathname==='/api/control/acquire'){if(fc.owner&&cid!==fc.owner&&f.clientRole!=='MOBILE'&&!f.takeover){code=423;data={ok:false,message:'App controls the kit'};}else{if(f.takeover)finish();fc.owner=cid;fc.role=f.clientRole||'WEB';fc.grants++;data={ok:true,deviceId:ID,controlRole:fc.role,trainingRunId:fc.run,lockMine:true,rcTimeoutMs:1000,lockTimeoutMs:15000,rcUdpPort:fc.active&&f.rcTransport==='HTTP'?0:4210,rcUdpToken:fc.udpToken=(fc.run+123).toString(16).padStart(16,'0'),rcProtocol:fc.active?'ZRC2':'ZRC1',simulationOutputsBlocked:fc.active,simulationRcTransport:'UDP'};}}
 else if(u.pathname==='/api/control/release'){if(cid===fc.owner){fc.owner=fc.role='';if(fc.active)finish();}}
 else if(u.pathname==='/api/control/ping'){if(cid!==fc.owner){code=423;data={ok:false,message:'Control lost'};}}
 else if(u.pathname==='/api/command'){
  if(f.type==='training_status'){if(denyObserverStatus&&cid!==fc.owner)return{code:0,body:'Observer status unavailable'};data=training();}
  else if(f.type==='training_end'){fc.cancelled.add(f.session);if(fc.active&&f.session===fc.session)finish();data=training();}
  else if(f.type==='training_ping'){fc.pings++;if(!fc.active||fc.session!==f.session||fc.owner!==cid){code=409;data={ok:false,message:'Lease lost'};}else data=training();}
  else if(f.type==='training_select'){if(selectionDelay)await sleep(selectionDelay);if(fc.cancelled.has(f.session)){code=409;data={ok:false,message:'Cancelled'};}else if(cid!==fc.owner||fc.role!=='MOBILE'){code=423;data={ok:false,message:'Mobile grant required'};}else{finish();fc.session=f.session;fc.target=f.target==='REAL'?'NONE':f.target;fc.active=f.target!=='REAL';data=training();}}
  else if(f.type==='rc_frame'){if(key!=='lab'&&fc.udpToken&&cid===fc.owner){await gate('offer',key,u.origin,ID,cid,f.channels);return{code:200,body:JSON.stringify({ok:true,rcQueued:true,rcAckAgeMs:0,outputsBlocked:fc.active,virtualArmed:!!fc.last&&fc.rc[4]>1500})};}if(rcDelay)await sleep(rcDelay);if(f.simulationRunId&&(!fc.active||Number(f.simulationRunId)!==fc.run)){code=409;data={ok:false,message:'Expired simulator run'};}else if(cid!==fc.owner){code=423;data={ok:false,message:'Control lost'};}else{fc.rc=f.channels.split(',').map(Number);fc.last=Date.now();fc.armed=!fc.active&&fc.rc[4]>=1500;data={ok:true,armed:fc.armed};}}
  else{code=400;data={ok:false,message:'Unexpected command '+f.type};}
 }else if(u.pathname==='/api/wifi/saved')data={ok:true,profiles:[]};
 if(key!=='lab'&&code===200&&method==='POST'){
  if(u.pathname==='/api/control/acquire'){await gate('accept',key,'','','',fc.active?'SIM':'');if(fc.udpToken)await gate('udp',key,u.origin,ID,cid,fc.udpToken+','+(fc.active?fc.run:0));}
  else if(u.pathname==='/api/control/release')await gate('release',key,u.origin,ID,cid);
  else if(f.type==='rc_frame')await gate('rc',key,u.origin,ID,cid,f.channels);
  else if(u.pathname==='/api/control/ping')await gate('ping',key,u.origin,ID,cid);
 }
 if(u.pathname==='/api/telemetry'&&u.searchParams.get('stream')==='rc')data=Object.fromEntries(Object.entries(data).filter(([k])=>['ok','kit','deviceId','name','ip','mode','armed','flightReady','flightMode','locked','lockMine','viewOnly','controlRole','trainingSelection','trainingActive','trainingTarget','trainingController','trainingRunId','rcSource','receiverHealth','rcAgeMs','rc','roll','pitch','yaw','webRcFrameHz','ppmFrameHz','flightLoopHz','batteryValid','battery'].includes(k)));
 return{code,body:JSON.stringify(data)};
}
const controlOn=p=>p.waitForFunction(()=>document.getElementById('controlToggle').getAttribute('aria-checked')==='true');
async function select(target){await phone.click(`[data-destination=${target}]`);await phone.waitForFunction(t=>document.querySelector(`[data-destination=${t}]`).getAttribute('aria-pressed')==='true'&&!document.querySelector(`[data-destination=${t}]`).disabled,target);}
(async()=>{
 gateDir=fs.mkdtempSync(path.join(os.tmpdir(),'aerion-native-gate-'));execFileSync('java',['com.sun.tools.javac.Main','-d',gateDir,...['LeaseGate','LocalPolicy','NativeRcStream','SecureTransport'].map(n=>path.join(root,'android-app/app/src/main/java/in/zebjus/aerion',n+'.java')),path.join(__dirname,'NativeGateHarness.java')]);nativeGate=spawn('java',['-cp',gateDir,'in.zebjus.aerion.NativeGateHarness']);nativeGate.stderr.on('data',b=>process.stderr.write(b));nativeGate.stdout.on('data',b=>{gateOutput+=b;let end;while((end=gateOutput.indexOf('\n'))>=0){const line=gateOutput.slice(0,end);gateOutput=gateOutput.slice(end+1);const [id,...message]=line.split('\t');if(id==='RC'){const [client,token,channels]=message;if(client===fc.owner&&fc.udpToken&&BigInt('0x'+token)===BigInt('0x'+fc.udpToken)){fc.rc=channels.split(',').map(Number);fc.last=Date.now();fc.udpFrames++;fc.armed=!fc.active&&fc.rc[4]>1500;}continue;}if(id==='STOP'){phone?.evaluate(client=>AerionAndroid.stopped(client),message[0]).catch(()=>{});continue;}const pending=gateReplies.get(id);gateReplies.delete(id);if(pending){if(message[0]==='JSON')pending.resolve(JSON.parse(message.slice(1).join('\t')));else if(message.join('\t')==='OK')pending.resolve();else pending.reject(Error(message.join('\t')));}}});
 server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/rc/live'){
 if(u.searchParams.get('deviceId')!==ID)return res.writeHead(404).end();res.writeHead(200,{'Content-Type':'application/x-ndjson','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});
 const timer=setInterval(()=>{const full=status();const {name,ip,mode,locked,lockMine,expansion,sensors,rcMonitorProtocol,rcMonitorPort,...packet}=full;res.write(JSON.stringify({...packet,type:'rc_live',controllerMs:Date.now()-monitorBoot,rcFrameCount:fc.udpFrames,rcAgeMs:staleLabRc?2000:full.rcAgeMs,outputsBlocked:fc.active,virtualArmed:fc.active&&!!fc.last&&fc.rc[4]>1500,observerTransport:'NDJSON1'})+'\n');},100);req.on('close',()=>clearInterval(timer));return;
 }const rel=decodeURIComponent(u.pathname).replace(/^\//,'');const file=path.join(root,rel.startsWith('assets/')?'android-app/app/src/main/'+rel:rel||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return res.writeHead(404).end();const ext=path.extname(file);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://localhost:${server.address().port}`;
 browser=await chromium.launch({headless:true,executablePath:process.env.ZEBJUS_CHROMIUM,args:['--enable-unsafe-swiftshader']});phone=await browser.newPage({viewport:{width:1000,height:560},hasTouch:true,serviceWorkers:'block'});const errors=[];phone.on('pageerror',e=>errors.push(e.message));await require('../../tools/browser_pairing_double').install(phone,{native:false});await phone.exposeFunction('__request',api);await phone.exposeFunction('__offer',async(base,id,client,csv)=>{await gate('offer','',base,id,client,csv);return gate('diagnostics');});await phone.exposeFunction('__export',(name,body,mime)=>capturedExports.push({name,body,mime}));await phone.exposeFunction('__pause',(base,id,client)=>gate('pause','',base,id,client));await phone.addInitScript(()=>{window.__aerionToken='test';window.__nativeStatus={};window.NativeAerion={offerInput(token,base,id,client,csv){window.__offer(base,id,client,csv).then(d=>window.__nativeStatus=d).catch(()=>{});return true;},rcDiagnostics(){return JSON.stringify(window.__nativeStatus)},request(k,id,a,m,f,t){window.__request(id,a,m,f,t).then(r=>{if(a.includes("/api/control/acquire"))window.__nativeStatus={};window.AerionAndroid.deliver(id,r.code,r.body)})},pauseStream(k,base,id,client){window.__pause(base,id,client)},cancel(){},openWifi(){},joinWifi(){},saveFile(k,name,body,mime){window.__export(name,body,mime)}}});await phone.goto(origin+'/assets/flight/index.html');await phone.click('#heroAction');await phone.fill('#expectedId',ID);reachable=true;await phone.click('#checkConnection');await phone.waitForFunction(()=>document.getElementById('controlHint').textContent==='MOBILE SESSION');assert.equal(await phone.locator('[data-destination]').count(),3);assert.equal(await phone.locator('#practiceProps').count(),0);
 // A1 / no ready IMU must be able to select and use simulation.
 const selections=()=>fc.calls.filter(x=>x.type==='training_select').length;statusDelay=700;for(let i=0;!statusHeld&&i<100;i++)await sleep(20);assert(statusHeld,'hold old refresh reply across selection');await select('FLIGHT');assert.equal(selections(),1);assert.equal(fc.target,'FLIGHT');assert(fc.active&&!fc.armed);await controlOn(phone);await sleep(900);assert(fc.active,'old refresh must not stop the new training grant');assert.equal(await phone.locator('#controlToggle').getAttribute('aria-checked'),'true');assert(!(await phone.locator('#arm').isDisabled()));await phone.click('#arm');denyObserverStatus=true;assert.equal(fc.grants,2);assert(fc.calls.some(x=>x.path==='/api/control/acquire'&&x.rcTransport==='UDP2'),'simulator must explicitly negotiate scoped ZRC2 input');
 lab=await browser.newPage({viewport:{width:1100,height:850},serviceWorkers:'block'});await require('../../tools/browser_pairing_double').install(lab);lab.on('pageerror',e=>errors.push(e.message));await lab.route('**/api/**',async route=>{const req=route.request();if(new URL(req.url()).pathname==='/api/rc/live')return route.continue({url:origin+'/api/rc/live?deviceId='+ID});if(req.method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'content-type'}});const r=await api('lab',req.url(),req.method(),req.postData()||'');return route.fulfill({status:r.code,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:r.body});});await lab.goto(origin+'/?tab=training');await lab.waitForFunction(()=>window.__zebjusAppLoaded&&window.AerionTraining&&window.zebjusSchool);const acquireBefore=fc.calls.filter(x=>x.path==='/api/control/acquire'&&x.clientRole!=='MOBILE').length;await lab.waitForFunction(()=>zebjusSchool.isSelectedConnected(),null,{timeout:60000});await lab.selectOption('#trainingQuality','software');await lab.waitForFunction(()=>AerionTraining.bridge?.observer);assert(!(await lab.evaluate(()=>zebjusSchool.canControl())));assert.equal(fc.calls.filter(x=>x.path==='/api/control/acquire'&&x.clientRole!=='MOBILE').length,acquireBefore,'observer must not request app control');
 await lab.waitForFunction(()=>AerionTraining.running&&AerionTraining.model.armed);const run=fc.run;await sleep(3000);assert.equal(await lab.evaluate(()=>AerionTraining.bridge?.runId),run);assert(await lab.evaluate(()=>AerionTraining.running&&AerionTraining.model.armed),'observer status failure must not reset active app training');await phone.keyboard.down('w');await phone.waitForFunction(()=>document.getElementById('throttleValue').textContent.replace('%','')>=65);await phone.keyboard.up('w');await lab.waitForFunction(()=>AerionTraining.model.y>.25);assert(!fc.armed,'training ARM never arms physical outputs');assert(!(await lab.evaluate(()=>zebjusLabAPI.getSimState().running)),'Tripod must stay stopped during Flight Training');await sleep(1600);assert.equal(fc.pings,0,'acknowledged RC avoids redundant training HTTP pings');assert.equal(fc.calls.filter(x=>x.type==='training_ping'&&x.clientId!==fc.owner).length,0,'web observer must not renew app-private lease');
 // Telemetry loss freezes the existing lesson. A held ARM cannot resume it.
 const flightTime=await lab.evaluate(()=>AerionTraining.model.time);staleLabRc=true;await lab.waitForFunction(()=>AerionTraining.paused&&!AerionTraining.model.armed);assert(await lab.evaluate(()=>AerionTraining.bridge?.observer));staleLabRc=false;await sleep(500);assert(await lab.evaluate(()=>AerionTraining.paused),'held ARM cannot resume a stale-input pause');await phone.keyboard.down('s');await phone.waitForFunction(()=>document.getElementById('throttleValue').textContent==='0%');await phone.keyboard.up('s');await phone.click('#arm');await lab.waitForFunction(()=>AerionTraining.bridge?.lowSeen);await phone.click('#arm');await lab.waitForFunction(()=>!AerionTraining.paused&&AerionTraining.model.armed);assert((await lab.evaluate(()=>AerionTraining.model.time))>=flightTime,'recovery keeps mission progress');assert.equal(fc.run,run);

 // Real native UDP ACK silence must retain the active inhibited run without HTTP/reselection.
 const gapOwner=fc.owner,gapSelections=selections(),gapHttp=fc.calls.length;await gate('ack_off');await sleep(4000);assert.equal(fc.run,run);assert.equal(fc.owner,gapOwner);assert.equal(fc.rc[2],1000);assert.equal(fc.rc[4],1000);assert.equal(selections(),gapSelections);assert.equal(fc.calls.length,gapHttp,'active app/web control must not add HTTP requests during ACK silence');await gate('ack_on');await sleep(400);assert.equal(fc.run,run);assert.equal(fc.owner,gapOwner);assert.equal(fc.rc[4],1000);assert.equal(await phone.locator('#controlToggle').getAttribute('aria-checked'),'true');

 await select('TRIPOD');assert.equal(fc.target,'TRIPOD');await lab.waitForFunction(()=>!AerionTraining.running&&!AerionTraining.model.armed);await controlOn(phone);await lab.waitForFunction(()=>zebjusSchool.state.tripodLow);await phone.click('#arm');await lab.waitForFunction(()=>zebjusLabAPI.getSimState().running);await phone.keyboard.down('ArrowRight');await sleep(150);await phone.keyboard.up('ArrowRight');assert.equal(await lab.evaluate(()=>AerionTraining.model.armed),false);assert(!fc.armed);const staleTraining={session:fc.session,owner:fc.owner};realReady=true;await select('REAL');await lab.waitForFunction(()=>!zebjusLabAPI.getSimState().running);assert(!fc.active&&!fc.armed);assert(await phone.locator('#arm').isDisabled());assert.equal(fc.rc[2],1000);assert.equal(fc.rc[4],1000);await phone.click('#controlToggle');await controlOn(phone);await phone.click('#arm');await phone.waitForFunction(()=>document.getElementById('flightState').textContent==='ARMED');await phone.keyboard.down('ArrowRight');await phone.keyboard.down('ArrowUp');await lab.waitForFunction(()=>zebjusSchool.state.joy[0]>1800&&zebjusSchool.state.joy[1]>1800);assert(await lab.locator('#takeControlBtn').isDisabled(),'exclusive mobile control is observer-only');await phone.keyboard.up('ArrowRight');await phone.keyboard.up('ArrowUp');const realRun=fc.run;await api('late', 'http://192.168.4.1/api/command','POST',new URLSearchParams({type:'training_end',clientId:staleTraining.owner,session:staleTraining.session,expectedDeviceId:ID}).toString());assert(fc.armed&&fc.run===realRun,'expired cleanup must not interrupt the fresh Real grant');await phone.click('#arm');await sleep(150);assert(!fc.armed);
 // A transient 260 ms response delay must not produce kit-not-found / ACK loss.
 await select('FLIGHT');await controlOn(phone);rcDelay=1000;await sleep(2700);assert.equal(await phone.locator('#controlToggle').getAttribute('aria-checked'),'true');rcDelay=0;
 // Hold HTTP longer than the previous field-report gaps; native input and stream observation must remain live.
 udp2=true;await select('FLIGHT');await controlOn(phone);await lab.waitForFunction(()=>AerionTraining.bridge?.lowSeen);await phone.click('#arm');await lab.waitForFunction(()=>AerionTraining.running&&AerionTraining.model.armed);rcDelay=1200;telemetryDelay=1200;const udpBefore=fc.udpFrames;
 await phone.keyboard.down('w');await phone.waitForFunction(()=>document.getElementById('throttleValue').textContent.replace('%','')>=65);await phone.keyboard.up('w');await phone.keyboard.down('ArrowRight');await phone.keyboard.down('ArrowUp');await lab.waitForFunction(()=>AerionTraining.model.y>.25);await sleep(2700);
 assert(await lab.evaluate(()=>!AerionTraining.paused&&AerionTraining.model.armed),'acknowledged simulation stream keeps Flight Training live');assert(fc.udpFrames>udpBefore+150,'native 50 Hz input continues while HTTP is delayed');assert(fc.calls.some(x=>x.rcTransport==='UDP2'));assert.equal(await lab.evaluate(()=>zebjusSchool.rcMonitor?.diagnostics().state),'live');await phone.keyboard.up('ArrowRight');await phone.keyboard.up('ArrowUp');
 await select('TRIPOD');await lab.waitForFunction(()=>zebjusSchool.state.tripodLow);await phone.click('#arm');await lab.waitForFunction(()=>zebjusLabAPI.getSimState().running);await phone.keyboard.down('w');await phone.waitForFunction(()=>document.getElementById('throttleValue').textContent.replace('%','')>=65);await phone.keyboard.up('w');await phone.keyboard.down('ArrowRight');await phone.keyboard.down('ArrowUp');
 await lab.waitForFunction(()=>{const s=zebjusLabAPI.getSimState();return s.cmdRoll>.5&&s.cmdPitch>.5&&Math.abs(s.roll)>1&&Math.abs(s.pitch)>1});assert.match(await lab.locator('#rightStickRead').textContent(),/P [1-9]/);assert(await lab.evaluate(()=>parseFloat(document.getElementById('rightStickKnob').style.left)>50),'virtual stick reflects phone roll in real time');await sleep(1200);assert(await lab.evaluate(()=>zebjusLabAPI.getSimState().running));assert(!fc.armed);await phone.keyboard.up('ArrowRight');await phone.keyboard.up('ArrowUp');rcDelay=0;
 await select('FLIGHT');await controlOn(phone);
 // An actual native hard stop fences; short ACK gaps above never call this callback.
 await phone.evaluate(()=>AerionAndroid.stopped());await sleep(350);assert.equal(await phone.locator('#controlToggle').getAttribute('aria-checked'),'false');assert(!fc.active&&!fc.owner&&!fc.armed);
 // Tripod opened after app ARM can join at neutral without a hidden ARM-low edge.
 await select('TRIPOD');await phone.click('#arm');await lab.reload();await lab.waitForFunction(()=>window.__zebjusAppLoaded&&window.zebjusSchool&&zebjusSchool.isSelectedConnected(),null,{timeout:60000});await lab.waitForFunction(()=>zebjusLabAPI.getSimState().running);assert(!fc.armed);
 // The laptop cannot replace the app's inhibited training lease.
 await lab.evaluate(()=>zebjusLabAPI.setActiveTab('joystick'));assert(await lab.locator('#mobileTakeWebControl').isDisabled());assert.equal(fc.role,'MOBILE');assert(fc.active&&!fc.armed);await phone.click('#arm');
 // Actual diagnostic export is available in the app and web Telemetry.
 await phone.click('#kitSettings');await phone.locator('#appFlightRecorder [data-fr-action=mark]').click();await phone.locator('#appFlightRecorder [data-fr-action=json]').click();await phone.waitForTimeout(100);await phone.setViewportSize({width:390,height:844});await phone.locator('#appFlightRecorder').scrollIntoViewIfNeeded();assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'app recorder portrait width');await phone.screenshot({path:path.resolve(root,'../flight_recorder_app.png')});assert(capturedExports.length);const appReport=JSON.parse(capturedExports.at(-1).body);assert.equal(appReport.actor,'app');assert.equal(appReport.deviceId,ID);assert(appReport.controlSamples.length>0&&appReport.controlSamples.some(s=>s.offeredChannels?.length===10));assert(appReport.controlSamples.some(s=>s.nativeRc?.validatedControllerAck)&&appReport.events.some(x=>x.kind==='user-marker'));assert(!capturedExports.at(-1).body.includes(fc.udpToken&&fc.udpToken.length>5?fc.udpToken:'impossible-private-token'));await phone.locator('[data-close=kitDialog]').click();
 await lab.evaluate(()=>zebjusLabAPI.setActiveTab('telemetry'));await lab.waitForFunction(()=>AerionWebRecorder.samples.length>0);const downloadReady=lab.waitForEvent('download');await lab.locator('#flightRecorderRoot [data-fr-action=json]').click();const reportDownload=await downloadReady;const webReport=JSON.parse(fs.readFileSync(await reportDownload.path(),'utf8'));assert.equal(webReport.actor,'web');assert.equal(webReport.deviceId,ID);assert.equal(await lab.locator('#telemetryLog').textContent().then(v=>v.includes('\"rc\"')),false,'raw telemetry spam removed');await lab.locator('#flightRecorderRoot').scrollIntoViewIfNeeded();await lab.screenshot({path:path.resolve(root,'../flight_recorder_web.png')});await lab.setViewportSize({width:390,height:844});assert(await lab.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'web recorder portrait width');await lab.screenshot({path:path.resolve(root,'../flight_recorder_web_mobile.png')});await lab.setViewportSize({width:1374,height:850});
 // STOP and background cancel recovery and any delayed destination acquisition.
 selectionDelay=500;await phone.click('[data-destination=FLIGHT]');await sleep(60);await phone.evaluate(()=>document.getElementById('kill').click());await sleep(1100);selectionDelay=0;assert(!fc.active&&!fc.owner&&!fc.armed);await select('FLIGHT');await controlOn(phone);await phone.evaluate(()=>AerionAndroid.pause());await sleep(400);assert(!fc.active&&!fc.owner);assert(await phone.locator('#arm').isDisabled());await phone.evaluate(()=>AerionAndroid.resume());await sleep(300);assert(!fc.active&&!fc.owner,'resume requires new selection and manual ARM');
 const firmwareAvailable=JSON.parse(fs.readFileSync(path.join(root,'FlightCore_Firmware/catalog.json'),'utf8')).boards.find(x=>x.id==='ZFC-A2').latest.app.available;
 if(firmwareAvailable){
 await lab.evaluate(()=>zebjusLabAPI.setActiveTab('firmware'));await lab.selectOption('#fwBoardProfile','ZFC-A2');await lab.waitForFunction(()=>document.getElementById('fwFileName').textContent==='ZEBJUS_FLIGHTCORE_A2_APP.bin'&&document.getElementById('fwSourceBadge').textContent==='LOADED');assert.equal(await lab.locator('#fwFileInput').getAttribute('accept'),null,'OS MIME filters must not hide .bin');
 await lab.route('**/*APP.bin*',r=>r.abort());await lab.click('#fwAutoLoadBtn');await lab.waitForFunction(()=>document.getElementById('fwPackageState').textContent==='CACHED BUILD');assert.match(await lab.locator('#fwSourceMessage').innerText(),/offline\/AP/);
 const downloadPromise=lab.waitForEvent('download');await lab.click('#fwDownloadBinBtn');const download=await downloadPromise;assert.equal(download.suggestedFilename(),'ZEBJUS_FLIGHTCORE_A2_APP.bin');const saved=await download.path();assert(fs.readFileSync(saved).equals(fs.readFileSync(path.join(root,'FlightCore_Firmware/ZEBJUS_FLIGHTCORE_A2_APP.bin'))),'download exact verified cached bytes');
 await lab.locator('#fwFileInput').setInputFiles({name:'ap-update.bin',mimeType:'application/x-unknown',buffer:fs.readFileSync(path.join(root,'FlightCore_Firmware/ZEBJUS_FLIGHTCORE_A2_APP.bin'))});await lab.waitForFunction(()=>document.getElementById('fwFileName').textContent==='ap-update.bin'&&document.getElementById('fwPackageState').textContent==='IMPORTED');
 }else console.log('Matching firmware still awaits its compiler build; cached firmware integration runs after compilation.');
 await select('FLIGHT');await controlOn(phone);await phone.click('#arm');await phone.setViewportSize({width:390,height:844});assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));const boxes=await phone.evaluate(()=>Object.fromEntries(['connect','arm','networkMode','controlToggle','kitSettings','mode','kill'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return[id,{left:r.left,right:r.right,top:r.top,bottom:r.bottom}]})));const row=['arm','networkMode','controlToggle','kitSettings','mode','kill'];for(let i=1;i<row.length;i++)assert(boxes[row[i-1]].right<=boxes[row[i]].left+1,'portrait header buttons must not overlap');await phone.screenshot({path:path.resolve(root,'../native_modes_mobile.png')});assert.deepEqual(errors,[]);console.log('PASS: production native grant policy + actual app/web UI; '+(firmwareAvailable?'AP cached firmware/import/download; ':'matching firmware cache checks pending compilation; ')+'stale refresh fencing; one-tap no-props simulator selection, A1/no-IMU readiness, native ZRC2 + NDJSON1 simulator controls, bounded delayed HTTP/live Flight/Tripod stick response and safe recovery, late Tripod attach, blocked web takeover and same-run four-second ACK recovery without HTTP, compact RC telemetry, Real stick mirror, automatic simulator controls/manual ARM, late armed-page attach, failed observer polls, same-session telemetry recovery, exclusive Flight/Tripod RC, private app lease, safe Real selection, late mode STOP, native background cleanup, actual diagnostic exports and recorder portrait layout');
})().catch(async e=>{console.error(e);if(phone)console.error('APP',await phone.evaluate(()=>({message:document.getElementById('practiceState').textContent,hint:document.getElementById('controlHint').textContent})).catch(()=>null));if(lab)console.error('LAB',await lab.evaluate(()=>({message:document.getElementById('trainingMessage').textContent,bridge:AerionTraining.bridge,kit:zebjusSchool.getSelectedDevice(),tripod:zebjusLabAPI.getSimState()})).catch(()=>null));process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)server.close();if(nativeGate)nativeGate.kill();if(gateDir)fs.rmSync(gateDir,{recursive:true,force:true})});
