'use strict';
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
let requested,upload,cancelled;const nodes=new Map();const node=()=>({value:'',textContent:'',disabled:false,after(){}});for(const id of ['expectedId','pairMessage','androidWifi','checkConnection','fwConnectUsbBtn','fwUsbState'])nodes.set(id,node());
const sandbox={window:{__aerionToken:'private-test-token',NativeAerion:{request(...args){requested=args},cancel(...args){cancelled=args},uploadFirmware(...args){upload=args}}},navigator:{},document:{getElementById:id=>nodes.get(id),createElement:node,querySelector:()=>node()},addEventListener(){},Map,Math,Date,Number,String,URLSearchParams,Response,DOMException,Error,setTimeout,clearTimeout,btoa,console};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('android-app/app/src/main/assets/android-transport.js','utf8'),sandbox);
(async()=>{
 const p=sandbox.window.fetch('http://192.168.4.1/api/status',{aerionTimeout:400});assert.equal(requested[0],'private-test-token');assert.equal(requested[4],'');sandbox.window.AerionAndroid.deliver(requested[1],200,'{"ok":true}');assert.equal((await (await p).json()).ok,true);
 const ctl=new AbortController(),q=sandbox.window.fetch('http://192.168.4.1/api/status',{signal:ctl.signal});ctl.abort();await assert.rejects(q,/cancelled/);assert(cancelled,'abort reaches native network request');
 const bytes=Uint8Array.from([0xE9,1,2,3]),u=sandbox.window.AerionAndroid.uploadFirmware('http://192.168.4.1/api/firmware/update',bytes,{clientId:'FLY-testclient',expectedDeviceId:'ZFC-001122334455',boardId:'ZFC-A2'});assert.deepEqual([...Buffer.from(upload[3],'base64')],[...bytes]);assert.match(upload[4],/expectedDeviceId=ZFC-001122334455/);sandbox.window.AerionAndroid.deliver(upload[1],200,'{"ok":true,"message":"written"}');assert.equal((await u).message,'written');
 console.log('PASS: native fetch identity token, abort/cancellation, firmware binary transfer and scoped upload identity');
})().catch(e=>{console.error(e);process.exitCode=1});
