'use strict';
const assert=require('node:assert/strict');const {RcLiveStream,validPacket}=require('../rc-live.js');
const ID='ZFC-001122334455',sample={type:'rc_live',deviceId:ID,controllerMs:100,trainingRunId:7,trainingActive:true,outputsBlocked:true,trainingTarget:'FLIGHT',rcSource:'WEB_AP',rcAgeMs:10,rc:[1800,1200,1650,1500,2000,1000,1000,1000,1500,1000]};
assert(validPacket(sample,ID));for(const patch of[{deviceId:'ZFC-FFEEDDCCBBAA'},{outputsBlocked:false},{rc:[1000]},{rcSource:'unknown'},{rc:sample.rc.map(()=>999)}])assert(!validPacket({...sample,...patch},ID));
(async()=>{let signal,control;const received=[],events=[];global.fetch=async(url,options)=>{assert(new URL(url).port==='4211');assert.equal(new URL(url).searchParams.get('deviceId'),ID);signal=options.signal;return{ok:true,body:new ReadableStream({start(c){control=c;signal.addEventListener('abort',()=>c.close())}})}};
const monitor=new RcLiveStream({packet:t=>received.push(t),event:e=>events.push(e)});monitor.update('http://192.168.4.1',ID,{rcMonitorPort:4211,rcMonitorProtocol:'NDJSON1'});await new Promise(r=>setTimeout(r,5));const line=JSON.stringify(sample)+'\n',encoder=new TextEncoder();control.enqueue(encoder.encode(line.slice(0,18)));control.enqueue(encoder.encode(line.slice(18)+JSON.stringify({...sample,controllerMs:101})+'\n'+JSON.stringify({...sample,controllerMs:99})+'\n'));await new Promise(r=>setTimeout(r,20));assert.equal(received.length,1);assert.equal(received[0].controllerMs,101);assert.equal(monitor.stats.frames,2);assert.equal(monitor.stats.invalidFrames,1);assert(monitor.live);assert(events.some(e=>e.state==='live'));// A buffered stream keeps ARM low/high and destination changes while coalescing sticks.
const frames=[{...sample,controllerMs:102,rc:sample.rc.map((v,i)=>i===4?1000:v)},{...sample,controllerMs:103},{...sample,controllerMs:104},{...sample,controllerMs:105,trainingRunId:8}];
control.enqueue(encoder.encode(frames.map(t=>JSON.stringify(t)+'\n').join('')));await new Promise(r=>setTimeout(r,20));assert.deepEqual(received.slice(1).map(t=>[t.controllerMs,t.rc[4],t.trainingRunId]),[[102,1000,7],[104,2000,7],[105,2000,8]]);
monitor.stop();assert(signal.aborted);assert(!monitor.live);monitor.update('http://192.168.4.1',ID,{});assert.equal(monitor.state,'off');console.log('PASS: production NDJSON parser, split/multiple chunks, scoped identities/output inhibition/channel bounds, old snapshots, cancellation and old-firmware fallback');})().catch(e=>{console.error(e);process.exitCode=1});
