'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(require('path').join(__dirname,'../app.js'),'utf8');
const grab=(start,end)=>source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)));
const elements={};for(const id of ['pythonOutputWindow','pythonOutputImage','pythonOutputDownload','pythonOutputTitle','pythonCameraVideo','pythonCameraStatus'])elements[id]={hidden:true,src:'',href:'',removeAttribute(name){this[name]=''},getAttribute(name){return this[name]||null}};
let stopped=0;
const ctx={$:selector=>elements[selector.slice(1)],pythonOutputKind:'',pythonOutputDismissed:false,pythonScriptImageSeen:false,pythonCameraStream:{getTracks:()=>[{stop:()=>stopped++}]},pythonCameraEpoch:0,pythonOutputPreviewTimer:0,pythonHandData:{},pythonCameraNote:()=>{},stopPythonHands:()=>{},clearInterval:()=>{},pythonTerminalWrite:()=>{},pythonCameraPump:0,document:{hidden:false},pythonCameraFrame:()=> 'ZmFrZQ=='};
vm.createContext(ctx);
vm.runInContext(grab('function clearPythonCameraOutput()', 'function cleanPythonTraceback(error)'),ctx);
vm.runInContext(grab('function stopPythonCamera()', 'function pythonCameraFrame()'),ctx);
ctx.pythonVisualImage({mimeType:'image/jpeg',base64:'ZmFrZQ==',title:'Camera'});
assert.equal(elements.pythonOutputWindow.hidden,false);
ctx.stopPythonCamera();
assert.equal(stopped,1);assert.equal(elements.pythonOutputWindow.hidden,true);assert.equal(elements.pythonOutputImage.src,'');assert.equal(elements.pythonOutputDownload.href,'');
ctx.pythonVisualImage({mimeType:'image/png',base64:'ZmFrZQ==',title:'Plot'});
assert.equal(elements.pythonOutputWindow.hidden,false);
ctx.stopPythonCamera();
assert.equal(elements.pythonOutputWindow.hidden,false);assert.ok(elements.pythonOutputImage.src.startsWith('data:image/png'));
assert(!source.includes("$('#pythonPlotImage')"),'duplicate embedded image should not be used');
console.log('PASS: camera output clears on stop; plot persists in the sole popup');
