'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{spawn}=require('node:child_process'),{chromium}=require('playwright');let browser,server,page;const pause=ms=>new Promise(r=>setTimeout(r,ms)),root=path.resolve(__dirname,'..'),port=8925,origin='http://localhost:'+port;
(async()=>{server=spawn('python3',[path.join(root,'start_offline.py'),'--no-browser','--port',String(port)],{cwd:root});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server timeout')),10000);server.stdout.on('data',d=>{if(String(d).includes('offline WebApp:')){clearTimeout(timer);resolve()}})});browser=await chromium.launch({headless:true,executablePath:process.env.ZEBJUS_CHROMIUM,args:['--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1374,height:850},serviceWorkers:'block'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.waitForFunction(()=>window.__zebjusAppLoaded&&window.AerionWorkflow&&window.AerionTraining);
 assert.deepEqual(await page.locator('.tab').evaluateAll(e=>e.map(x=>x.dataset.tab)),['assembly','wiring','setup','io','sim','joystick','training','firmware','telemetry','python','settings']);
 const out=process.env.ZEBJUS_LEARNING_SCREENSHOTS||path.resolve(root,'../learning_lab_screenshots');fs.mkdirSync(out,{recursive:true});
 for(const tab of ['setup','io','firmware','telemetry','training']){await page.click(`[data-tab="${tab}"]`);await pause(200);assert(await page.locator('#tab-'+tab).isVisible());await page.screenshot({path:path.join(out,tab+'.png')})}
 await page.click('[data-tab="io"]');assert.equal(await page.locator('.tool-tile').count(),15);await page.click('[data-tool="calibration"]');assert(await page.locator('#calReadBtn').isVisible());assert(!await page.locator('#hardwareToolMenu').isVisible());await page.click('#hardwareToolBack');await page.click('[data-tool="guided:Sensors"]');assert(await page.locator('#hardwareWizard [data-fs=detect]').isVisible());await page.click('#hardwareToolBack');
 await page.click('[data-tab="firmware"]');assert(await page.locator('#kitSearchBtn').isVisible());assert(await page.locator('#fwUpgradeBtn').isVisible());assert(await page.locator('#fwUpgradeEraseBtn').isVisible());
 await page.click('[data-tab="telemetry"]');assert.equal(await page.locator('.instrument-grid canvas').count(),4);assert.match(await page.locator('#gaugeAltitude').innerText(),/NOT AVAILABLE/);await pause(350);assert.equal(await page.locator('#telRoll').innerText(),'—','Tripod data cannot overwrite real telemetry');
 await page.click('[data-tab="training"]');await page.selectOption('#trainingQuality','software');await pause(200);assert(await page.locator('#trainingStage canvas').isVisible());assert.equal(await page.locator('.lesson-card').count(),10);await page.click('[data-lesson="3"]',{force:true});assert.match(await page.locator('#trainingMessage').innerText(),/earlier lesson/);await page.click('#trainingStart');await page.click('#trainingArm');await page.waitForFunction(()=>AerionTraining.model.armed);await page.fill('#trainingThrottleSlider','1700');await page.waitForFunction(()=>AerionTraining.model.y>.3,null,{timeout:8000});await page.screenshot({path:path.join(out,'training_flying.png')});await page.click('[data-tab="telemetry"]');await page.click('[data-tab="training"]');assert(await page.locator('#trainingOverlay').isVisible());
 // The bridge obtains an output-inhibited lease without ever publishing motor RC.
 const ID='ZFC-001122334455';let active=false,session='',owner='',input='APP',ends=0,pings=0;
 await page.route('http://training-kit.test/**',r=>{const f=Object.fromEntries(new URLSearchParams(r.request().postData()||''));if(f.type==='training_end'&&f.session===session){active=false;ends++}if(f.type==='training_ping')pings++;return r.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify({ok:true,deviceId:ID,active,outputsBlocked:active,supported:true,input})})});
 await page.evaluate(ID=>{window.bridgeCalls=[];window.testTrainingActive=false;window.zebjusSchool={client:{base:'http://training-kit.test',clientId:'TEST-LAPTOP'},getSelectedDevice:()=>({deviceId:ID,boardId:'ZFC-A2',armed:false,benchMode:0}),isSelectedConnected:()=>true,prepareFcSetup:async()=>{},releaseLock:async()=>{},commandDevice:async d=>{bridgeCalls.push(d);if(d.type==='training_status')return{ok:true,deviceId:ID,supported:true};if(d.type==='training_begin'){await window.enableTestLease(d);return {ok:true,deviceId:ID,active:true,outputsBlocked:true}}throw Error('Unexpected hardware command '+d.type);}}},ID);
 await page.exposeFunction('enableTestLease',d=>{session=d.session;input=d.source;active=true});
 await page.selectOption('#trainingInput','APP');await page.check('#trainingProps');await page.click('#trainingEnable');await page.waitForFunction(()=>AerionTraining.bridge?.confirmed);assert(active);await page.evaluate(()=>{window.testTelemetryOn=true;window.testTelemetry=null;window.testTelemetryTimer=setInterval(()=>{if(testTelemetryOn&&testTelemetry)window.dispatchEvent(new CustomEvent('aerion-telemetry',{detail:testTelemetry}))},50)});const tel=(c,src='WEB_STA',id=ID)=>page.evaluate(({c,src,id})=>{window.testTelemetry={deviceId:id,trainingActive:true,rc:c,rcAgeMs:10,rcSource:src,expansion:{ppmArmMode:'YAW_LEFT'}};window.testTelemetryOn=true;window.dispatchEvent(new CustomEvent('aerion-telemetry',{detail:testTelemetry}))},{c,src,id});let c=[1500,1500,1000,1500,1000,1000];await tel(c);await page.click('#trainingStart');await page.waitForFunction(()=>AerionTraining.model.lowSeen);c[4]=2000;await tel(c);await page.waitForFunction(()=>AerionTraining.model.armed);c[2]=1700;await tel(c);await page.waitForFunction(()=>AerionTraining.model.y>.3,null,{timeout:8000});assert.equal(await page.evaluate(()=>bridgeCalls.filter(d=>d.type==='rc_frame').length),0);await page.evaluate(()=>window.testTelemetryOn=false);await page.waitForFunction(()=>!document.getElementById('trainingOverlay').hidden,null,{timeout:5000});assert(await page.locator('#trainingOverlay').isVisible());assert.match(await page.locator('#trainingMessage').innerText(),/frames stopped/);await tel([1500,1500,1000,1500,1000,1000]);await page.click('#trainingPause');await page.click('[data-tab="io"]');await pause(200);assert(!active&&ends>0);assert(await page.evaluate(()=>!AerionTraining.bridge));await page.evaluate(()=>clearInterval(window.testTelemetryTimer));
 await page.click('[data-tab="telemetry"]');const sensorPacket=ready=>page.evaluate(({ready,ID})=>window.dispatchEvent(new CustomEvent('aerion-telemetry',{detail:{deviceId:ID,flightReady:ready,flightCoreIntegrated:true,roll:ready?12:0,pitch:ready?-3:0,yaw:ready?90:0,gyroX:1.5,sensors:{imu:{fresh:ready,usedInFlight:ready}},batteryValid:false}})),{ready,ID});await sensorPacket(true);await page.waitForFunction(()=>document.getElementById('telRoll').textContent==='12.00°');await sensorPacket(false);await page.waitForFunction(()=>document.getElementById('gaugeAttitude').textContent==='SENSOR NOT AVAILABLE');assert.equal(await page.locator('#telRoll').innerText(),'—','unready FC placeholder angles cannot be presented as live attitude');
 // Portrait software view and every page remain inside the viewport.
 await page.setViewportSize({width:390,height:844});for(const tab of ['setup','io','firmware','telemetry','training']){await page.click(`[data-tab="${tab}"]`);await pause(100);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),tab+' overflows');}await page.screenshot({path:path.join(out,'mobile_training.png')});
 assert.deepEqual(errors,[]);console.log('PASS: navigation, individual hardware tools, merged connection/upgrade controls, honest instrument gauges, software 3D, lesson locks, RC-driven virtual flight, inhibited app bridge, stale pause/neutral resume/page-exit STOP and mobile width');
})().catch(async e=>{console.error(e);if(page){console.error('Training state:',await page.evaluate(()=>({message:document.getElementById('trainingMessage')?.textContent,bridge:!!window.AerionTraining?.bridge,input:window.AerionTraining?.source,y:window.AerionTraining?.model.y,result:window.AerionTraining?.model.result,armed:window.AerionTraining?.model.armed,lowSeen:window.AerionTraining?.model.lowSeen,time:window.AerionTraining?.model.time,channels:window.AerionTraining?.model.channels})).catch(()=>null));const out=process.env.ZEBJUS_LEARNING_SCREENSHOTS||path.resolve(root,'../learning_lab_screenshots');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'test_failure.png'),fullPage:true}).catch(()=>{})}process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)server.kill('SIGTERM')});
