'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright');
const pause=ms=>new Promise(r=>setTimeout(r,ms));let browser;
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.ZEBJUS_CHROMIUM});const page=await browser.newPage({viewport:{width:920,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://setup.test/**',r=>r.fulfill({contentType:'text/html',body:'<meta charset="UTF-8"><div id="wizard"></div>'}));await page.goto('http://setup.test/');await page.addScriptTag({path:path.resolve(__dirname,'../fc-setup.js')});await page.addScriptTag({path:path.resolve(__dirname,'../kit-console.js')});await page.evaluate(()=>{document.body.style.background='#081522';document.body.style.color='#dceefa';document.getElementById('wizard').classList.add('kit-console')});
 await page.evaluate(()=>{
  const s=window.mock={id:'ZFC-001122334455',supported:true,owned:false,active:false,session:'',airframe:'QUAD_X',input:'WEB',job:0,samples:0,total:0,benchMode:0,pulse:1000,escStage:0,until:0,ppmFresh:true,raw:[1500,1500,1000,1500,1000,1000,1500,1500,1500,1500],channels:[1500,1500,1000,1500,1000,1000,1500,1500,1500,1500],idleUs:1100,receiver:{calibrated:false,map:[1,2,3,4,5,6],minimum:Array(6).fill(1000),centre:Array(6).fill(1500),maximum:Array(6).fill(2000),reverse:Array(4).fill(false),armMode:'YAW_RIGHT'},calls:[],cancelled:[],delay:0,failJob:false};
  function status(){if(s.until&&performance.now()>=s.until){s.benchMode=0;s.until=0;s.pulse=1000}if(s.job===1){s.samples=Math.min(s.total,s.samples+s.total/3);if(s.samples>=s.total)s.job=s.failJob?3:2}return {ok:true,deviceId:s.id,boardId:'ZFC-A2',firmware:'18.3.64',supported:s.supported,active:s.active,session:s.active?s.session:'',armed:false,flightReady:false,airframe:s.airframe,input:s.input,job:s.job,samples:s.samples,total:s.total,benchMode:s.benchMode,pulse:s.pulse,escStage:s.escStage,ppmFresh:s.ppmFresh,receiver:structuredClone(s.receiver),raw:[...s.raw],channels:[...s.channels]}}
  window.wizard=AerionFcSetup.mount(document.getElementById('wizard'),{kit:()=>({deviceId:s.id,boardId:'ZFC-A2',armed:false,flightReady:false,rcTimeoutMs:1000}),owned:()=>s.owned,ensureControl:async()=>{s.owned=true},command:async d=>{
   s.calls.push(structuredClone(d));if(d.type==='setup_begin'){if(s.delay)await new Promise(r=>setTimeout(r,s.delay));if(s.cancelled.includes(d.session))throw Error('cancelled session');s.active=true;s.session=d.session}
   else if(d.type==='setup_end'){s.cancelled.push(d.session);if(d.session===s.session){s.active=false;s.benchMode=0}}
   else if(d.type==='setup_calibrate'){s.total=d.kind==='gyro'?2000:120;s.samples=0;s.job=1}
   else if(d.type==='setup_motor'){s.benchMode=1;s.pulse=d.pulse;s.until=performance.now()+d.durationMs}
   else if(d.type==='setup_esc'){s.benchMode=4;s.pulse=d.stage==='HIGH'?2000:1000;s.escStage=d.stage==='HIGH'?0:1;s.until=performance.now()+(d.stage==='HIGH'?12000:300)}
   else if(d.type==='airframe_set')s.airframe=d.airframe;
   else if(d.type==='input_set')s.input=d.source;
   else if(d.type==='flight_settings_set')s.idleUs=d.idleUs;
   else if(d.type==='snapshot_get')return {ok:true,flightSettings:{idleUs:s.idleUs}};
   else if(d.type==='pinmap_get')return {ok:true,expansion:{motors:[1,2,3,4].map((motor,i)=>({motor,connector:'D'+[1,2,3,0][i]}))}};
   else if(d.type==='receiver_setup_set'){s.receiver.calibrated=true;s.receiver.armMode=d.armMode;for(let i=0;i<6;i++){s.receiver.map[i]=d['map'+i];s.receiver.minimum[i]=d['min'+i];s.receiver.centre[i]=d['centre'+i];s.receiver.maximum[i]=d['max'+i];if(i<4)s.receiver.reverse[i]=!!d['reverse'+i]}}
   else if(d.type==='receiver_setup_get')return {ok:true,receiver:structuredClone(s.receiver)};
   return status();
  }});
 });
 const click=n=>page.click(`[data-fs="${n}"]`),next=async title=>{await click('next');await page.waitForFunction(t=>document.querySelector('.fs-title').textContent.includes(t),title)},message=txt=>page.waitForFunction(t=>document.querySelector('.fs-status').textContent.includes(t),txt);
 await click('detect');await message('Remove every propeller');await page.check('[data-fs=props]');await page.evaluate(()=>mock.supported=false);await click('detect');await message('bridge-only');await page.evaluate(()=>mock.supported=true);await click('detect');await message('Arming is inhibited');await next('Airframe');
 await page.selectOption('[data-fs=airframe]','QUAD_H');await click('saveFrame');await message('QUAD_H');await next('Sensors');
 await page.evaluate(()=>mock.failJob=true);await click('gyro');await message('Calibration failed');await page.evaluate(()=>mock.failJob=false);await click('gyro');await message('gyro calibration completed');await click('level');await message('level calibration completed');await next('ESC');
 await click('high');await message('HIGH active');assert(await page.locator('[data-fs=next]').isDisabled());await click('low');await message('LOW completed');await page.check('[data-fs=tones]');await click('confirmEsc');await next('Motor idle');
 for(let i=0;i<4;i++){await page.selectOption('[data-fs=motor]',String(i));if(i===1)await click('plus');await click('testMinimum');await message('800 ms motor test finished');await page.waitForFunction(()=>!document.querySelector('[data-fs=back]').disabled);await click('markStart')}
 await click('saveIdle');await message('Motor idle saved');assert.equal(await page.evaluate(()=>mock.idleUs),1075);await next('Rotation');await page.click('[data-motor="0"]');assert(!await page.isChecked('[data-motor="0"]'),'untested rotation cannot be confirmed');await page.selectOption('[data-fs=runMask]','15');await click('rotationTest');await page.waitForFunction(()=>!document.querySelector('[data-fs=back]').disabled);for(let i=0;i<4;i++)await page.check(`[data-motor="${i}"]`);await next('Receiver');
 await page.selectOption('[data-fs=source]','PPM');await click('saveInput');await click('sweep');for(const v of [1000,2000]){await page.evaluate(v=>mock.raw.fill(v),v);await pause(650)}await page.evaluate(()=>mock.raw=[1500,1500,1000,1500,1000,1000,1500,1500,1500,1500]);await pause(650);await click('centres');await click('saveReceiver');await message('saved and read back');await pause(350);await page.screenshot({path:process.env.ZEBJUS_SETUP_SCREENSHOT||path.resolve(__dirname,'../../fc_setup_receiver_v64.png')});await next('Arm / failsafe');
 await page.selectOption('[data-fs=armMode]','YAW_LEFT');await click('saveArm');await message('Arm method saved');assert.equal(await page.evaluate(()=>mock.receiver.armMode),'YAW_LEFT');await click('watchLoss');await page.evaluate(()=>mock.ppmFresh=false);await pause(700);await page.evaluate(()=>mock.ppmFresh=true);await pause(700);await click('confirmLoss');await next('Finish');await click('finish');await message('Setup finished');assert(!await page.evaluate(()=>mock.active));assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('aerion-fc-setup-'+mock.id)).physicalFlightTested===false));
 // STOP while begin is delayed: compensate the late grant with the same nonce.
 await page.evaluate(()=>{document.getElementById('wizard').remove();const root=document.createElement('div');root.id='second';document.body.append(root);mock.delay=700;window.second=AerionFcSetup.mount(root,{kit:()=>({deviceId:mock.id,armed:false}),owned:()=>true,command:async d=>{mock.calls.push(d);if(d.type==='setup_status')return {deviceId:mock.id,supported:true};if(d.type==='setup_begin'){await new Promise(r=>setTimeout(r,mock.delay));mock.active=true;mock.session=d.session;return {deviceId:mock.id,active:true,session:d.session}}if(d.type==='setup_end'){if(mock.session===d.session)mock.active=false;return {ok:true}}}})});
 await page.check('#second [data-fs=props]');await page.click('#second [data-fs=detect]');await pause(100);await page.click('#second [data-fs=stop]');await pause(1000);assert(!await page.evaluate(()=>mock.active));assert(!await page.evaluate(()=>second.active));assert.deepEqual(errors,[]);
 console.log('PASS: actual wizard board / props gates, failed calibration retry, ESC HIGH→LOW, motor start / all rotation, PPM endpoints/readback, yaw-left and loss/restore, disarmed finish and delayed begin STOP');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close()});
