'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');let browser;
(async()=>{browser=await chromium.launch({headless:true,executablePath:process.env.ZEBJUS_CHROMIUM});const page=await browser.newPage({viewport:{width:900,height:550},hasTouch:true});await page.setContent('<div id="zone" style="width:280px;height:250px"><i></i></div>');await page.addScriptTag({path:path.resolve(__dirname,'../control-sticks.js')});await page.evaluate(()=>{window.moves=[];window.bound=AerionSticks.bind(document.getElementById('zone'),{change:(...v)=>moves.push(v)});});
 const box=await page.locator('#zone').boundingBox(),point={x:box.x+8,y:box.y+7};await page.mouse.move(point.x,point.y);await page.mouse.down();let result=await page.evaluate(()=>({x:bound.state.x,y:bound.state.y,last:moves.at(-1),anchor:bound.state.anchor}));assert.equal(result.x,0);assert.equal(result.y,0);assert.deepEqual(result.anchor,point);assert.equal(result.last[0],0);assert.equal(result.last[1],0);
 await page.mouse.move(point.x+25,point.y-10);result=await page.evaluate(()=>({x:bound.state.x,y:bound.state.y}));assert(result.x>0&&result.y<0);await page.mouse.up();assert.deepEqual(await page.evaluate(()=>[bound.state.x,bound.state.y]),[0,0]);assert.equal(await page.locator('#zone').evaluate(el=>getComputedStyle(el,':before').content),'none');
 // Installed app code receives real pointer events. Touch blank space creates
 // an exact neutral centre; subsequent relative travel sends pitch / roll.
 const html=fs.readFileSync(path.resolve(__dirname,'../flight/index.html'),'utf8');const calls=[];let owner='';await page.route('**/*',async route=>{const u=new URL(route.request().url()),d=Object.fromEntries(new URLSearchParams(route.request().postData()||''));let body={ok:true};if(u.pathname==='/api/status')body={ok:true,kit:'ZEBJUS_FLIGHTCORE',deviceId:'ZFC-001122334455',name:'Kit',mode:'AP',ip:'192.168.4.1',flightReady:true,armed:false,locked:!!owner,lockMine:u.searchParams.get('clientId')===owner};else if(u.pathname==='/api/telemetry')body={ok:true,deviceId:'ZFC-001122334455'};else if(u.pathname==='/api/control/acquire'){owner=d.clientId;body={ok:true,rcTimeoutMs:1000}}else if(u.pathname==='/api/control/release')owner='';else if(d.type==='rc_frame'){calls.push(d.channels.split(',').map(Number));}await route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify(body)});});await page.goto('http://192.168.4.1/');await page.setContent(html);await page.waitForFunction(()=>!document.getElementById('heroAction').disabled);await page.click('#heroAction');await page.waitForFunction(()=>document.getElementById('hero').hidden);await page.waitForTimeout(1300);const zone=await page.locator('#right').boundingBox(),p={x:zone.x+12,y:zone.y+12};await page.mouse.move(p.x,p.y);await page.mouse.down();await page.waitForFunction(()=>document.getElementById('right').classList.contains('touching'));await page.waitForTimeout(80);assert.deepEqual(calls.at(-1).slice(0,2),[1500,1500]);const centre=await page.locator('#right .base').evaluate(e=>{const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}});assert(Math.abs(centre.x-p.x)<1&&Math.abs(centre.y-p.y)<1,JSON.stringify({centre,p,floating:await page.evaluate(()=>AerionSticks.settings()),base:await page.locator('#right .base').evaluate(e=>({left:e.style.left,top:e.style.top,transform:getComputedStyle(e).transform})),zone}));await page.mouse.move(p.x+25,p.y-18);await page.waitForTimeout(80);assert(calls.at(-1)[0]>1500&&calls.at(-1)[1]>1500);await page.mouse.up();
 for(const size of [{width:900,height:550},{width:390,height:844}]){await page.setViewportSize(size);const arrows=await page.locator('#right .base').evaluate(e=>{const b=e.getBoundingClientRect(),c={x:b.x+b.width/2,y:b.y+b.height/2};return [...e.querySelectorAll('.dir')].map(a=>{const r=a.getBoundingClientRect();return{side:a.classList.contains('up')||a.classList.contains('down')?'vertical':'horizontal',x:r.x+r.width/2-c.x,y:r.y+r.height/2-c.y}})});for(const a of arrows)assert(Math.abs(a.side==='vertical'?a.x:a.y)<1,'arrow aligned through the stick centre');}
 // A cold controller can grant settings ownership without transmitting RC.
 const cold=await browser.newPage({viewport:{width:920,height:600}});let coldOwner='',coldSession='',coldActive=false,coldFrames=0;
 await cold.route('**/*',async route=>{const u=new URL(route.request().url()),d=Object.fromEntries(new URLSearchParams(route.request().postData()||''));let response={ok:true};if(u.pathname==='/api/status')response={ok:true,kit:'ZEBJUS_FLIGHTCORE',deviceId:'ZFC-001122334455',name:'Cold kit',mode:'AP',ip:'192.168.4.1',flightReady:false,armed:false,locked:!!coldOwner,lockMine:u.searchParams.get('clientId')===coldOwner};else if(u.pathname==='/api/control/acquire')coldOwner=d.clientId;else if(u.pathname==='/api/control/release')coldOwner='';else if(d.type==='rc_frame')coldFrames++;else if(d.type==='setup_begin'){coldSession=d.session;coldActive=true;}else if(d.type==='setup_end')coldActive=false;if(d.type?.startsWith('setup_'))response={ok:true,deviceId:'ZFC-001122334455',boardId:'ZFC-A2',firmware:'18.3.65',supported:true,active:coldActive,session:coldActive?coldSession:'',armed:false,benchMode:0,job:0,raw:Array(10).fill(1500),channels:Array(10).fill(1500)};await route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify(response)});});
 await cold.goto('http://192.168.4.1/');await cold.setContent(html);await cold.waitForFunction(()=>document.getElementById('connectionLabel').textContent==='Cold kit');await cold.click('#kitSettings');await cold.click('[data-mobile-tab="Safety"]');assert.equal(await cold.locator('[data-kc=setupWizard]').count(),0);assert.equal(coldFrames,0);assert((await cold.locator('[data-mobile=safety]').textContent()).includes('NOT READY'));await cold.close();
 console.log('PASS: shared and installed floating sticks stay neutral at blank / edge touch, move relative to exact touch centre, release centred, remove duplicate crosshairs and align app arrows in both orientations');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close()});
