'use strict';
const assert=require('node:assert/strict'),{FlightTraining,lessons,neutral}=require('../flight-training-core.js');
assert.equal(lessons.length,16);assert.equal(new Set(lessons.map(l=>l.title)).size,16);
const tick=(m,c,n=1,extra={})=>{for(let i=0;i<n;i++)m.tick(.025,c,extra)};
let m=new FlightTraining().start(),ch=[...neutral];ch[4]=2000;tick(m,ch,10);assert(!m.armed,'high ARM without low observation is rejected');ch[4]=1000;tick(m,ch);ch[4]=2000;tick(m,ch);assert(m.armed);
// Closed-loop pilot flies the whole first lesson using only channel frames.
let landed=false;for(let i=0;i<5000&&m.result==='running';i++){const target=m.hold>=m.lesson.hold?.15:1.9;ch[2]=Math.max(1000,Math.min(2000,1500+(target-m.y)*220-m.vy*230));tick(m,ch);if(m.result==='complete')landed=true;}assert(landed,'takeoff, hold and soft landing complete via RC input');assert(m.landingQuality<.8);
// Stick direction, yaw and deliberate PPM dwell/release are meaningful.
m=new FlightTraining(3).start();ch=[...neutral];tick(m,ch);ch[4]=2000;tick(m,ch);ch[2]=1700;ch[1]=2000;tick(m,ch,60);assert(m.z<0);assert(m.y>.65);
m=new FlightTraining().start();ch=[...neutral];ch[3]=1000;tick(m,ch,41,{ppm:true,armMode:'YAW_LEFT'});assert(m.armed);ch[3]=1500;tick(m,ch,2,{ppm:true,armMode:'YAW_LEFT'});ch[3]=2000;tick(m,ch,41,{ppm:true,armMode:'YAW_LEFT'});assert(!m.armed);
// A gentle input error cannot silently bypass collision or hard-landing failure.
m=new FlightTraining(5).start();m.x=0;m.z=-4;m.y=2;tick(m,neutral);assert.equal(m.result,'failed');assert.match(m.reason,/collision/);
m=new FlightTraining().start();m.y=.23;m.vy=-3;m.airborne=true;tick(m,neutral);assert.equal(m.result,'failed');assert.match(m.reason,/Hard landing/);
m=new FlightTraining(6).start();m.time=4.5;tick(m,neutral);assert(Math.hypot(m.windX,m.windZ)>.1,'gusts change the flight dynamics');
// Mission actions require location, altitude, speed and exact LED message.
m=new FlightTraining(7).start();assert.match(m.action('signal',lessons[7].pattern),/Hover near/);m.z=-5;m.y=2;assert.match(m.action('signal',Array(8).fill(0)),/differs/);assert(!m.signalSent);assert.match(m.action('signal',lessons[7].pattern),/received/);assert(m.signalSent);
m=new FlightTraining(8).start();assert.match(m.action('pickup'),/Reach/);m.x=-5;m.z=-4;m.y=.6;assert.match(m.action('pickup'),/secured/);assert(m.payload);assert.match(m.action('drop'),/Reach/);m.x=5;m.z=-5;assert.match(m.action('drop'),/delivered/);assert(m.delivered&&!m.payload);
m=new FlightTraining(9).start();m.x=-4;m.z=-8;m.y=.6;m.action('pickup');m.x=4;assert.match(m.action('drop'),/signal/);m.y=2;m.action('signal',lessons[9].pattern);m.y=.6;assert.match(m.action('drop'),/delivered/);assert(m.obstacles().some(o=>o.moving));
m=new FlightTraining().start();tick(m,[NaN,1500,1000,1500,1000,1000]);assert.equal(m.result,'failed');
// Forward/backward and right/left stay in the aircraft's body axes at every cardinal heading.
for(const heading of[0,90,180,270])for(const [axis,sign]of[[1,1],[1,-1],[0,1],[0,-1]]){m=new FlightTraining(3).start();ch=[...neutral];m.tick(0,ch);ch[4]=2000;m.tick(0,ch);m.y=2;m.yaw=heading;ch[2]=1500;ch[axis]=1500+sign*350;tick(m,ch,24);const a=heading*Math.PI/180,expectedX=axis===1?Math.sin(a):Math.cos(a),expectedZ=axis===1?-Math.cos(a):Math.sin(a);assert((m.x*expectedX+m.z*expectedZ)*sign>.03,'movement follows the nose/right axis');assert(Math.abs(m.x*expectedZ-m.z*expectedX)<.001,'no unexplained sideways drift');assert.equal(m.result,'running');}
// An armed aircraft on its skids does not slide, bank or turn from full stick inputs.
m=new FlightTraining(3).start();ch=[...neutral];m.tick(0,ch);ch[4]=2000;m.tick(0,ch);ch[0]=ch[1]=ch[3]=2000;tick(m,ch,80);assert.deepEqual([m.x,m.z,m.yaw,m.pitch,m.roll],[0,0,0,0,0]);
// Physics remains close across tick sizes, including tilt and acceleration response.
const trajectory=hz=>{const m=new FlightTraining(3).start(),c=[...neutral];m.tick(0,c);c[4]=2000;m.tick(0,c);m.y=2;c[2]=1500;c[0]=1660;c[1]=1720;c[3]=1560;for(let n=0;n<hz*2;n++)m.tick(1/hz,c);return m};const coarse=trajectory(30),fine=trajectory(120);assert(Math.hypot(coarse.x-fine.x,coarse.z-fine.z)<.09);assert(Math.abs(coarse.yaw-fine.yaw)<.3);
// Closed-loop RC pilot: navigation, directed passage and contact are real flight behaviour.
const aircraft=level=>{const m=new FlightTraining(level).start(),c=[...neutral];m.tick(0,c);c[4]=2000;m.tick(0,c);return{m,c}};
function fly(m,c,target,until,max=7000){for(let i=0;i<max&&m.result==='running';i++){const a=m.yaw*Math.PI/180,ax=Math.max(-2.4,Math.min(2.4,(target.x-m.x)*1.25-m.vx*1.8)),az=Math.max(-2.4,Math.min(2.4,(target.z-m.z)*1.25-m.vz*1.8));c[0]=1500+(ax*Math.cos(a)+az*Math.sin(a))/3.2*500;c[1]=1500+(ax*Math.sin(a)-az*Math.cos(a))/3.2*500;c[2]=Math.max(1000,Math.min(2000,1500+(target.y-m.y)*220-m.vy*230));c[3]=1500+Math.max(-400,Math.min(400,(((target.yaw??0)-m.yaw+540)%360-180)*8));m.tick(.025,c);if(until(m))return true;}return false;}
const settled=(m,p)=>Math.hypot(m.x-p.x,m.z-p.z)<.25&&Math.abs(m.y-p.y)<.15&&Math.hypot(m.vx,m.vz)<.3&&Math.abs(m.vy)<.2&&Math.abs(((m.yaw-(p.yaw??0)+540)%360)-180)<6;
let craft=aircraft(4);m=craft.m;ch=craft.c;let g=m.gates()[0],entry={x:g.x-g.nx*1.6,z:g.z-g.nz*1.6,y:g.y},exit={x:g.x+g.nx*1,z:g.z+g.nz*1,y:g.y};assert.equal(m.navigation().direction,'FORWARD');assert.equal(m.navigation().height,2);assert.equal(m.navigation().homeRange,0);assert.equal(m.navigation().finishRange,12);assert.equal(m.navigation().ringRange,4);m.yaw=90;assert.equal(m.navigation().direction,'LEFT');assert.equal(m.navigation(true).name,'HOME');m.yaw=0;
assert(fly(m,ch,entry,q=>settled(q,entry)),'RC pilot reaches ring entry');assert.equal(m.point,0,'hovering before a ring does not pass it');assert(fly(m,ch,exit,q=>q.point===1),'RC flight crosses the opening in its entry direction');assert.equal(m.ringContacts,0);
// Wrong direction or height does not pass, and navigation returns pilots to the entry side.
craft=aircraft(4);m=craft.m;ch=craft.c;g=m.gates()[0];m.x=exit.x;m.z=exit.z;m.y=2;assert.match(m.navigation().phase,/entry side/);assert(fly(m,ch,entry,q=>settled(q,entry)));assert.equal(m.point,0,'reverse ring crossing cannot score');
craft=aircraft(4);m=craft.m;ch=craft.c;m.y=4;const highExit={...exit,y:4};assert(fly(m,ch,highExit,q=>settled(q,highExit)));assert.equal(m.point,0,'flying above the hoop cannot score');
// The physical frame stops motion, emits one contact event, permits back-off and explicit recovery.
craft=aircraft(4);m=craft.m;ch=craft.c;g=m.gates()[0];const rimEntry={...entry,x:entry.x+g.nz*.95,z:entry.z-g.nx*.95},rimExit={...exit,x:exit.x+g.nz*.95,z:exit.z-g.nx*.95};assert(fly(m,ch,rimEntry,q=>settled(q,rimEntry)));assert(fly(m,ch,rimExit,q=>q.stuck),'rim contact blocks a flying drone');const blocked={x:m.x,y:m.y,z:m.z};assert.equal(m.ringContacts,1);assert.match(m.alert.text,/CONTACT/);fly(m,ch,rimExit,()=>false,40);assert.equal(m.ringContacts,1,'held forward input cannot flood contact alerts');assert(Math.hypot(m.x-blocked.x,m.z-blocked.z)<.06);assert.equal(m.point,0);assert(fly(m,ch,rimEntry,q=>!q.stuck),'backward control frees the drone');assert(fly(m,ch,rimExit,q=>q.stuck));assert.match(m.action('recover'),/recovered/);assert(!m.stuck);assert.equal(m.point,0,'recovery must not skip the ring');assert(m.gateDepth(m,g)<-1);
craft=aircraft(4);m=craft.m;ch=craft.c;g=m.gates()[1];m.x=g.x+g.nz*g.radius;m.z=g.z-g.nx*g.radius;m.y=g.y;ch[2]=1500;tick(m,ch);assert(m.stuck);assert.equal(m.navigation().ringIndex,1,'contact guidance identifies the actual frame even before its mission turn');assert.match(m.navigation().name,/RING 2/);assert.match(m.navigation().phase,/Back away/);
// Every height-changing gate has the same physical and displayed target.
craft=aircraft(10);m=craft.m;ch=craft.c;for(const ring of m.gates()){const before={x:ring.x-ring.nx*1.6,z:ring.z-ring.nz*1.6,y:ring.y},after={x:ring.x+ring.nx*1.1,z:ring.z+ring.nz*1.1,y:ring.y};assert.equal(m.navigation().height,ring.y);assert(fly(m,ch,before,q=>settled(q,before)),`approach altitude ring ${ring.index+1}`);assert(fly(m,ch,after,q=>settled(q,after)),`depart altitude ring ${ring.index+1}`);assert.equal(m.point,ring.index+1);}assert.equal(m.ringContacts,0);assert(m.readyToLand());
// New action missions are gated by position, height, heading, speed and their prior tasks.
craft=aircraft(12);m=craft.m;ch=craft.c;assert.match(m.action('photo'),/Hold PHOTO/);for(const p of m.lesson.inspections){assert(fly(m,ch,p,q=>settled(q,p)));assert.match(m.action('photo'),/recorded/);}assert.equal(m.inspectionIndex,3);assert(m.readyToLand());
craft=aircraft(13);m=craft.m;ch=craft.c;assert.match(m.action('beacon'),/Deliver/);m.x=m.lesson.drop.x;m.z=m.lesson.drop.z;m.y=.6;m.delivered=true;m.vx=1;assert.match(m.action('beacon'),/hold/);m.vx=0;assert.match(m.action('beacon'),/transmitting/);assert(m.beaconSent);
// Fly all three landing-tour pads with RC input, including take-off between touchdowns.
craft=aircraft(14);m=craft.m;ch=craft.c;for(const [i,p]of m.lesson.landings.entries()){const overhead={...p,y:2};assert(fly(m,ch,overhead,q=>settled(q,overhead)));assert(fly(m,ch,{...p,y:.13},q=>q.landingIndex===i+1),`soft touchdown L${i+1}`);if(i<2){assert.equal(m.result,'running');assert(!m.padDeparted);tick(m,ch,8);assert.equal(m.landingIndex,i+1,'remaining on a pad cannot count twice');}}assert.equal(m.result,'complete');assert(m.landingQuality<.8);
craft=aircraft(15);m=craft.m;ch=craft.c;m.y=2;tick(m,[1500,1500,1500,1500,2000,1000],280);assert.equal(m.hold,0,'return hold starts only after the route');m.time=120;tick(m,ch);assert.equal(m.result,'failed');
console.log('PASS: 16 lesson curriculum; actual RC takeoff/hover/soft landing, yaw-left PPM, pitch direction, collision/hard landing/gust dynamics, directed ring passage / contact / back-off / recovery, height guidance, inspection / beacon / three real RC landings, LED message and payload mission gates');
