'use strict';
const assert=require('node:assert/strict'),{TrainingInput}=require('../flight-training-input.js'),{FlightTraining,neutral}=require('../flight-training-core.js');
// Rate throttle has no centre-tap jump, is monotonic and retains its setting on release.
let input=new TrainingInput();input.setStick('left',0,0);for(let i=0;i<120;i++)input.advance(1/120);assert.equal(input.channels[2],1000);
const up=new Set(['KeyW']);let previous=1000,maxStep=0;for(let i=0;i<120;i++){input.advance(1/120,up);assert(input.channels[2]>=previous);maxStep=Math.max(maxStep,input.channels[2]-previous);previous=input.channels[2];}assert(maxStep<3);assert(Math.abs(input.throttleTarget-1320)<.001);const target=input.throttleTarget;for(let i=0;i<120;i++)input.advance(1/120);assert.equal(input.throttleTarget,target);assert(Math.abs(input.channels[2]-target)<.001);
input.setThrottle(1800);const initial=input.channels[2];input.advance(1/120);assert(input.channels[2]>initial&&input.channels[2]<1400,'slider values blend instead of jumping');for(let i=0;i<120;i++)input.advance(1/120);assert(Math.abs(input.channels[2]-1800)<.01);
input.setStick('left',0,1);input.advance(.025);assert(input.throttleTarget>1800);input.setStick('left',0,0);const held=input.throttleTarget;input.advance(.025);assert.equal(input.throttleTarget,held);
// Opposing keys cancel; diagonal joystick travel is circular, with smooth recentring.
input.reset();for(let i=0;i<100;i++)input.advance(.01,new Set(['ArrowUp','ArrowDown','KeyW','KeyS']));assert.equal(input.channels[1],1500);assert.equal(input.throttleTarget,1000);input.setStick('right',1,1);assert(Math.hypot(input.sticks.right.x,input.sticks.right.y)<=1.00001);for(let i=0;i<40;i++)input.advance(.01);const pitch=input.channels[1];input.setStick('right',0,0);input.advance(.01);assert(input.channels[1]>1500&&input.channels[1]<pitch);for(let i=0;i<100;i++)input.advance(.01);assert(Math.abs(input.channels[1]-1500)<.1);input.centre();assert.deepEqual([input.channels[0],input.channels[1],input.channels[3]],[1500,1500,1500]);
// Same held inputs at 30/60/120 Hz produce the same throttle and almost identical axes.
const sample=hz=>{const i=new TrainingInput();for(let n=0;n<hz*2;n++)i.advance(1/hz,new Set(['KeyW','ArrowUp','KeyD']));return i};const slow=sample(30),fast=sample(120);assert(Math.abs(slow.throttleTarget-fast.throttleTarget)<.001);assert(Math.abs(slow.channels[2]-fast.channels[2])<5);assert(Math.abs(slow.channels[1]-fast.channels[1])<.001);
// Full take-off, hover and touchdown using the same smoothing as the browser.
const m=new FlightTraining().start();input.reset();m.tick(0,input.channels);input.channels[4]=2000;m.tick(0,input.channels);let steps=0;for(;steps<120*40&&m.result==='running';steps++){const height=m.hold>=m.lesson.hold?.16:1.9;input.setThrottle(1500+(height-m.y)*220-m.vy*250);m.tick(1/120,input.advance(1/120));}assert.equal(m.result,'complete','smoothed RC must allow a genuine soft landing');assert(m.landingQuality<.8);assert(m.time<40);
console.log('PASS: rate throttle, retained setting, smooth slider/axes, opposing inputs, circular sticks, render-rate independence and RC-driven take-off/hover/soft landing');
