'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{spawn}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),origin='http://localhost:8930',out=process.env.ZEBJUS_TRAINING_SCREENSHOTS||path.resolve(root,'../training_screenshots'),wait=ms=>new Promise(r=>setTimeout(r,ms));let server,browser,page;const errors=[];
async function picture(name){await page.locator('#trainingStage').evaluate(s=>s.scrollIntoView({block:'start'}));await wait(150);await page.locator('#trainingStage').screenshot({path:path.join(out,name+'.png')})}
async function stick(side,type,id,x=0,y=0){const p=page.locator(`[data-training-stick="${side}"]`),r=await p.locator('.training-stick-ring').boundingBox();await p.dispatchEvent(type,{pointerId:id,pointerType:'touch',button:0,buttons:type==='pointerup'?0:1,clientX:r.x+r.width*(.5+x*.29),clientY:r.y+r.height*(.5-y*.29),bubbles:true})}
(async()=>{
 fs.mkdirSync(out,{recursive:true});server=spawn('python3',[path.join(root,'start_offline.py'),'--no-browser','--port','8930'],{cwd:root});await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Server timeout')),10000);server.stdout.on('data',d=>{if(String(d).includes('offline WebApp:')){clearTimeout(t);resolve()}});server.on('error',reject)});
 browser=await chromium.launch({headless:true,executablePath:process.env.ZEBJUS_CHROMIUM,args:['--enable-unsafe-swiftshader']});page=await browser.newPage({viewport:{width:1440,height:1000},serviceWorkers:'block'});page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.waitForFunction(()=>window.__zebjusAppLoaded&&window.AerionTraining);await page.click('[data-tab="training"]');await page.waitForFunction(()=>AerionTraining.view?.renderer?.info.render.calls>0);await picture('arena_ready');
 assert.equal(await page.evaluate(()=>AerionTraining.view.mode),'chase');assert(await page.locator('#trainingMap').isVisible());assert.equal(await page.locator('[data-training-stick]').count(),2);
 await page.click('#trainingStart');await page.click('#trainingArm');await page.waitForFunction(()=>AerionTraining.model.armed);await page.locator('#trainingStage').click({position:{x:300,y:200}});
 await stick('left','pointerdown',11);await wait(200);await stick('left','pointerup',11);assert.equal(await page.evaluate(()=>AerionTraining.input.throttleTarget),1000,'centre tap cannot jump to half throttle');
 await page.keyboard.down('KeyW');await wait(200);await page.keyboard.up('KeyW');let sample=await page.evaluate(()=>({target:AerionTraining.input.throttleTarget,effective:AerionTraining.input.channels[2]}));assert(sample.target>1030&&sample.target<1150);assert(sample.effective<sample.target);await wait(250);assert.equal(await page.evaluate(()=>AerionTraining.input.throttleTarget),sample.target,'keyboard release retains throttle');
 await page.fill('#trainingThrottleSlider','1680');await page.waitForFunction(()=>AerionTraining.model.y>.85);await page.click('#trainingHover');await page.waitForFunction(()=>Math.abs(AerionTraining.input.channels[2]-1500)<2);await picture('takeoff_chase');
 // Actual keyboard motion and the model's tilt agree in the rendered drone.
 const before=await page.evaluate(()=>AerionTraining.model.z);await page.locator('#trainingStage').click({position:{x:300,y:200}});await page.keyboard.down('ArrowUp');await wait(450);let pose=await page.evaluate(()=>({pitch:AerionTraining.model.pitch,rotation:AerionTraining.view.drone.rotation.x,z:AerionTraining.model.z,channel:AerionTraining.input.channels[1]}));assert(pose.pitch>0&&pose.rotation<0&&pose.z<before,'forward pitch must lower the nose and move north');await page.keyboard.up('ArrowUp');await wait(180);assert((await page.evaluate(()=>AerionTraining.input.channels[1]))>1500,'release blends back to centre');await page.keyboard.down('ArrowDown');await wait(850);assert((await page.evaluate(()=>AerionTraining.model.vz))>0,'backward reverses velocity');await page.keyboard.up('ArrowDown');await wait(300);
 // Independent pointers permit simultaneous throttle and movement without centre jumps.
 const target=await page.evaluate(()=>AerionTraining.input.throttleTarget);await stick('left','pointerdown',21,0,.35);await stick('right','pointerdown',22,.35,.2);await wait(200);sample=await page.evaluate(()=>({target:AerionTraining.input.throttleTarget,roll:AerionTraining.input.channels[0]}));assert(sample.target>target&&sample.roll>1500);await stick('left','pointercancel',21);await stick('right','pointerup',22);const held=await page.evaluate(()=>AerionTraining.input.throttleTarget);await wait(200);assert.equal(await page.evaluate(()=>AerionTraining.input.throttleTarget),held);await page.click('#trainingHover');
 await page.click('#trainingCamera');assert.equal(await page.evaluate(()=>AerionTraining.view.mode),'fpv');assert(await page.locator('.training-crosshair').isVisible());await wait(150);assert.equal(await page.evaluate(()=>AerionTraining.view.drone.visible),false);await picture('fpv');await page.click('#trainingCamera');assert.equal(await page.evaluate(()=>AerionTraining.view.mode),'orbit');await picture('orbit');await page.click('#trainingCamera');assert.equal(await page.evaluate(()=>AerionTraining.view.mode),'overview');await picture('overview');assert(await page.locator('#trainingDroneMarker').isVisible());await page.click('#trainingFindDrone');assert.equal(await page.evaluate(()=>AerionTraining.view.mode),'chase');
 // Fly a complete lesson with RC input; scoring still requires hover and a genuine soft touchdown.
 await page.click('#trainingStart');await page.click('#trainingArm');await page.evaluate(()=>{window.trainingPilot=setInterval(()=>{const m=AerionTraining.model,target=m.hold>=m.lesson.hold?.16:1.9;AerionTraining.input.setThrottle(1500+(target-m.y)*220-m.vy*250)},16)});await page.waitForFunction(()=>AerionTraining.model.result==='complete',null,{timeout:40000});await page.evaluate(()=>clearInterval(window.trainingPilot));assert((await page.evaluate(()=>AerionTraining.model.landingQuality))<.8);await picture('soft_landing');
 // Exercise the course's actual geometry and dispose/rebuild path, not a separate mock scene.
 await page.evaluate(()=>localStorage.setItem('aerion-training-progress',JSON.stringify({schema:1,results:Array.from({length:10},()=>({complete:true}))})));await page.reload();await page.waitForFunction(()=>window.AerionTraining);await page.click('[data-tab="training"]');await page.click('[data-lesson="4"]');await page.click('#trainingStart');assert.equal(await page.evaluate(()=>AerionTraining.view.markers.length),3);await picture('precision_course');const resources=await page.evaluate(()=>AerionTraining.view.assets.size);for(let i=0;i<4;i++)await page.click('#trainingStart');assert.equal(await page.evaluate(()=>AerionTraining.view.assets.size),resources,'retries must not leak per-course materials');await page.click('[data-lesson="9"]');await page.click('#trainingStart');assert.equal(await page.evaluate(()=>AerionTraining.view.blocks.length),2);await picture('rescue_course');
 // Compact 320/390px Wix views retain both controls and a visible course map.
 for(const width of[390,320]){await page.setViewportSize({width,height:844});await page.goto(origin+'/?embed=wix&tab=training');await page.waitForFunction(()=>window.AerionTraining&&AerionTraining.view);await page.click('#trainingStart');const size=await page.evaluate(()=>({screen:innerWidth,scroll:document.documentElement.scrollWidth,stage:document.getElementById('trainingStage').getBoundingClientRect().height}));assert(size.scroll<=size.screen+2);assert(size.stage>=365);for(const side of['left','right']){const box=await page.locator(`[data-training-stick="${side}"]`).boundingBox();assert(box.width>=85&&box.x>=0&&box.x+box.width<=width);}await picture('wix_'+width);}
 await page.selectOption('#trainingQuality','software');await page.click('#trainingStart');await page.click('#trainingArm');await page.fill('#trainingThrottleSlider','1700');await page.waitForFunction(()=>AerionTraining.model.y>.4);assert.equal(await page.evaluate(()=>AerionTraining.view.software),true);await picture('lightweight');
 assert.deepEqual(errors,[]);const report={passed:true,checks:['smooth keyboard and slider throttle','no joystick centre jump','two independent touch pointers','forward/backward tilt and motion','chase/FPV/orbit/overview and find drone','RC takeoff/hover/soft landing','gate and rescue scene objects','course resource reuse','320px and 390px Wix controls','software fallback'],screenshots:fs.readdirSync(out).filter(x=>x.endsWith('.png'))};fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify(report,null,2)+'\n');console.log('PASS: '+report.checks.join('; '));
})().catch(async e=>{console.error(e);if(page){console.error(await page.evaluate(()=>({state:AerionTraining?.model.result,y:AerionTraining?.model.y,armed:AerionTraining?.model.armed,paused:AerionTraining?.paused,message:document.getElementById('trainingMessage')?.textContent,view:AerionTraining?.view?.mode})).catch(()=>null));await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{})}process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)server.kill('SIGTERM')});
