'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');let browser,server;const ID='ZFC-001122334455',calls=[];let lock='',ready=false,armed=false,dropRc=false,kitOffline=false,pickerCalls=0;
const status=()=>({ok:true,kit:'ZEBJUS_FLIGHTCORE',deviceId:ID,name:'zebjus_drone_1',boardId:'ZFC-A2',boardName:'Aerion F1',mode:'AP / DIRECT',firmware:'18.4.0',flightReady:ready,webRc:true,armed,rcSource:'WEB_AP',rcTimeoutMs:1000,locked:!!lock,lockMine:!!lock,imuModel:'MPU6050',rc:[1500,1500,1000,1500,1000,1000,1000,1000,1500,1000]});
(async()=>{
 server=http.createServer((req,res)=>{const filename=path.join(root,new URL(req.url,'http://test').pathname==='/'?'index.html':new URL(req.url,'http://test').pathname);if(!filename.startsWith(root)||!fs.existsSync(filename)){res.writeHead(404);res.end();return;}res.setHeader('content-type',filename.endsWith('.html')?'text/html':filename.endsWith('.js')||filename.endsWith('.mjs')?'text/javascript':'application/json');res.end(fs.readFileSync(filename));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({executablePath:process.env.ZEBJUS_CHROMIUM,headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1080,height:860},serviceWorkers:'block'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.pickerCalls=0;Object.defineProperty(navigator,'serial',{configurable:true,value:{requestPort(){window.pickerCalls++;return Promise.reject(new DOMException('Cancelled','NotFoundError'));}}});});
 await page.route('http://192.168.4.1/**',async route=>{const req=route.request(),u=new URL(req.url()),f=Object.fromEntries(new URLSearchParams(req.postData()||''));calls.push({path:u.pathname,...f});if(kitOffline)return route.abort();if(dropRc&&f.type==='rc_frame')return route.abort();let result=status(),code=200;
  if(u.pathname==='/api/control/acquire'){lock=f.clientId;result={ok:true,rcTimeoutMs:1000};}
  if(u.pathname==='/api/control/release'){if(lock===f.clientId)lock='';result={ok:true};}
  if(u.pathname==='/api/control/ping')result={ok:true};
  if(f.type==='rc_frame'){const c=f.channels.split(',').map(Number);armed=ready&&c[4]>1500;result={ok:true,deviceId:ID,armed,flightReady:ready};}
  if(f.type==='rc_source_set')result={ok:true};if(f.type==='snapshot_get')result={ok:true,deviceId:ID,sensors:{imu:{detected:true}},pid:{rateRoll:{P:.9,I:15,D:.035}}};
  await route.fulfill({status:code,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify(result)});
 });
 await page.goto(base);await page.waitForFunction(()=>!!window.AerionController);await page.click('#connect');await page.click('#checkConnection');await page.waitForFunction(()=>AerionController.state.online);assert.match(await page.locator('#connectionHealth').innerText(),/connected.*IMU/i,'IMU readiness is distinct from connectivity');
 await page.click('#control');await page.waitForFunction(()=>AerionController.state.tx);assert(await page.locator('#arm').isDisabled(),'missing IMU cannot arm');assert(calls.some(c=>c.path==='/api/control/acquire'),'control can be acquired while IMU needs setup');
 ready=true;await page.evaluate(()=>AerionController.refresh());await page.waitForFunction(()=>!document.getElementById('arm').disabled);await page.click('#arm');await page.waitForFunction(()=>AerionController.state.status.armed);await page.fill('#throttle','1350');await page.waitForFunction(()=>Math.round(AerionController.state.channels[2])===1350);const stick=await page.locator('#right').boundingBox();await page.mouse.move(stick.x+stick.width/2,stick.y+stick.height/2);await page.mouse.down();await page.mouse.move(stick.x+stick.width*.7,stick.y+stick.height*.4);await page.mouse.up();
 await page.click('#stop');await page.waitForFunction(()=>!AerionController.state.tx);await page.waitForTimeout(250);assert(calls.some(c=>c.type==='rc_frame'&&c.channels.startsWith('1500,1500,1000,1500,1000')),'STOP sends a disarmed neutral frame');
 await page.click('[data-page=setup]');await page.click('#readSettings');await page.waitForFunction(()=>document.getElementById('settingsResult').textContent.includes('sensors'));assert.equal(await page.locator('#pid-rateRollP').inputValue(),'.9'.replace('.9','0.9'));
 await page.click('[data-page=fly]');await page.click('#control');await page.waitForFunction(()=>AerionController.state.tx);dropRc=true;await page.waitForFunction(()=>!AerionController.state.tx,null,{timeout:4000});assert.equal(await page.evaluate(()=>AerionController.state.channels[4]),1000);dropRc=false;await page.waitForTimeout(1300);assert.equal(await page.evaluate(()=>AerionController.state.tx),false,'loss cannot silently enable or arm control');
 await page.click('[data-page=firmware]');await page.click('#fwConnectUsbBtn');await page.waitForFunction(()=>window.pickerCalls===1);assert.match(await page.locator('#fwUsbState').innerText(),/No port selected/);await page.click('#fwConnectUsbBtn');await page.waitForFunction(()=>window.pickerCalls===2);
 // A stalled firmware download must never block the browser's USB chooser.
 await page.route('**/FlightCore_Firmware/catalog.json*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({defaultBoardId:'ZFC-A2',boards:[{id:'ZFC-A2',name:'Aerion F1',imageChipIds:[13],latest:{version:'18.4.0',app:{available:true,file:'slow.bin'}}}]})}));await page.route('**/FlightCore_Firmware/slow.bin*',()=>{});await page.reload();await page.click('[data-page=firmware]');await page.waitForTimeout(350);await page.click('#fwAutoLoadBtn');await page.waitForTimeout(200);assert.equal(await page.locator('#fwConnectUsbBtn').isEnabled(),true);await page.click('#fwConnectUsbBtn');await page.waitForFunction(()=>window.pickerCalls===1);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:process.env.AERION_TEST_SCREENSHOT||path.join(root,'android-app/build/controller-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'390px page fits');
 assert.deepEqual(errors,[]);console.log('PASS: connected vs IMU readiness, acquire/manual ARM, sticks/throttle, STOP, PID read, RC loss/no auto-arm, USB cancel/retry and chooser during stalled firmware download, mobile layout');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)server.close();});
